
/*
 * Magic spells.
 */

{NORM,
 "reserved",
 {NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE,
  NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE},
 0,
 TAR_IGNORE,
 POS_STANDING,
 NULL,
 SLOT(0),
 0,
 0,
 FALSE,
 "",
 "",
 ""},

    {NORM,
     "acid blast",
     {50,     NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE,
      NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE,
      NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE},
     spell_acid_blast,
     TAR_CHAR_OFFENSIVE,
     POS_FIGHTING,
     NULL,
     SLOT(70),
     20,
     12,
     TRUE,
     "acid blast",
     "!Acid Blast!",
     ""},

    {NORM,
     "armor",
     {3,      NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE,
      NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE,
      NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE},
     spell_armor,
     TAR_CHAR_DEFENSIVE,
     POS_STANDING,
     NULL,
     SLOT(1),
     5,
     12,
     FALSE,
     "",
     "You feel less protected.",
     ""},

    {NORM,
     "animate",
     {NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE,
      NO_USE, NO_USE, 70,     NO_USE, NO_USE, NO_USE, NO_USE, NO_USE,
      70,     NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE},
     spell_animate,
     TAR_IGNORE,
     POS_STANDING,
     NULL,
     SLOT(525),
     50,
     24,
     FALSE,
     "",
     "!Animate!",
     ""},

    {NORM,
     "bad breath",
     {4,      NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE,
      NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE,
      NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE},
     spell_badbreath,
     TAR_CHAR_OFFENSIVE,
     POS_FIGHTING,
     NULL,
     SLOT(502),
     10,
     12,
     TRUE,
     "bad breath",
     "!Bad Breath!",
     ""},

    {NORM,
     "bark skin",
     {NO_USE, 20,     NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE,
      NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE,
      NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE},
     spell_bark_skin,
     TAR_CHAR_SELF,
     POS_STANDING,
     NULL,
     SLOT(514),
     20,
     24,
     FALSE,
     "",
     "Your skin feels softer.",
     "$n's skin looks less wooden."},

    {NORM,
     "bless",
     {NO_USE, 8,      NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE,
      NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE,
      NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE},
     spell_bless,
     TAR_CHAR_DEFENSIVE,
     POS_STANDING,
     NULL,
     SLOT(3),
     5,
     12,
     FALSE,
     "",
     "You feel less righteous.",
     "$n looks less Holy."},

    {NORM,
     "blindness",
     {16,     NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE,
      NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE,
      NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE},
     spell_blindness,
     TAR_CHAR_OFFENSIVE,
     POS_FIGHTING,
     &gsn_blindness,
     SLOT(4),
     5,
     12,
     TRUE,
     "",
     "You can see again.",
     "$n's vision returns."},

    {NORM,
     "bloody tears",
     {NO_USE, NO_USE, NO_USE, NO_USE, 26,     NO_USE, NO_USE, NO_USE,
      NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE,
      NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE},
     spell_bloody_tears,
     TAR_CHAR_OFFENSIVE,
     POS_FIGHTING,
     NULL,
     SLOT(518),
     12,
     12,
     TRUE,
     "Bloody Tears",
     "!Bloody Tears!",
     ""},

    {NORM,
     "burning hands",
     {6,      NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE,
      NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE,
      NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE},
     spell_burning_hands,
     TAR_CHAR_OFFENSIVE,
     POS_FIGHTING,
     NULL,
     SLOT(5),
     15,
     12,
     TRUE,
     "burning hands",
     "!Burning Hands!",
     ""},

    {NORM,
     "call lightning",
     {NO_USE, 36,     NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE,
      NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE,
      NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE},
     spell_call_lightning,
     TAR_IGNORE,
     POS_FIGHTING,
     NULL,
     SLOT(6),
     15,
     12,
     TRUE,
     "lightning bolt",
     "!Call Lightning!",
     ""},

    {NORM,
     "calm",
     {NO_USE, NO_USE, NO_USE, NO_USE, 52,     NO_USE, NO_USE, NO_USE,
      NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE,
      NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE},
     spell_calm,
     TAR_IGNORE,
     POS_FIGHTING,
     NULL,
     SLOT(531),
     30,
     24,
     FALSE,
     "",
     "!Calm!",
     ""},

    {NORM,
     "cause critical",
     {NO_USE, 58,     NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE,
      NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE,
      NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE},
     spell_cause_critical,
     TAR_CHAR_OFFENSIVE,
     POS_FIGHTING,
     NULL,
     SLOT(63),
     20,
     12,
     TRUE,
     "spell",
     "!Cause Critical!",
     ""},

    {NORM,
     "cause light",
     {NO_USE, 4,      NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE,
      NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE,
      NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE},
     spell_cause_light,
     TAR_CHAR_OFFENSIVE,
     POS_FIGHTING,
     NULL,
     SLOT(62),
     15,
     12,
     TRUE,
     "spell",
     "!Cause Light!",
     ""},

    {NORM,
     "cause serious",
     {NO_USE, 40,     NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE,
      NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE,
      NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE},
     spell_cause_serious,
     TAR_CHAR_OFFENSIVE,
     POS_FIGHTING,
     NULL,
     SLOT(64),
     17,
     12,
     TRUE,
     "spell",
     "!Cause Serious!",
     ""},

    {NORM,
     "change sex",
     {66,     NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE,
      NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE,
      NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE},
     spell_change_sex,
     TAR_CHAR_DEFENSIVE,
     POS_FIGHTING,
     NULL,
     SLOT(82),
     15,
     12,
     FALSE,
     "",
     "Your body feels familiar again.",
     "$n looks $mself again."},

    {NORM,
     "charm person",
     {NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE,
      NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE,
      NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE},
     spell_charm_person,
     TAR_CHAR_OFFENSIVE,
     POS_STANDING,
     &gsn_charm_person,
     SLOT(7),
     5,
     12,
     FALSE,
     "",
     "You feel more self-confident.",
     "The glazed look in $n's eyes fades."},

    {NORM,
     "chill touch",
     {8,      NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE,
      NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE,
      NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE},
     spell_chill_touch,
     TAR_CHAR_OFFENSIVE,
     POS_FIGHTING,
     NULL,
     SLOT(8),
     15,
     12,
     TRUE,
     "chilling touch",
     "You feel less cold.",
     ""},

    {NORM,
     "color spray",
     {7,      NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE,
      NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE,
      NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE},
     spell_color_spray,
     TAR_CHAR_OFFENSIVE,
     POS_FIGHTING,
     NULL,
     SLOT(10),
     15,
     12,
     TRUE,
     "color spray",
     "!color Spray!",
     ""},

    {NORM,
     "continual light",
     {11,     27,     NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE,
      NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE,
      NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE},
     spell_continual_light,
     TAR_IGNORE,
     POS_STANDING,
     NULL,
     SLOT(57),
     7,
     12,
     FALSE,
     "",
     "!Continual Light!",
     ""},

    {NORM,
     "control weather",
     {58,     79,     NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE,
      NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE,
      NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE},
     spell_control_weather,
     TAR_IGNORE,
     POS_STANDING,
     NULL,
     SLOT(11),
     25,
     12,
     FALSE,
     "",
     "!Control Weather!",
     ""},

    {NORM,
     "create food",
     {NO_USE, 26,     NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE,
      NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE,
      NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE},
     spell_create_food,
     TAR_IGNORE,
     POS_STANDING,
     NULL,
     SLOT(12),
     5,
     12,
     FALSE,
     "",
     "!Create Food!",
     ""},

    {NORM,
     "create spring",
     {NO_USE, 65,     NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE,
      NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE,
      NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE},
     spell_create_spring,
     TAR_IGNORE,
     POS_STANDING,
     NULL,
     SLOT(80),
     20,
     12,
     FALSE,
     "",
     "!Create Spring!",
     ""},

    {NORM,
     "create water",
     {NO_USE, 9,      NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE,
      NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE,
      NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE},
     spell_create_water,
     TAR_OBJ_INV,
     POS_STANDING,
     NULL,
     SLOT(13),
     5,
     12,
     FALSE,
     "",
     "!Create Water!",
     ""},

    {NORM,
     "cure blindness",
     {NO_USE, 28,     NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE,
      NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE,
      NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE},
     spell_cure_blindness,
     TAR_CHAR_DEFENSIVE,
     POS_FIGHTING,
     NULL,
     SLOT(14),
     5,
     12,
     FALSE,
     "",
     "!Cure Blindness!",
     ""},

    {NORM,
     "cure critical",
     {NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE,
      NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE,
      NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE},
     spell_cure_critical,
     TAR_CHAR_DEFENSIVE,
     POS_FIGHTING,
     NULL,
     SLOT(15),
     20,
     12,
     FALSE,
     "",
     "!Cure Critical!",
     ""},

    {NORM,
     "cure light",
     {NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE,
      NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE,
      NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE},
     spell_cure_light,
     TAR_CHAR_DEFENSIVE,
     POS_FIGHTING,
     NULL,
     SLOT(16),
     10,
     12,
     FALSE,
     "",
     "!Cure Light!",
     ""},

    {NORM,
     "cure poison",
     {NO_USE, 32,     NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE,
      NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE,
      NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE},
     spell_cure_poison,
     TAR_CHAR_DEFENSIVE,
     POS_FIGHTING,
     NULL,
     SLOT(43),
     5,
     12,
     FALSE,
     "",
     "!Cure Poison!",
     ""},

    {NORM,
     "purify",
     {NO_USE, NO_USE, NO_USE, NO_USE, 19,     NO_USE, NO_USE, NO_USE,
      NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE,
      NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE},
     spell_purify,
     TAR_CHAR_SELF,
     POS_FIGHTING,
     NULL,
     SLOT(231),
     5,
     12,
     FALSE,
     "Purify",
     "!Purify!",
     ""},

    {NORM,
     "cure serious",
     {NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE,
      NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE,
      NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE},
     spell_cure_serious,
     TAR_CHAR_DEFENSIVE,
     POS_FIGHTING,
     NULL,
     SLOT(61),
     15,
     12,
     TRUE,
     "",
     "!Cure Serious!",
     ""},

    {NORM,
     "curse",
     {35,     26,     NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE,
      NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE,
      NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE},
     spell_curse,
     TAR_CHAR_OFFENSIVE,
     POS_FIGHTING,
     &gsn_curse,
     SLOT(17),
     20,
     12,
     FALSE,
     "curse",
     "The curse wears off.",
     "$n starts to look more Holy."},

    {NORM,
     "detect evil",
     {12,     8,      NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE,
      NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE,
      NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE},
     spell_detect_evil,
     TAR_CHAR_SELF,
     POS_STANDING,
     NULL,
     SLOT(18),
     5,
     12,
     FALSE,
     "",
     "The red in your vision disappears.",
     ""},

    {NORM,
     "detect hidden",
     {17,     16,     NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE,
      NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE,
      NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE},
     spell_detect_hidden,
     TAR_CHAR_SELF,
     POS_STANDING,
     NULL,
     SLOT(44),
     5,
     12,
     FALSE,
     "",
     "You feel less aware of your suroundings.",
     ""},

    {NORM,
     "detect invis",
     {19,     NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE,
      NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE,
      NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE},
     spell_detect_invis,
     TAR_CHAR_SELF,
     POS_STANDING,
     NULL,
     SLOT(19),
     5,
     12,
     FALSE,
     "",
     "You no longer see invisible objects.",
     ""},

    {NORM,
     "detect magic",
     {7,      7,      NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE,
      NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE,
      NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE},
     spell_detect_magic,
     TAR_CHAR_SELF,
     POS_STANDING,
     NULL,
     SLOT(20),
     5,
     12,
     FALSE,
     "",
     "The detect magic wears off.",
     ""},

    {NORM,
     "detect poison",
     {NO_USE, 10,     NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE,
      NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE,
      NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE},
     spell_detect_poison,
     TAR_OBJ_INV,
     POS_STANDING,
     NULL,
     SLOT(21),
     5,
     12,
     FALSE,
     "",
     "!Detect Poison!",
     ""},

    {NORM,
     "detect undead",
     {8,      NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE,
      NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE,
      NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE},
     spell_detect_undead,
     TAR_CHAR_SELF,
     POS_STANDING,
     NULL,
     SLOT(513),
     8,
     12,
     FALSE,
     "",
     "You no longer sense undead beings.",
     ""},

    {NORM,
     "detection",
     {NO_USE, NO_USE, NO_USE, NO_USE, 22,     NO_USE, NO_USE, NO_USE,
      NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE,
      NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE},
     spell_detection,
     TAR_IGNORE,
     POS_STANDING,
     NULL,
     SLOT(527),
     12,
     24,
     FALSE,
     "",
     "!Detection!",
     ""},

    {NORM,
     "dimension blade",
     {NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE,
      NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE,
      NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE},
     spell_dimension_blade,
     TAR_OBJ_INV,
     POS_STANDING,
     NULL,
     SLOT(523),
     100,
     41,
     FALSE,
     "",
     "!Dimension Blade!",
     ""},

    {NORM,
     "dispel evil",
     {NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE,
      NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE,
      NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE}, /* was 82, 63, ... */
     spell_dispel_evil,
     TAR_CHAR_OFFENSIVE,
     POS_FIGHTING,
     NULL,
     SLOT(22),
     15,
     12,
     FALSE,
     "dispel evil",
     "!Dispel Evil!",
     ""},

    {NORM,
     "dispel object",
     {60,     70,     NO_USE, NO_USE, 80,     NO_USE, NO_USE, NO_USE,
      NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE,
      NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE},
     spell_dispel_object,
     TAR_IGNORE,
     POS_FIGHTING,
     NULL,
     SLOT(0),
     15,
     12,
     FALSE,
     "",
     "!Dispel Object!",
     ""},

    {NORM,
     "dispel magic",
     {68,     89,     NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE,
      NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE,
      NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE},
     spell_dispel_magic,
     TAR_IGNORE,
     POS_FIGHTING,
     NULL,
     SLOT(59),
     15,
     12,
     TRUE,
     "",
     "!Dispel Magic!",
     ""},

    {NORM,
     "purge",
     {NO_USE, NO_USE, NO_USE, NO_USE, 50,     NO_USE, NO_USE, NO_USE,
      NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE,
      NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE},
     spell_dispel_magic,
     TAR_CHAR_NOTSELF,
     POS_FIGHTING,
     NULL,
     SLOT(0),
     15,
     12,
     TRUE,
     "",
     "!Purge!",
     ""},

    {NORM,
     "earthquake",
     {NO_USE, 78,     NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE,
      NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE,
      NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE},
     spell_earthquake,
     TAR_IGNORE,
     POS_FIGHTING,
     NULL,
     SLOT(23),
     15,
     12,
     TRUE,
     "earthquake",
     "!Earthquake!",
     ""},

    {NORM,
     "ego whip",
     {NO_USE, NO_USE, NO_USE, NO_USE, 25,     NO_USE, NO_USE, NO_USE,
      NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE,
      NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE},
     spell_ego_whip,
     TAR_CHAR_OFFENSIVE,
     POS_FIGHTING,
     NULL,
     SLOT(535),
     35,
     24,
     TRUE,
     "ego whip",
     "!Ego Whip!",
     ""},

    {NORM,
     "enchant weapon",
     {39,     NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE,
      NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE,
      NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE},
     spell_enchant_weapon,
     TAR_OBJ_INV,
     POS_STANDING,
     NULL,
     SLOT(24),
     100,
     24,
     FALSE,
     "",
     "!Enchant Weapon!",
     ""},

    {NORM,
     "energy drain",
     {15,     7,      8,      11,     9,      13,     NO_USE, NO_USE,
      NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE,
      NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE},
     spell_energy_drain,
     TAR_CHAR_OFFENSIVE,
     POS_FIGHTING,
     NULL,
     SLOT(25),
     12,
     12,
     TRUE,
     "energy drain",
     "!Energy Drain!",
     ""},

    {NORM,
     "enhance weapon",
     {NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE,
      NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE,
      NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE},
     spell_enhance_weapon,
     TAR_OBJ_INV,
     POS_STANDING,
     NULL,
     SLOT(517),
     50,
     24,
     FALSE,
     "",
     "!Enhance Weapon!",
     ""},

    {NORM,
     "faerie fire",
     {3,      NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE,
      NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE,
      NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE},
     spell_faerie_fire,
     TAR_CHAR_DEFENSIVE,
     POS_FIGHTING,
     NULL,
     SLOT(72),
     5,
     12,
     TRUE,
     "faerie fire",
     "The pink aura around you fades away.",
     "The pink aura around $n fades away."},

    {NORM,
     "faerie fog",
     {NO_USE, 14,     NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE,
      NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE,
      NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE},
     spell_faerie_fog,
     TAR_IGNORE,
     POS_STANDING,
     NULL,
     SLOT(73),
     12,
     12,
     FALSE,
     "faerie fog",
     "!Faerie Fog!",
     ""},

    {NORM,
     "fighting trance",
     {NO_USE, NO_USE, NO_USE, NO_USE, 60,     NO_USE, NO_USE, NO_USE,
      NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE,
      NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE},
     spell_fighting_trance,
     TAR_CHAR_SELF,
     POS_STANDING,
     NULL,
     SLOT(521),
     60,
     24,
     FALSE,
     "",
     "Your fighting trance fades.",
     "$n's fighting trance fades."},

    {NORM,
     "fireball",
     {28,     NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE,
      NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE,
      NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE},
     spell_fireball,
     TAR_CHAR_OFFENSIVE,
     POS_FIGHTING,
     NULL,
     SLOT(26),
     15,
     12,
     TRUE,
     "fireball",
     "!Fireball!",
     ""},

    {NORM,
     "flamestrike",
     {NO_USE, 54,     NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE,
      NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE,
      NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE},
     spell_flamestrike,
     TAR_CHAR_OFFENSIVE,
     POS_FIGHTING,
     NULL,
     SLOT(65),
     20,
     12,
     TRUE,
     "flamestrike",
     "!Flamestrike!",
     ""},

    {NORM,
     "flare",
     {NO_USE, 20,     NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE,
      NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE,
      NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE},
     spell_flare,
     TAR_CHAR_OFFENSIVE,
     POS_FIGHTING,
     NULL,
     SLOT(591),
     18,
     12,
     TRUE,
     "flare",
     "Your vision returns.",
     "$n blinks, and starts to see again."},

    {NORM,
     "fly",
     {24,     NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE,
      NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE,
      NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE},
     spell_fly,
     TAR_CHAR_DEFENSIVE,
     POS_STANDING,
     NULL,
     SLOT(56),
     10,
     18,
     FALSE,
     "",
     "You slowly float to the ground.",
     "$n slowly floats to the ground."},

    {NORM,
     "gate",
     {NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE,
      NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE,
      NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE},
     spell_gate,
     TAR_CHAR_DEFENSIVE,
     POS_FIGHTING,
     NULL,
     SLOT(83),
     50,
     12,
     FALSE,
     "",
     "!Gate!",
     ""},

    {NORM,
     "giant strength",
     {NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, 18,     NO_USE,
      NO_USE, NO_USE, NO_USE, NO_USE, 18,     NO_USE, NO_USE, NO_USE,
      NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE},
     spell_giant_strength,
     TAR_CHAR_DEFENSIVE,
     POS_STANDING,
     NULL,
     SLOT(39),
     20,
     12,
     FALSE,
     "",
     "You feel weaker.",
     "$n looks weaker."},

    {NORM,
     "harm",
     {NO_USE, 74,     NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE,
      NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE,
      NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE},
     spell_harm,
     TAR_CHAR_OFFENSIVE,
     POS_FIGHTING,
     NULL,
     SLOT(27),
     35,
     12,
     TRUE,
     "harm spell",
     "!Harm!",
     ""},

    {NORM,
     "heal",
     {NO_USE, 5,      NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE,
      NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE,
      NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE},
     spell_heal,
     TAR_CHAR_DEFENSIVE,
     POS_FIGHTING,
     NULL,
     SLOT(28),
     50,
     12,
     TRUE,
     "",
     "!Heal!",
     ""},

    {NORM,
     "group heal",
     {NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, 5,
      NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, 25,     NO_USE, NO_USE,
      NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE},
     spell_group_heal,
     TAR_CHAR_DEFENSIVE,
     POS_FIGHTING,
     NULL,
     SLOT(169),
     50,
     12,
     TRUE,
     "",
     "!Group Heal!",
     ""},

    {NORM,
     "hypnosis",
     {NO_USE, NO_USE, NO_USE, NO_USE, 14,     NO_USE, NO_USE, NO_USE,
      NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE,
      NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE},
     spell_hypnosis,
     TAR_CHAR_OFFENSIVE,
     POS_STANDING,
     NULL,
     SLOT(532),
     30,
     24,
     FALSE,
     "",
     "!Hypnosis!",
     ""},

    {NORM,
     "identify",
     {9,      NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE,
      NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE,
      NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE},
     spell_identify,
     TAR_OBJ_INV,
     POS_STANDING,
     NULL,
     SLOT(53),
     12,
     24,
     FALSE,
     "",
     "!Identify!",
     ""},

    {NORM,
     "infravision",
     {20,     NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE,
      NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE,
      NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE},
     spell_infravision,
     TAR_CHAR_DEFENSIVE,
     POS_STANDING,
     NULL,
     SLOT(77),
     5,
     18,
     FALSE,
     "",
     "You no longer see in the dark.",
     ""},

    {NORM,
     "influx",
     {NO_USE, 65,     NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE,
      NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE,
      NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE},
     spell_influx,
     TAR_CHAR_DEFENSIVE,
     POS_FIGHTING,
     NULL,
     SLOT(503),
     75,
     24,
     TRUE,
     "",
     "!Influx!",
     ""},

    {NORM,
     "invis",
     {17,     NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE,
      NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE,
      NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE},
     spell_invis,
     TAR_IGNORE,
     POS_STANDING,
     &gsn_invis,
     SLOT(29),
     5,
     12,
     FALSE,
     "",
     "You are no longer invisible.",
     "$n's invisibilty fades."},

    {NORM,
     "know alignment",
     {13,     22,     NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE,
      NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE,
      NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE},
     spell_know_alignment,
     TAR_CHAR_DEFENSIVE,
     POS_FIGHTING,
     NULL,
     SLOT(58),
     9,
     12,
     FALSE,
     "",
     "!Know Alignment!",
     ""},

    {NORM,
     "know weakness",
     {NO_USE, NO_USE, NO_USE, NO_USE, 18,     NO_USE, NO_USE, NO_USE,
      NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE,
      NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE},
     spell_know_weakness,
     TAR_CHAR_SELF,
     POS_STANDING,
     NULL,
     SLOT(530),
     15,
     12,
     FALSE,
     "",
     "You are less aware of your enemy's weaknesses.",
     ""},

    {NORM,
     "know critical",
     {NO_USE, NO_USE, NO_USE, NO_USE, 28,     NO_USE, NO_USE, NO_USE,
      NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE,
      NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE},
     spell_know_weakness,
     TAR_CHAR_SELF,
     POS_STANDING,
     NULL,
     SLOT(530),
     15,
     12,
     FALSE,
     "",
     "You are less aware of critical damage points.",
     ""},

    {NORM,
     "know item",
     {NO_USE, NO_USE, NO_USE, NO_USE, 9,      NO_USE, NO_USE, NO_USE,
      NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE,
      NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE},
     spell_identify,
     TAR_OBJ_INV,
     POS_STANDING,
     NULL,
     SLOT(533),
     20,
     24,
     FALSE,
     "",
     "!Know Item!",
     ""},

    {NORM,
     "laser bolt",
     {NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE,
      NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE,
      NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE},
     spell_laserbolt,
     TAR_CHAR_OFFENSIVE,
     POS_FIGHTING,
     NULL,
     SLOT(511),
     35,
     12,
     FALSE,
     "laserbolt",
     "!laserbolt!",
     ""},

    {NORM,
     "lightning bolt",
     {24,     NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE,
      NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE,
      NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE},
     spell_lightning_bolt,
     TAR_CHAR_OFFENSIVE,
     POS_FIGHTING,
     NULL,
     SLOT(30),
     15,
     12,
     TRUE,
     "lightning bolt",
     "!Lightning Bolt!",
     ""},

    {NORM,
     "locate object",
     {16,     30,     NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE,
      NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE,
      NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE},
     spell_locate_object,
     TAR_IGNORE,
     POS_STANDING,
     NULL,
     SLOT(31),
     20,
     18,
     FALSE,
     "",
     "!Locate Object!",
     ""},

    {NORM,
     "magic missile",
     {3,      NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE,
      NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE,
      NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE},
     spell_magic_missile,
     TAR_CHAR_OFFENSIVE,
     POS_FIGHTING,
     NULL,
     SLOT(32),
     15,
     12,
     TRUE,
     "magic missile",
     "!Magic Missile!",
     ""},

    {NORM,
     "mass invis",
     {60,     NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE,
      NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE,
      NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE},
     spell_mass_invis,
     TAR_IGNORE,
     POS_STANDING,
     &gsn_mass_invis,
     SLOT(69),
     20,
     24,
     FALSE,
     "",
     "!Mass Invis!",
     ""},

    {NORM,
     "mind flail",
     {NO_USE, NO_USE, NO_USE, NO_USE, 4,      NO_USE, NO_USE, NO_USE,
      NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE,
      NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE},
     spell_mind_flail,
     TAR_CHAR_OFFENSIVE,
     POS_FIGHTING,
     NULL,
     SLOT(536),
     12,
     24,
     TRUE,
     "mind flail",
     "!Mind Flail!",
     ""},

    {NORM,
     "mystic armour",
     {10,     NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE,
      NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE,
      NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE},
     spell_mystic_armor,
     TAR_CHAR_DEFENSIVE,
     POS_STANDING,
     NULL,
     SLOT(590),
     18,
     24,
     FALSE,
     ""
     "Your Mystic Armour fades away",
     "The Mystic Armour around someone in the room fades away."},

    {NORM,
     "nerve fire",
     {NO_USE, NO_USE, NO_USE, NO_USE, 60,     NO_USE, NO_USE, NO_USE,
      NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE,
      NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE},
     spell_nerve_fire,
     TAR_IGNORE,
     POS_FIGHTING,
     NULL,
     SLOT(520),
     50,
     24,
     TRUE,
     "nerve fire",
     "!Nerve Fire!",
     ""},

    {NORM,
     "night vision",
     {NO_USE, NO_USE, NO_USE, NO_USE, 19,     NO_USE, NO_USE, NO_USE,
      NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE,
      NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE},
     spell_night_vision,
     TAR_CHAR_SELF,
     POS_STANDING,
     NULL,
     SLOT(538),
     17,
     24,
     FALSE,
     "",
     "Your eyes feel weaker.",
     ""},

    {NORM,
     "pass door",
     {46,     NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE,
      NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE,
      NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE},
     spell_pass_door,
     TAR_CHAR_SELF,
     POS_STANDING,
     NULL,
     SLOT(74),
     20,
     12,
     FALSE,
     "",
     "You feel solid again.",
     "$n's body becomes more solid."},

    {NORM,
     "phase",
     {NO_USE, NO_USE, NO_USE, NO_USE, 45,     NO_USE, NO_USE, NO_USE,
      NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE,
      NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE},
     spell_phase,
     TAR_CHAR_SELF,
     POS_STANDING,
     NULL,
     SLOT(522),
     20,
     12,
     FALSE,
     "",
     "You feel solid again.",
     "$n's body becomes more solid."},

    {NORM,
     "psychic crush",
     {NO_USE, NO_USE, NO_USE, NO_USE, 19,     NO_USE, NO_USE, NO_USE,
      NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE,
      NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE},
     spell_physic_thrust,
     TAR_CHAR_OFFENSIVE,
     POS_FIGHTING,
     NULL,
     SLOT(537),
     33,
     24,
     TRUE,
     "psychic crush",
     "!Psychic Crush!",
     ""},

    {NORM,
     "psychic thrust",
     {NO_USE, NO_USE, NO_USE, NO_USE, 7,      NO_USE, NO_USE, NO_USE,
      NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE,
      NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE},
     spell_physic_thrust,
     TAR_CHAR_OFFENSIVE,
     POS_FIGHTING,
     NULL,
     SLOT(537),
     22,
     24,
     TRUE,
     "psychic thrust",
     "!Physic Thrust!",
     ""},

    {NORM,
     "poison",
     {NO_USE, 31,     NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE,
      NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE,
      NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE},
     spell_poison,
     TAR_CHAR_OFFENSIVE,
     POS_STANDING,
     &gsn_poison,
     SLOT(33),
     10,
     12,
     FALSE,
     "poison",
     "You feel less sick.",
     "$n looks less sick."},

    {NORM,
     "produce food",
     {NO_USE, NO_USE, NO_USE, NO_USE, 24,     NO_USE, NO_USE, NO_USE,
      NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE,
      NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE},
     spell_produce_food,
     TAR_IGNORE,
     POS_STANDING,
     NULL,
     SLOT(524),
     16,
     24,
     FALSE,
     "",
     "!Produce Food!",
     ""},

    {NORM,
     "protection",
     {9,      12,     NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE,
      NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE,
      NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE},
     spell_protection,
     TAR_CHAR_SELF,
     POS_STANDING,
     NULL,
     SLOT(34),
     5,
     12,
     FALSE,
     "",
     "You feel less protected.",
     ""},

    {NORM,
     "psionic recovery",
     {NO_USE, NO_USE, NO_USE, NO_USE, 5,      NO_USE, NO_USE, NO_USE,
      NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE,
      NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE},
     spell_psionic_recovery,
     TAR_CHAR_SELF,
     POS_FIGHTING,
     NULL,
     SLOT(78),
     5,
     12,
     TRUE,
     "",
     "You feel less protected.",
     ""},

    {NORM,
     "refresh",
     {NO_USE, 11,     NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE,
      NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE,
      NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE},
     spell_refresh,
     TAR_CHAR_DEFENSIVE,
     POS_STANDING,
     NULL,
     SLOT(81),
     12,
     18,
     FALSE,
     "refresh",
     "!Refresh!",
     ""},

    {NORM,
     "refresh mana",
     {NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE,
      NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE,
      NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE},
     spell_refresh_mana,
     TAR_CHAR_DEFENSIVE,
     POS_STANDING,
     NULL,
     SLOT(81),
     12,
     18,
     FALSE,
     "refresh mana",
     "!Refresh mana!",
     ""},

    {NORM,
     "regen",
     {5,      NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE,
      NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE,
      NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE},
     spell_regen,
     TAR_CHAR_DEFENSIVE,
     POS_FIGHTING,
     NULL,
     SLOT(271),
     12,
     18,
     TRUE,
     "",
     "You are no longer regenerating quickly.",
     "$n is no longer regenerating quickly."},

    {NORM,
     "haste",
     {NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE,
      NO_USE, NO_USE, NO_USE, NO_USE, 84,     NO_USE, NO_USE, NO_USE,
      NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE},
     spell_haste,
     TAR_CHAR_DEFENSIVE,
     POS_FIGHTING,
     NULL,
     SLOT(271),
     12,
     18,
     TRUE,
     "",
     "You are no longer moving quickly.",
     "$n is no longer moving quickly."},

    {NORM,
     "overdrive",
     {NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE,
      NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE,
      57,     NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE},
     spell_overdrive,
     TAR_CHAR_SELF,
     POS_FIGHTING,
     NULL,
     SLOT(271),
     12,
     18,
     TRUE,
     "",
     "You are no longer acting quickly.",
     "$n is no longer acting quickly."},

    {NORM,
     "magical supremacy",
     {NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE,
      NO_USE, NO_USE, NO_USE, NO_USE, 42,     NO_USE, NO_USE, NO_USE,
      13,     NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE},
     spell_magical_supremacy,
     TAR_CHAR_SELF,
     POS_FIGHTING,
     NULL,
     SLOT(271),
     12,
     18,
     TRUE,
     "",
     "You no longer have magical supremacy.",
     "$n no longer has magical supremacy."},

    {NORM,
     "slow",
     {NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE,
      NO_USE, NO_USE, NO_USE, NO_USE, 92,     NO_USE, NO_USE, NO_USE,
      NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE},
     spell_slow,
     TAR_CHAR_OFFENSIVE,
     POS_FIGHTING,
     NULL,
     SLOT(271),
     12,
     18,
     TRUE,
     "",
     "You are no longer acting slowly.",
     "$n is no longer acting slowly."},

    {NORM,
     "feeble mind",
     {NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE,
      NO_USE, NO_USE, 45,     NO_USE, NO_USE, NO_USE, NO_USE, NO_USE,
      NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE},
     spell_feeble_mind,
     TAR_CHAR_OFFENSIVE,
     POS_FIGHTING,
     NULL,
     SLOT(271),
     12,
     18,
     TRUE,
     "",
     "You are now thinking quickly.",
     "$n is now thinking quickly."},

    {NORM,
     "feeble body",
     {NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE,
      NO_USE, NO_USE, 45,     NO_USE, NO_USE, NO_USE, NO_USE, NO_USE,
      NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE},
     spell_feeble_body,
     TAR_CHAR_OFFENSIVE,
     POS_FIGHTING,
     NULL,
     SLOT(271),
     12,
     18,
     TRUE,
     "",
     "You are now moving quickly.",
     "$n is now moving quickly."},

    {NORM,
     "remove curse",
     {36,     27,     NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE,
      NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE,
      NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE},
     spell_remove_curse,
     TAR_CHAR_DEFENSIVE,
     POS_STANDING,
     NULL,
     SLOT(35),
     5,
     12,
     FALSE,
     "",
     "!Remove Curse!",
     ""},

    {NORM,
     "sanctuary",
     {NO_USE, 70,     NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE,
      NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE,
      NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE},
     spell_sanctuary,
     TAR_CHAR_DEFENSIVE,
     POS_STANDING,
     NULL,
     SLOT(36),
     75,
     12,
     FALSE,
     "",
     "The white aura around your body fades.",
     "The white aura around $n's body fades."},

    {NORM,
     "refuge",
     {NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, 32,
      NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, 32,     NO_USE, NO_USE,
      NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE},
     spell_refuge,
     TAR_CHAR_DEFENSIVE,
     POS_STANDING,
     NULL,
     SLOT(0),
     75,
     12,
     TRUE,
     "",
     "The rainbow aura around your body fades.",
     "The rainbow aura around $n's body fades."},

    {NORM,
     "seal room",
     {70,     50,     NO_USE, NO_USE, 50,     NO_USE, NO_USE, NO_USE,
      NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE,
      NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE},
     spell_seal_room,
     TAR_IGNORE,
     POS_STANDING,
     NULL,
     SLOT(541),
     75,
     12,
     FALSE,
     "",
     "The Energy web around this room fades.",
     ""},

    {NORM,
     "see magic",
     {NO_USE, NO_USE, NO_USE, NO_USE, 7,      NO_USE, NO_USE, NO_USE,
      NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE,
      NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE},
     spell_see_magic,
     TAR_CHAR_SELF,
     POS_STANDING,
     NULL,
     SLOT(526),
     8,
     12,
     FALSE,
     "",
     "You no longer see magical auras.",
     ""},

    {NORM,
     "sense evil",
     {NO_USE, NO_USE, NO_USE, NO_USE, 10,     NO_USE, NO_USE, NO_USE,
      NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE,
      NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE},
     spell_sense_evil,
     TAR_CHAR_SELF,
     POS_STANDING,
     NULL,
     SLOT(515),
     12,
     12,
     FALSE,
     "",
     "You no longer sense evil.",
     ""},

    {NORM,
     "shield",
     {9,      NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE,
      NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE,
      NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE},
     spell_shield,
     TAR_CHAR_DEFENSIVE,
     POS_STANDING,
     NULL,
     SLOT(67),
     12,
     18,
     FALSE,
     "",
     "Your force shield shimmers, then fades away.",
     "$n's force field shimmers, then fades away."},

    {NORM,
     "shocking grasp",
     {5,      NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE,
      NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE,
      NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE},
     spell_shocking_grasp,
     TAR_CHAR_OFFENSIVE,
     POS_FIGHTING,
     NULL,
     SLOT(82),
     15,
     12,
     TRUE,
     "shocking grasp",
     "!Shocking Grasp!",
     ""},

    {NORM,
     "sight",
     {30,     NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE,
      NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE,
      NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE},
     spell_cure_blindness,
     TAR_CHAR_DEFENSIVE,
     POS_STANDING,
     NULL,
     SLOT(592),
     20,
     24,
     FALSE,
     "",
     "!Sight!",
     ""},

    {NORM,
     "sleep",
     {9,      NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE,
      NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE,
      NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE},
     spell_sleep,
     TAR_CHAR_OFFENSIVE,
     POS_STANDING,
     &gsn_sleep,
     SLOT(38),
     15,
     12,
     FALSE,
     "",
     "You feel less tired.",
     "$n starts looking much more awake."},

    {NORM,
     "stalker",
     {NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE,
      NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE,
      NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE},
     spell_stalker,
     TAR_IGNORE,
     POS_STANDING,
     NULL,
     SLOT(401),
     100,
     24,
     FALSE,
     "",
     "!Stalker!",
     ""},

    {NORM,
     "stone skin",
     {36,     NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE,
      NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE,
      NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE},
     spell_stone_skin,
     TAR_CHAR_SELF,
     POS_STANDING,
     NULL,
     SLOT(66),
     12,
     18,
     TRUE,
     "",
     "Your skin feels soft again.",
     "$n's skin loses it's stone-like look."},

    {NORM,
     "suffocate",
     {NO_USE, NO_USE, NO_USE, NO_USE, 46,     NO_USE, NO_USE, NO_USE,
      NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE,
      NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE},
     spell_suffocate,
     TAR_CHAR_OFFENSIVE,
     POS_FIGHTING,
     NULL,
     SLOT(516),
     30,
     24,
     TRUE,
     "a choking hand",
     "!Suffocate!",
     ""},

    {NORM,
     "summon",
     {35,     NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE,
      NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE,
      NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE},
     spell_summon,
     TAR_IGNORE,
     POS_STANDING,
     NULL,
     SLOT(40),
     50,
     12,
     FALSE,
     "",
     "!Summon!",
     ""},

    {NORM,
     "teleport",
     {40,     NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE,
      NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE,
      NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE},
     spell_teleport,
     TAR_CHAR_SELF,
     POS_FIGHTING,
     NULL,
     SLOT(2),
     35,
     12,
     FALSE,
     "",
     "!Teleport!",
     ""},

    {NORM,
     "travel",
     {NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE,
      NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE,
      NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE},
     spell_travel,
     TAR_CHAR_SELF,
     POS_STANDING,
     NULL,
     SLOT(599),
     50,
     24,
     FALSE,
     "",
     "!Travel!",
     ""},

    {NORM,
     "ventriloquate",
     {3,      NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE,
      NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE,
      NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE},
     spell_ventriloquate,
     TAR_IGNORE,
     POS_STANDING,
     NULL,
     SLOT(41),
     5,
     12,
     FALSE,
     "",
     "!Ventriloquate!",
     ""},

    {NORM,
     "weaken",
     {NO_USE, 20,     NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE,
      NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE,
      NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE},
     spell_weaken,
     TAR_CHAR_OFFENSIVE,
     POS_FIGHTING,
     NULL,
     SLOT(68),
     20,
     12,
     FALSE,
     "spell",
     "You feel stronger.",
     "$n looks stronger."},

    {NORM,
     "beacon",
     {70,     NO_USE, NO_USE, NO_USE, 70,     NO_USE, NO_USE, NO_USE,
      NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE,
      NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE},
     spell_beacon,
     TAR_IGNORE,
     POS_STANDING,
     NULL,
     SLOT(399),
     25,
     12,
     FALSE,
     "",
     "!Beacon!",
     ""},

    {NORM,
     "portal",
     {80,     NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE,
      NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE,
      NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE},
     spell_portal,
     TAR_IGNORE,
     POS_FIGHTING,
     NULL,
     SLOT(334),
     100,
     12,
     FALSE,
     "",
     "!Portal!",
     ""},

    {NORM,
     "window",
     {70,     NO_USE, NO_USE, NO_USE, 70,     NO_USE, NO_USE, NO_USE,
      NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE,
      NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE},
     spell_window,
     TAR_IGNORE,
     POS_STANDING,
     NULL,
     SLOT(333),
     100,
     12,
     FALSE,
     "",
     "!Window!",
     ""},

    {NORM,
     "word of recall",
     {NO_USE, 66,     NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE,
      NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE,
      NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE},
     spell_word_of_recall,
     TAR_CHAR_SELF,
     POS_RESTING,
     NULL,
     SLOT(42),
     5,
     12,
     FALSE,
     "",
     "!Word of Recall!",
     ""},

    {NORM,
     "hellspawn",
     {43,     NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE,
      NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE,
      NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE},
     spell_hellspawn,
     TAR_CHAR_OFFENSIVE,
     POS_FIGHTING,
     NULL,
     SLOT(512),
     50,
     12,
     TRUE,
     "HellSpawn",
     "!Hellspawn!",
     ""},

    {NORM,
     "planergy",
     {NO_USE, NO_USE, NO_USE, NO_USE, 5,      NO_USE, NO_USE, NO_USE,
      NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE,
      NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE},
     spell_planergy,
     TAR_CHAR_OFFENSIVE,
     POS_FIGHTING,
     NULL,
     SLOT(504),
     25,
     24,
     TRUE,
     "energy",
     "!planergy!",
     ""},

    {NORM,
     "visit",
     {NO_USE, NO_USE, NO_USE, NO_USE, 32,     NO_USE, NO_USE, NO_USE,
      NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE,
      NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE},
     spell_visit,
     TAR_IGNORE,
     POS_STANDING,
     NULL,
     SLOT(505),
     50,
     48,
     FALSE,
     "",
     "!visit!",
     ""},

    {NORM,
     "barrier",
     {NO_USE, NO_USE, NO_USE, NO_USE, 8,      NO_USE, NO_USE, NO_USE,
      NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE,
      NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE},
     spell_barrier,
     TAR_CHAR_SELF,
     POS_STANDING,
     NULL,
     SLOT(506),
     30,
     24,
     FALSE,
     "",
     "Your barrier slowly fades.",
     "The barrier around $n fades."},

    {NORM,
     "phobia",
     {NO_USE, NO_USE, NO_USE, NO_USE, 10,     NO_USE, NO_USE, NO_USE,
      NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE,
      NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE},
     spell_phobia,
     TAR_CHAR_OFFENSIVE,
     POS_FIGHTING,
     NULL,
     SLOT(507),
     32,
     24,
     FALSE,
     "phobia attack",
     "!phobia!",
     ""},

    {NORM,
     "mind bolt",
     {NO_USE, NO_USE, NO_USE, NO_USE, 12,     NO_USE, NO_USE, NO_USE,
      NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE,
      NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE},
     spell_mind_bolt,
     TAR_CHAR_OFFENSIVE,
     POS_FIGHTING,
     NULL,
     SLOT(519),
     40,
     12,
     TRUE,
     "Mind Bolt",
     "!MindBolt!",
     ""},

    {NORM,
     "mindflame",
     {NO_USE, NO_USE, NO_USE, NO_USE, 35,     NO_USE, NO_USE, NO_USE,
      NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE,
      NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE},
     spell_mindflame,
     TAR_IGNORE,
     POS_FIGHTING,
     NULL,
     SLOT(508),
     40,
     24,
     TRUE,
     "Mind Flame",
     "!mindflame!",
     ""},

    {NORM,
     "chain lightning",
     {65,     NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE,
      NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE,
      NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE},
     spell_chain_lightning,
     TAR_IGNORE,
     POS_FIGHTING,
     NULL,
     SLOT(509),
     25,
     24,
     TRUE,
     "lightening bolt",
     "!chain-light!",
     ""},

    {NORM,
     "static",
     {NO_USE, NO_USE, NO_USE, NO_USE, 20,     NO_USE, NO_USE, NO_USE,
      NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE,
      NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE},
     spell_static,
     TAR_CHAR_OFFENSIVE,
     POS_FIGHTING,
     NULL,
     SLOT(510),
     40,
     24,
     TRUE,
     "discharge",
     "!static!",
     ""},

    {NORM,
     "cloak:absorption",
     {NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE,
      NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE,
      NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE},
     spell_cloak_absorb,
     TAR_CHAR_DEFENSIVE,
     POS_STANDING,
     NULL,
     SLOT(221),
     500,
     12,
     FALSE,
     "",
     "@@NThe @@lcloak@@N around your body fades.",
     "@@NThe @@lcloak@@N around $n's body fades."},

    {NORM,
     "cloak:reflection",
     {NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE,
      NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE,
      NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE},
     spell_cloak_reflect,
     TAR_CHAR_DEFENSIVE,
     POS_STANDING,
     NULL,
     SLOT(222),
     500,
     12,
     FALSE,
     "",
     "@@NThe @@lc@@el@@ro@@ya@@ak@@N around your body fades.",
     "@@NThe @@lc@@el@@ro@@ya@@ak@@N around $n's body fades."},

    {NORM,
     "cloak:flaming",
     {NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, 48,     NO_USE,
      NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE,
      NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE},
     spell_cloak_flaming,
     TAR_CHAR_DEFENSIVE,
     POS_STANDING,
     NULL,
     SLOT(223),
     750,
     12,
     FALSE,
     "",
     "@@NThe @@ecloak@@N around your body fades.",
     "@@NThe @@ecloak@@N around $n's body fades."},

    {NORM,
     "cloak:elements",
     {NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE,
      NO_USE, NO_USE, NO_USE, NO_USE, 48,     NO_USE, NO_USE, NO_USE,
      NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE},
     spell_cloak_elements,
     TAR_CHAR_DEFENSIVE,
     POS_STANDING,
     NULL,
     SLOT(225),
     750,
     12,
     FALSE,
     "",
     "@@NThe @@lcloak@@N around your body fades.",
     "@@NThe @@lcloak@@N around $n's body fades."},

    {NORM,
     "cloak:adept",
     {NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE,
      NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE,
      NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE},
     spell_cloak_adept,
     TAR_CHAR_DEFENSIVE,
     POS_STANDING,
     NULL,
     SLOT(226),
     500,
     12,
     FALSE,
     "",
     "@@NThe @@Wcloak@@N around your body fades.",
     "@@NThe @@Wcloak@@N around $n's body fades."},

    {NORM,
     "acid breath",
     {NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE,
      NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE,
      NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE},
     spell_acid_breath,
     TAR_CHAR_OFFENSIVE,
     POS_FIGHTING,
     NULL,
     SLOT(200),
     0,
     4,
     FALSE,
     "blast of acid",
     "!Acid Breath!",
     ""},

    {NORM,
     "fire breath",
     {NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE,
      NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE,
      NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE},
     spell_fire_breath,
     TAR_CHAR_OFFENSIVE,
     POS_FIGHTING,
     NULL,
     SLOT(201),
     0,
     4,
     FALSE,
     "blast of flame",
     "!Fire Breath!",
     ""},

    {NORM,
     "frost breath",
     {NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE,
      NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE,
      NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE},
     spell_frost_breath,
     TAR_CHAR_OFFENSIVE,
     POS_FIGHTING,
     NULL,
     SLOT(202),
     0,
     4,
     FALSE,
     "blast of frost",
     "!Frost Breath!",
     ""},

    {NORM,
     "gas breath",
     {NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE,
      NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE,
      NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE},
     spell_gas_breath,
     TAR_IGNORE,
     POS_FIGHTING,
     NULL,
     SLOT(203),
     0,
     4,
     FALSE,
     "blast of gas",
     "!Gas Breath!",
     ""},

    {NORM,
     "lightning breath",
     {NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE,
      NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE,
      NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE},
     spell_lightning_breath,
     TAR_CHAR_OFFENSIVE,
     POS_FIGHTING,
     NULL,
     SLOT(204),
     0,
     4,
     FALSE,
     "blast of lightning",
     "!Lightning Breath!",
     ""},
