
/*
 * Magic spells.
 */

{NORM, "reserved", {LEVELS_INIT}, 0, TAR_IGNORE, POS_STANDING, NULL, SLOT(0), 0, 0, FALSE, "",
 "",   ""},

    {NORM,
     "dissolution",
     {LEVELS_INIT, L(CLASS_MAG, 50)},
     spell_acid_blast,
     TAR_CHAR_OFFENSIVE,
     POS_FIGHTING,
     NULL,
     SLOT(70),
     20,
     12,
     TRUE,
     "dissolution",
     "!Dissolution!",
     ""},

    {NORM,
     "armor",
     {LEVELS_INIT, L(CLASS_MAG, 3)},
     spell_armor,
     TAR_CHAR_DEFENSIVE,
     POS_STANDING,
     NULL,
     SLOT(1),
     5,
     12,
     FALSE,
     "",
     "You feel less protected.",
     ""},

    {NORM,
     "animate",
     {LEVELS_INIT},
     spell_animate,
     TAR_IGNORE,
     POS_STANDING,
     NULL,
     SLOT(525),
     50,
     24,
     FALSE,
     "",
     "!Animate!",
     ""},

    {NORM,
     "revenant",
     {LEVELS_INIT, L(CLASS_NEC, 70)},
     spell_revenant,
     TAR_IGNORE,
     POS_STANDING,
     NULL,
     SLOT(755),
     75,
     24,
     FALSE,
     "",
     "!Revenant!",
     ""},

    {NORM,
     "bad breath",
     {LEVELS_INIT},
     spell_badbreath,
     TAR_CHAR_OFFENSIVE,
     POS_FIGHTING,
     NULL,
     SLOT(502),
     10,
     12,
     TRUE,
     "bad breath",
     "!Bad Breath!",
     ""},

    {NORM,
     "bark skin",
     {LEVELS_INIT},
     spell_bark_skin,
     TAR_CHAR_SELF,
     POS_STANDING,
     NULL,
     SLOT(514),
     20,
     24,
     FALSE,
     "",
     "Your skin feels softer.",
     "$n's skin looks less wooden."},

    {NORM,
     "bless",
     {LEVELS_INIT, L(CLASS_CLE, 8)},
     spell_bless,
     TAR_CHAR_DEFENSIVE,
     POS_STANDING,
     NULL,
     SLOT(3),
     5,
     12,
     FALSE,
     "",
     "You feel less righteous.",
     "$n looks less Holy."},

    {NORM,
     "blindness",
     {LEVELS_INIT, L(CLASS_MAG, 16)},
     spell_blindness,
     TAR_CHAR_OFFENSIVE,
     POS_FIGHTING,
     &gsn_blindness,
     SLOT(4),
     5,
     12,
     TRUE,
     "",
     "You can see again.",
     "$n's vision returns."},

    {NORM,
     "bloody tears",
     {LEVELS_INIT, L(CLASS_PSI, 26)},
     spell_bloody_tears,
     TAR_CHAR_OFFENSIVE,
     POS_FIGHTING,
     NULL,
     SLOT(518),
     12,
     12,
     TRUE,
     "Bloody Tears",
     "!Bloody Tears!",
     ""},

    {NORM,
     "burning hands",
     {LEVELS_INIT, L(CLASS_MAG, 6)},
     spell_burning_hands,
     TAR_CHAR_OFFENSIVE,
     POS_FIGHTING,
     NULL,
     SLOT(5),
     15,
     12,
     TRUE,
     "burning hands",
     "!Burning Hands!",
     ""},

    {NORM,
     "shard ward",
     {LEVELS_INIT, L(CLASS_CLE, 36)},
     spell_shard_ward,
     TAR_IGNORE,
     POS_FIGHTING,
     NULL,
     SLOT(6),
     15,
     12,
     TRUE,
     "shard ward",
     "!Shard Ward!",
     ""},

    {NORM,       "calm",     {LEVELS_INIT, L(CLASS_PSI, 52)},
     spell_calm, TAR_IGNORE, POS_FIGHTING,
     NULL,       SLOT(531),  30,
     24,         FALSE,      "",
     "!Calm!",   ""},

    {NORM,
     "tribunal's hand",
     {LEVELS_INIT, L(CLASS_CLE, 58)},
     spell_cause_critical,
     TAR_CHAR_OFFENSIVE,
     POS_FIGHTING,
     NULL,
     SLOT(63),
     20,
     12,
     TRUE,
     "tribunal's hand",
     "!Tribunal's Hand!",
     ""},

    {NORM,
     "cause light",
     {LEVELS_INIT},
     spell_cause_light,
     TAR_CHAR_OFFENSIVE,
     POS_FIGHTING,
     NULL,
     SLOT(62),
     15,
     12,
     TRUE,
     "spell",
     "!Cause Light!",
     ""},

    {NORM,
     "solar censure",
     {LEVELS_INIT, L(CLASS_CLE, 40)},
     spell_cause_serious,
     TAR_CHAR_OFFENSIVE,
     POS_FIGHTING,
     NULL,
     SLOT(64),
     17,
     12,
     TRUE,
     "solar censure",
     "!Solar Censure!",
     ""},

    {NORM,
     "change sex",
     {LEVELS_INIT},
     spell_change_sex,
     TAR_CHAR_DEFENSIVE,
     POS_FIGHTING,
     NULL,
     SLOT(82),
     15,
     12,
     FALSE,
     "",
     "Your body feels familiar again.",
     "$n looks $mself again."},

    {NORM,
     "charm person",
     {LEVELS_INIT},
     spell_charm_person,
     TAR_CHAR_OFFENSIVE,
     POS_STANDING,
     &gsn_charm_person,
     SLOT(7),
     5,
     12,
     FALSE,
     "",
     "You feel more self-confident.",
     "The glazed look in $n's eyes fades."},

    {NORM,
     "chill touch",
     {LEVELS_INIT, L(CLASS_MAG, 8)},
     spell_chill_touch,
     TAR_CHAR_OFFENSIVE,
     POS_FIGHTING,
     NULL,
     SLOT(8),
     15,
     12,
     TRUE,
     "chilling touch",
     "You feel less cold.",
     ""},

    {NORM,
     "crystal burst",
     {LEVELS_INIT, L(CLASS_MAG, 7)},
     spell_crystal_burst,
     TAR_CHAR_OFFENSIVE,
     POS_FIGHTING,
     NULL,
     SLOT(10),
     15,
     12,
     TRUE,
     "crystal burst",
     "!Crystal Burst!",
     ""},

    {NORM,
     "continual light",
     {LEVELS_INIT, L(CLASS_MAG, 11), L(CLASS_CLE, 27)},
     spell_continual_light,
     TAR_IGNORE,
     POS_STANDING,
     NULL,
     SLOT(57),
     7,
     12,
     FALSE,
     "",
     "!Continual Light!",
     ""},

    {NORM,
     "seal calculus",
     {LEVELS_INIT, L(CLASS_CLE, 79)},
     spell_seal_calculus,
     TAR_IGNORE,
     POS_STANDING,
     NULL,
     SLOT(11),
     25,
     12,
     FALSE,
     "",
     "!Seal Calculus!",
     ""},

    {NORM,
     "cure blindness",
     {LEVELS_INIT, L(CLASS_CLE, 28)},
     spell_cure_blindness,
     TAR_CHAR_DEFENSIVE,
     POS_FIGHTING,
     NULL,
     SLOT(14),
     5,
     12,
     FALSE,
     "",
     "!Cure Blindness!",
     ""},

    {NORM,
     "cure critical",
     {LEVELS_INIT},
     spell_cure_critical,
     TAR_CHAR_DEFENSIVE,
     POS_FIGHTING,
     NULL,
     SLOT(15),
     20,
     12,
     FALSE,
     "",
     "!Cure Critical!",
     ""},

    {NORM,
     "cure light",
     {LEVELS_INIT},
     spell_cure_light,
     TAR_CHAR_DEFENSIVE,
     POS_FIGHTING,
     NULL,
     SLOT(16),
     10,
     12,
     FALSE,
     "",
     "!Cure Light!",
     ""},

    {NORM,
     "cure poison",
     {LEVELS_INIT, L(CLASS_CLE, 32)},
     spell_cure_poison,
     TAR_CHAR_DEFENSIVE,
     POS_FIGHTING,
     NULL,
     SLOT(43),
     5,
     12,
     FALSE,
     "",
     "!Cure Poison!",
     ""},

    {NORM,
     "purify",
     {LEVELS_INIT, L(CLASS_PSI, 19)},
     spell_purify,
     TAR_CHAR_SELF,
     POS_FIGHTING,
     NULL,
     SLOT(231),
     5,
     12,
     FALSE,
     "Purify",
     "!Purify!",
     ""},

    {NORM,
     "cure serious",
     {LEVELS_INIT},
     spell_cure_serious,
     TAR_CHAR_DEFENSIVE,
     POS_FIGHTING,
     NULL,
     SLOT(61),
     15,
     12,
     TRUE,
     "",
     "!Cure Serious!",
     ""},

    {NORM,
     "curse",
     {LEVELS_INIT, L(CLASS_MAG, 35), L(CLASS_CLE, 26)},
     spell_curse,
     TAR_CHAR_OFFENSIVE,
     POS_FIGHTING,
     &gsn_curse,
     SLOT(17),
     20,
     12,
     FALSE,
     "curse",
     "The curse wears off.",
     "$n starts to look more Holy."},

    {NORM,
     "detect evil",
     {LEVELS_INIT, L(CLASS_MAG, 12), L(CLASS_CLE, 8)},
     spell_detect_evil,
     TAR_CHAR_SELF,
     POS_STANDING,
     NULL,
     SLOT(18),
     5,
     12,
     FALSE,
     "",
     "The red in your vision disappears.",
     ""},

    {NORM,
     "detect hidden",
     {LEVELS_INIT, L(CLASS_MAG, 17), L(CLASS_CLE, 16)},
     spell_detect_hidden,
     TAR_CHAR_SELF,
     POS_STANDING,
     NULL,
     SLOT(44),
     5,
     12,
     FALSE,
     "",
     "You feel less aware of your suroundings.",
     ""},

    {NORM,
     "detect invis",
     {LEVELS_INIT, L(CLASS_MAG, 19)},
     spell_detect_invis,
     TAR_CHAR_SELF,
     POS_STANDING,
     NULL,
     SLOT(19),
     5,
     12,
     FALSE,
     "",
     "You no longer see invisible objects.",
     ""},

    {NORM,
     "detect magic",
     {LEVELS_INIT, L(CLASS_MAG, 7), L(CLASS_CLE, 7)},
     spell_detect_magic,
     TAR_CHAR_SELF,
     POS_STANDING,
     NULL,
     SLOT(20),
     5,
     12,
     FALSE,
     "",
     "The detect magic wears off.",
     ""},

    {NORM,
     "detect poison",
     {LEVELS_INIT, L(CLASS_CLE, 10)},
     spell_detect_poison,
     TAR_OBJ_INV,
     POS_STANDING,
     NULL,
     SLOT(21),
     5,
     12,
     FALSE,
     "",
     "!Detect Poison!",
     ""},

    {NORM,
     "detect undead",
     {LEVELS_INIT, L(CLASS_MAG, 8)},
     spell_detect_undead,
     TAR_CHAR_SELF,
     POS_STANDING,
     NULL,
     SLOT(513),
     8,
     12,
     FALSE,
     "",
     "You no longer sense undead beings.",
     ""},

    {NORM,
     "detection",
     {LEVELS_INIT, L(CLASS_PSI, 22)},
     spell_detection,
     TAR_IGNORE,
     POS_STANDING,
     NULL,
     SLOT(527),
     12,
     24,
     FALSE,
     "",
     "!Detection!",
     ""},

    {NORM,
     "dimension blade",
     {LEVELS_INIT},
     spell_dimension_blade,
     TAR_OBJ_INV,
     POS_STANDING,
     NULL,
     SLOT(523),
     100,
     41,
     FALSE,
     "",
     "!Dimension Blade!",
     ""},

    {NORM,
     "dispel evil",
     {LEVELS_INIT}, /* was 82, 63, ... */
     spell_dispel_evil,
     TAR_CHAR_OFFENSIVE,
     POS_FIGHTING,
     NULL,
     SLOT(22),
     15,
     12,
     FALSE,
     "dispel evil",
     "!Dispel Evil!",
     ""},

    {NORM,
     "dispel object",
     {LEVELS_INIT, L(CLASS_MAG, 60), L(CLASS_CLE, 70), L(CLASS_PSI, 80)},
     spell_dispel_object,
     TAR_IGNORE,
     POS_FIGHTING,
     NULL,
     SLOT(0),
     15,
     12,
     FALSE,
     "",
     "!Dispel Object!",
     ""},

    {NORM,
     "dispel magic",
     {LEVELS_INIT, L(CLASS_MAG, 68), L(CLASS_CLE, 89)},
     spell_dispel_magic,
     TAR_IGNORE,
     POS_FIGHTING,
     NULL,
     SLOT(59),
     15,
     12,
     TRUE,
     "",
     "!Dispel Magic!",
     ""},

    {NORM,
     "cognitive flush",
     {LEVELS_INIT, L(CLASS_PSI, 50)},
     spell_dispel_magic,
     TAR_CHAR_NOTSELF,
     POS_FIGHTING,
     NULL,
     SLOT(0),
     15,
     12,
     TRUE,
     "",
     "!Cognitive Flush!",
     ""},

    {NORM,
     "jackal's verdict",
     {LEVELS_INIT, L(CLASS_CLE, 78)},
     spell_jackal_verdict,
     TAR_IGNORE,
     POS_FIGHTING,
     NULL,
     SLOT(23),
     15,
     12,
     TRUE,
     "jackal's verdict",
     "!Jackal's Verdict!",
     ""},

    {NORM,
     "ego whip",
     {LEVELS_INIT, L(CLASS_PSI, 25)},
     spell_ego_whip,
     TAR_CHAR_OFFENSIVE,
     POS_FIGHTING,
     NULL,
     SLOT(535),
     35,
     24,
     TRUE,
     "ego whip",
     "!Ego Whip!",
     ""},

    {NORM,
     "enchant weapon",
     {LEVELS_INIT, L(CLASS_MAG, 39)},
     spell_enchant_weapon,
     TAR_OBJ_INV,
     POS_STANDING,
     NULL,
     SLOT(24),
     100,
     24,
     FALSE,
     "",
     "!Enchant Weapon!",
     ""},

    {NORM,
     "energy drain",
     {LEVELS_INIT},
     spell_energy_drain,
     TAR_CHAR_OFFENSIVE,
     POS_FIGHTING,
     NULL,
     SLOT(25),
     12,
     12,
     TRUE,
     "energy drain",
     "!Energy Drain!",
     ""},

    {NORM,
     "enhance weapon",
     {LEVELS_INIT},
     spell_enhance_weapon,
     TAR_OBJ_INV,
     POS_STANDING,
     NULL,
     SLOT(517),
     50,
     24,
     FALSE,
     "",
     "!Enhance Weapon!",
     ""},

    {NORM,
     "prism mark",
     {LEVELS_INIT, L(CLASS_MAG, 3)},
     spell_prism_mark,
     TAR_CHAR_DEFENSIVE,
     POS_FIGHTING,
     NULL,
     SLOT(72),
     5,
     12,
     TRUE,
     "prism mark",
     "The crystal outline around you fractures and fades.",
     "The crystal outline around $n fractures and fades."},

    {NORM,
     "ledger mark",
     {LEVELS_INIT, L(CLASS_CLE, 14)},
     spell_ledger_mark,
     TAR_IGNORE,
     POS_STANDING,
     NULL,
     SLOT(73),
     12,
     12,
     FALSE,
     "ledger mark",
     "!Ledger Mark!",
     ""},

    {NORM,
     "assertion form",
     {LEVELS_INIT, L(CLASS_PSI, 60)},
     spell_fighting_trance,
     TAR_CHAR_SELF,
     POS_STANDING,
     NULL,
     SLOT(521),
     60,
     24,
     FALSE,
     "",
     "Your assertion form fades.",
     "$n's assertion form fades."},

    {NORM,
     "fireball",
     {LEVELS_INIT, L(CLASS_MAG, 28)},
     spell_fireball,
     TAR_CHAR_OFFENSIVE,
     POS_FIGHTING,
     NULL,
     SLOT(26),
     15,
     12,
     TRUE,
     "fireball",
     "!Fireball!",
     ""},

    {NORM,
     "flamestrike",
     {LEVELS_INIT, L(CLASS_CLE, 54)},
     spell_flamestrike,
     TAR_CHAR_OFFENSIVE,
     POS_FIGHTING,
     NULL,
     SLOT(65),
     20,
     12,
     TRUE,
     "flamestrike",
     "!Flamestrike!",
     ""},

    {NORM,
     "flare",
     {LEVELS_INIT},
     spell_flare,
     TAR_CHAR_OFFENSIVE,
     POS_FIGHTING,
     NULL,
     SLOT(591),
     18,
     12,
     TRUE,
     "flare",
     "Your vision returns.",
     "$n blinks, and starts to see again."},

    {NORM,
     "fly",
     {LEVELS_INIT, L(CLASS_MAG, 24)},
     spell_fly,
     TAR_CHAR_DEFENSIVE,
     POS_STANDING,
     NULL,
     SLOT(56),
     10,
     18,
     FALSE,
     "",
     "You slowly float to the ground.",
     "$n slowly floats to the ground."},

    {NORM,         "gate", {LEVELS_INIT}, spell_gate, TAR_CHAR_DEFENSIVE,
     POS_FIGHTING, NULL,   SLOT(83),      50,         12,
     FALSE,        "",     "!Gate!",      ""},

    {NORM,
     "giant strength",
     {LEVELS_INIT, L(CLASS_SOR, 18), L(CLASS_WIZ, 18)},
     spell_giant_strength,
     TAR_CHAR_DEFENSIVE,
     POS_STANDING,
     NULL,
     SLOT(39),
     20,
     12,
     FALSE,
     "",
     "You feel weaker.",
     "$n looks weaker."},

    {NORM,         "harm",       {LEVELS_INIT}, spell_harm, TAR_CHAR_OFFENSIVE,
     POS_FIGHTING, NULL,         SLOT(27),      35,         12,
     TRUE,         "harm spell", "!Harm!",      ""},

    {NORM,
     "heal",
     {LEVELS_INIT, L(CLASS_CLE, 5)},
     spell_heal,
     TAR_CHAR_DEFENSIVE,
     POS_FIGHTING,
     NULL,
     SLOT(28),
     50,
     12,
     TRUE,
     "",
     "!Heal!",
     ""},

    {NORM,
     "group heal",
     {LEVELS_INIT, L(CLASS_PAL, 5), L(CLASS_PRI, 25)},
     spell_group_heal,
     TAR_CHAR_DEFENSIVE,
     POS_FIGHTING,
     NULL,
     SLOT(169),
     50,
     12,
     TRUE,
     "",
     "!Group Heal!",
     ""},

    {NORM,
     "hypnosis",
     {LEVELS_INIT, L(CLASS_PSI, 14)},
     spell_hypnosis,
     TAR_CHAR_OFFENSIVE,
     POS_STANDING,
     NULL,
     SLOT(532),
     30,
     24,
     FALSE,
     "",
     "!Hypnosis!",
     ""},

    {NORM,
     "identify",
     {LEVELS_INIT, L(CLASS_MAG, 9)},
     spell_identify,
     TAR_OBJ_INV,
     POS_STANDING,
     NULL,
     SLOT(53),
     12,
     24,
     FALSE,
     "",
     "!Identify!",
     ""},

    {NORM,
     "infravision",
     {LEVELS_INIT, L(CLASS_MAG, 20)},
     spell_infravision,
     TAR_CHAR_DEFENSIVE,
     POS_STANDING,
     NULL,
     SLOT(77),
     5,
     18,
     FALSE,
     "",
     "You no longer see in the dark.",
     ""},

    {NORM,
     "influx",
     {LEVELS_INIT, L(CLASS_CLE, 65)},
     spell_influx,
     TAR_CHAR_DEFENSIVE,
     POS_FIGHTING,
     NULL,
     SLOT(503),
     75,
     24,
     TRUE,
     "",
     "!Influx!",
     ""},

    {NORM,
     "invis",
     {LEVELS_INIT, L(CLASS_MAG, 17)},
     spell_invis,
     TAR_IGNORE,
     POS_STANDING,
     &gsn_invis,
     SLOT(29),
     5,
     12,
     FALSE,
     "",
     "You are no longer invisible.",
     "$n's invisibilty fades."},

    {NORM,
     "know alignment",
     {LEVELS_INIT, L(CLASS_MAG, 13), L(CLASS_CLE, 22)},
     spell_know_alignment,
     TAR_CHAR_DEFENSIVE,
     POS_FIGHTING,
     NULL,
     SLOT(58),
     9,
     12,
     FALSE,
     "",
     "!Know Alignment!",
     ""},

    {NORM,
     "know weakness",
     {LEVELS_INIT, L(CLASS_PSI, 18)},
     spell_know_weakness,
     TAR_CHAR_SELF,
     POS_STANDING,
     NULL,
     SLOT(530),
     15,
     12,
     FALSE,
     "",
     "You are less aware of your enemy's weaknesses.",
     ""},

    {NORM,
     "know critical",
     {LEVELS_INIT, L(CLASS_PSI, 28)},
     spell_know_weakness,
     TAR_CHAR_SELF,
     POS_STANDING,
     NULL,
     SLOT(530),
     15,
     12,
     FALSE,
     "",
     "You are less aware of critical damage points.",
     ""},

    {NORM,
     "know item",
     {LEVELS_INIT, L(CLASS_PSI, 9)},
     spell_identify,
     TAR_OBJ_INV,
     POS_STANDING,
     NULL,
     SLOT(533),
     20,
     24,
     FALSE,
     "",
     "!Know Item!",
     ""},

    {NORM,
     "laser bolt",
     {LEVELS_INIT},
     spell_laserbolt,
     TAR_CHAR_OFFENSIVE,
     POS_FIGHTING,
     NULL,
     SLOT(511),
     35,
     12,
     FALSE,
     "laserbolt",
     "!laserbolt!",
     ""},

    {NORM,
     "lightning bolt",
     {LEVELS_INIT, L(CLASS_MAG, 24)},
     spell_lightning_bolt,
     TAR_CHAR_OFFENSIVE,
     POS_FIGHTING,
     NULL,
     SLOT(30),
     15,
     12,
     TRUE,
     "lightning bolt",
     "!Lightning Bolt!",
     ""},

    {NORM,
     "locate object",
     {LEVELS_INIT, L(CLASS_MAG, 16), L(CLASS_CLE, 30)},
     spell_locate_object,
     TAR_IGNORE,
     POS_STANDING,
     NULL,
     SLOT(31),
     20,
     18,
     FALSE,
     "",
     "!Locate Object!",
     ""},

    {NORM,
     "magic missile",
     {LEVELS_INIT, L(CLASS_MAG, 3)},
     spell_magic_missile,
     TAR_CHAR_OFFENSIVE,
     POS_FIGHTING,
     NULL,
     SLOT(32),
     15,
     12,
     TRUE,
     "magic missile",
     "!Magic Missile!",
     ""},

    {NORM,
     "mass invis",
     {LEVELS_INIT, L(CLASS_MAG, 60)},
     spell_mass_invis,
     TAR_IGNORE,
     POS_STANDING,
     &gsn_mass_invis,
     SLOT(69),
     20,
     24,
     FALSE,
     "",
     "!Mass Invis!",
     ""},

    {NORM,
     "mind flail",
     {LEVELS_INIT, L(CLASS_PSI, 4)},
     spell_mind_flail,
     TAR_CHAR_OFFENSIVE,
     POS_FIGHTING,
     NULL,
     SLOT(536),
     12,
     24,
     TRUE,
     "mind flail",
     "!Mind Flail!",
     ""},

    {NORM,
     "mystic armour",
     {LEVELS_INIT, L(CLASS_MAG, 10)},
     spell_mystic_armor,
     TAR_CHAR_DEFENSIVE,
     POS_STANDING,
     NULL,
     SLOT(590),
     18,
     24,
     FALSE,
     ""
     "Your Mystic Armour fades away",
     "The Mystic Armour around someone in the room fades away."},

    {NORM,
     "nerve fire",
     {LEVELS_INIT, L(CLASS_PSI, 60)},
     spell_nerve_fire,
     TAR_IGNORE,
     POS_FIGHTING,
     NULL,
     SLOT(520),
     50,
     24,
     TRUE,
     "nerve fire",
     "!Nerve Fire!",
     ""},

    {NORM,
     "peripheral extension",
     {LEVELS_INIT, L(CLASS_PSI, 19)},
     spell_night_vision,
     TAR_CHAR_SELF,
     POS_STANDING,
     NULL,
     SLOT(538),
     17,
     24,
     FALSE,
     "",
     "Your peripheral awareness returns to its normal range.",
     ""},

    {NORM,
     "pass door",
     {LEVELS_INIT, L(CLASS_MAG, 46)},
     spell_pass_door,
     TAR_CHAR_SELF,
     POS_STANDING,
     NULL,
     SLOT(74),
     20,
     12,
     FALSE,
     "",
     "You feel solid again.",
     "$n's body becomes more solid."},

    {NORM,
     "phase",
     {LEVELS_INIT, L(CLASS_PSI, 45)},
     spell_phase,
     TAR_CHAR_SELF,
     POS_STANDING,
     NULL,
     SLOT(522),
     20,
     12,
     FALSE,
     "",
     "You feel solid again.",
     "$n's body becomes more solid."},

    {NORM,
     "psychic crush",
     {LEVELS_INIT, L(CLASS_PSI, 19)},
     spell_physic_thrust,
     TAR_CHAR_OFFENSIVE,
     POS_FIGHTING,
     NULL,
     SLOT(537),
     33,
     24,
     TRUE,
     "psychic crush",
     "!Psychic Crush!",
     ""},

    {NORM,
     "psychic thrust",
     {LEVELS_INIT, L(CLASS_PSI, 7)},
     spell_physic_thrust,
     TAR_CHAR_OFFENSIVE,
     POS_FIGHTING,
     NULL,
     SLOT(537),
     22,
     24,
     TRUE,
     "psychic thrust",
     "!Physic Thrust!",
     ""},

    {NORM,
     "poison",
     {LEVELS_INIT},
     spell_poison,
     TAR_CHAR_OFFENSIVE,
     POS_STANDING,
     &gsn_poison,
     SLOT(33),
     10,
     12,
     FALSE,
     "poison",
     "You feel less sick.",
     "$n looks less sick."},

    {NORM,
     "protection",
     {LEVELS_INIT, L(CLASS_MAG, 9), L(CLASS_CLE, 12)},
     spell_protection,
     TAR_CHAR_SELF,
     POS_STANDING,
     NULL,
     SLOT(34),
     5,
     12,
     FALSE,
     "",
     "You feel less protected.",
     ""},

    {NORM,
     "psionic recovery",
     {LEVELS_INIT, L(CLASS_PSI, 5)},
     spell_psionic_recovery,
     TAR_CHAR_SELF,
     POS_FIGHTING,
     NULL,
     SLOT(78),
     5,
     12,
     TRUE,
     "",
     "You feel less protected.",
     ""},

    {NORM,
     "refresh",
     {LEVELS_INIT, L(CLASS_CLE, 11)},
     spell_refresh,
     TAR_CHAR_DEFENSIVE,
     POS_STANDING,
     NULL,
     SLOT(81),
     12,
     18,
     FALSE,
     "refresh",
     "!Refresh!",
     ""},

    {NORM,
     "refresh mana",
     {LEVELS_INIT},
     spell_refresh_mana,
     TAR_CHAR_DEFENSIVE,
     POS_STANDING,
     NULL,
     SLOT(81),
     12,
     18,
     FALSE,
     "refresh mana",
     "!Refresh mana!",
     ""},

    {NORM,
     "regen",
     {LEVELS_INIT, L(CLASS_MAG, 40)},
     spell_regen,
     TAR_CHAR_DEFENSIVE,
     POS_FIGHTING,
     NULL,
     SLOT(271),
     12,
     18,
     TRUE,
     "",
     "You are no longer regenerating quickly.",
     "$n is no longer regenerating quickly."},

    {NORM,
     "haste",
     {LEVELS_INIT, L(CLASS_WIZ, 84)},
     spell_haste,
     TAR_CHAR_DEFENSIVE,
     POS_FIGHTING,
     NULL,
     SLOT(271),
     12,
     18,
     TRUE,
     "",
     "You are no longer moving quickly.",
     "$n is no longer moving quickly."},

    {NORM,
     "overdrive",
     {LEVELS_INIT, L(CLASS_EGO, 57)},
     spell_overdrive,
     TAR_CHAR_SELF,
     POS_FIGHTING,
     NULL,
     SLOT(271),
     12,
     18,
     TRUE,
     "",
     "You are no longer acting quickly.",
     "$n is no longer acting quickly."},

    {NORM,
     "magical supremacy",
     {LEVELS_INIT, L(CLASS_WIZ, 42), L(CLASS_EGO, 13)},
     spell_magical_supremacy,
     TAR_CHAR_SELF,
     POS_FIGHTING,
     NULL,
     SLOT(271),
     12,
     18,
     TRUE,
     "",
     "You no longer have magical supremacy.",
     "$n no longer has magical supremacy."},

    {NORM,
     "slow",
     {LEVELS_INIT, L(CLASS_WIZ, 92)},
     spell_slow,
     TAR_CHAR_OFFENSIVE,
     POS_FIGHTING,
     NULL,
     SLOT(271),
     12,
     18,
     TRUE,
     "",
     "You are no longer acting slowly.",
     "$n is no longer acting slowly."},

    {NORM,
     "feeble mind",
     {LEVELS_INIT, L(CLASS_NEC, 45)},
     spell_feeble_mind,
     TAR_CHAR_OFFENSIVE,
     POS_FIGHTING,
     NULL,
     SLOT(271),
     12,
     18,
     TRUE,
     "",
     "You are now thinking quickly.",
     "$n is now thinking quickly."},

    {NORM,
     "feeble body",
     {LEVELS_INIT, L(CLASS_NEC, 45)},
     spell_feeble_body,
     TAR_CHAR_OFFENSIVE,
     POS_FIGHTING,
     NULL,
     SLOT(271),
     12,
     18,
     TRUE,
     "",
     "You are now moving quickly.",
     "$n is now moving quickly."},

    {NORM,
     "remove curse",
     {LEVELS_INIT, L(CLASS_MAG, 36), L(CLASS_CLE, 27)},
     spell_remove_curse,
     TAR_CHAR_DEFENSIVE,
     POS_STANDING,
     NULL,
     SLOT(35),
     5,
     12,
     FALSE,
     "",
     "!Remove Curse!",
     ""},

    {NORM,
     "sanctuary",
     {LEVELS_INIT, L(CLASS_CLE, 70)},
     spell_sanctuary,
     TAR_CHAR_DEFENSIVE,
     POS_STANDING,
     NULL,
     SLOT(36),
     75,
     12,
     FALSE,
     "",
     "The white aura around your body fades.",
     "The white aura around $n's body fades."},

    {NORM,
     "refuge",
     {LEVELS_INIT, L(CLASS_PAL, 32), L(CLASS_PRI, 32)},
     spell_refuge,
     TAR_CHAR_DEFENSIVE,
     POS_STANDING,
     NULL,
     SLOT(0),
     75,
     12,
     TRUE,
     "",
     "The rainbow aura around your body fades.",
     "The rainbow aura around $n's body fades."},

    {NORM,
     "seal room",
     {LEVELS_INIT, L(CLASS_MAG, 70), L(CLASS_CLE, 50)},
     spell_seal_room,
     TAR_IGNORE,
     POS_STANDING,
     NULL,
     SLOT(541),
     75,
     12,
     FALSE,
     "",
     "The Energy web around this room fades.",
     ""},

    {NORM,
     "architecture scan",
     {LEVELS_INIT, L(CLASS_PSI, 7)},
     spell_see_magic,
     TAR_CHAR_SELF,
     POS_STANDING,
     NULL,
     SLOT(526),
     8,
     12,
     FALSE,
     "",
     "You no longer perceive structural magical patterns.",
     ""},

    {NORM,
     "pale imprint",
     {LEVELS_INIT, L(CLASS_PSI, 10)},
     spell_pale_imprint,
     TAR_CHAR_SELF,
     POS_STANDING,
     NULL,
     SLOT(515),
     12,
     12,
     FALSE,
     "",
     "The Pale Ledger's imprint fades from your awareness.",
     ""},

    {NORM,
     "shield",
     {LEVELS_INIT, L(CLASS_MAG, 9)},
     spell_shield,
     TAR_CHAR_DEFENSIVE,
     POS_STANDING,
     NULL,
     SLOT(67),
     12,
     18,
     FALSE,
     "",
     "Your force shield shimmers, then fades away.",
     "$n's force field shimmers, then fades away."},

    {NORM,
     "shocking grasp",
     {LEVELS_INIT, L(CLASS_MAG, 5)},
     spell_shocking_grasp,
     TAR_CHAR_OFFENSIVE,
     POS_FIGHTING,
     NULL,
     SLOT(82),
     15,
     12,
     TRUE,
     "shocking grasp",
     "!Shocking Grasp!",
     ""},

    {NORM,
     "sight",
     {LEVELS_INIT, L(CLASS_MAG, 30)},
     spell_cure_blindness,
     TAR_CHAR_DEFENSIVE,
     POS_STANDING,
     NULL,
     SLOT(592),
     20,
     24,
     FALSE,
     "",
     "!Sight!",
     ""},

    {NORM,
     "sleep",
     {LEVELS_INIT},
     spell_sleep,
     TAR_CHAR_OFFENSIVE,
     POS_STANDING,
     &gsn_sleep,
     SLOT(38),
     15,
     12,
     FALSE,
     "",
     "You feel less tired.",
     "$n starts looking much more awake."},

    {NORM,          "stalker",
     {LEVELS_INIT}, spell_stalker,
     TAR_IGNORE,    POS_STANDING,
     NULL,          SLOT(401),
     100,           24,
     FALSE,         "",
     "!Stalker!",   ""},

    {NORM,
     "stone skin",
     {LEVELS_INIT, L(CLASS_MAG, 36), L(CLASS_DRU, 28)},
     spell_stone_skin,
     TAR_CHAR_SELF,
     POS_STANDING,
     NULL,
     SLOT(66),
     12,
     18,
     TRUE,
     "",
     "Your skin feels soft again.",
     "$n's skin loses it's stone-like look."},

    {NORM,
     "suffocate",
     {LEVELS_INIT, L(CLASS_PSI, 46)},
     spell_suffocate,
     TAR_CHAR_OFFENSIVE,
     POS_FIGHTING,
     NULL,
     SLOT(516),
     30,
     24,
     TRUE,
     "a choking hand",
     "!Suffocate!",
     ""},

    {NORM,         "summon",   {LEVELS_INIT, L(CLASS_MAG, 35)},
     spell_summon, TAR_IGNORE, POS_STANDING,
     NULL,         SLOT(40),   50,
     12,           FALSE,      "",
     "!Summon!",   ""},

    {NORM,
     "teleport",
     {LEVELS_INIT, L(CLASS_MAG, 40)},
     spell_teleport,
     TAR_CHAR_SELF,
     POS_FIGHTING,
     NULL,
     SLOT(2),
     35,
     12,
     FALSE,
     "",
     "!Teleport!",
     ""},

    {NORM,
     "travel",
     {LEVELS_INIT},
     spell_travel,
     TAR_CHAR_SELF,
     POS_STANDING,
     NULL,
     SLOT(599),
     50,
     24,
     FALSE,
     "",
     "!Travel!",
     ""},

    {NORM,
     "ventriloquate",
     {LEVELS_INIT},
     spell_ventriloquate,
     TAR_IGNORE,
     POS_STANDING,
     NULL,
     SLOT(41),
     5,
     12,
     FALSE,
     "",
     "!Ventriloquate!",
     ""},

    {NORM,
     "weaken",
     {LEVELS_INIT},
     spell_weaken,
     TAR_CHAR_OFFENSIVE,
     POS_FIGHTING,
     NULL,
     SLOT(68),
     20,
     12,
     FALSE,
     "spell",
     "You feel stronger.",
     "$n looks stronger."},

    {NORM,         "beacon",   {LEVELS_INIT, L(CLASS_MAG, 70)},
     spell_beacon, TAR_IGNORE, POS_STANDING,
     NULL,         SLOT(399),  25,
     12,           FALSE,      "",
     "!Beacon!",   ""},

    {NORM,         "portal",   {LEVELS_INIT, L(CLASS_MAG, 80)},
     spell_portal, TAR_IGNORE, POS_FIGHTING,
     NULL,         SLOT(334),  100,
     12,           FALSE,      "",
     "!Portal!",   ""},

    {NORM,         "window",   {LEVELS_INIT, L(CLASS_MAG, 70)},
     spell_window, TAR_IGNORE, POS_STANDING,
     NULL,         SLOT(333),  100,
     12,           FALSE,      "",
     "!Window!",   ""},

    {NORM,
     "word of recall",
     {LEVELS_INIT, L(CLASS_CLE, 66)},
     spell_word_of_recall,
     TAR_CHAR_SELF,
     POS_RESTING,
     NULL,
     SLOT(42),
     5,
     12,
     FALSE,
     "",
     "!Word of Recall!",
     ""},

    {NORM,
     "hellspawn",
     {LEVELS_INIT},
     spell_hellspawn,
     TAR_CHAR_OFFENSIVE,
     POS_FIGHTING,
     NULL,
     SLOT(512),
     50,
     12,
     TRUE,
     "HellSpawn",
     "!Hellspawn!",
     ""},

    {NORM,
     "planergy",
     {LEVELS_INIT, L(CLASS_PSI, 5)},
     spell_planergy,
     TAR_CHAR_OFFENSIVE,
     POS_FIGHTING,
     NULL,
     SLOT(504),
     25,
     24,
     TRUE,
     "energy",
     "!planergy!",
     ""},

    {NORM,        "visit",    {LEVELS_INIT, L(CLASS_PSI, 32)},
     spell_visit, TAR_IGNORE, POS_STANDING,
     NULL,        SLOT(505),  50,
     48,          FALSE,      "",
     "!visit!",   ""},

    {NORM,
     "barrier",
     {LEVELS_INIT, L(CLASS_PSI, 8)},
     spell_barrier,
     TAR_CHAR_SELF,
     POS_STANDING,
     NULL,
     SLOT(506),
     30,
     24,
     FALSE,
     "",
     "Your barrier slowly fades.",
     "The barrier around $n fades."},

    {NORM,
     "phobia",
     {LEVELS_INIT, L(CLASS_PSI, 10)},
     spell_phobia,
     TAR_CHAR_OFFENSIVE,
     POS_FIGHTING,
     NULL,
     SLOT(507),
     32,
     24,
     FALSE,
     "phobia attack",
     "!phobia!",
     ""},

    {NORM,
     "mind bolt",
     {LEVELS_INIT, L(CLASS_PSI, 12)},
     spell_mind_bolt,
     TAR_CHAR_OFFENSIVE,
     POS_FIGHTING,
     NULL,
     SLOT(519),
     40,
     12,
     TRUE,
     "Mind Bolt",
     "!MindBolt!",
     ""},

    {NORM,
     "recurrence loop",
     {LEVELS_INIT, L(CLASS_PSI, 35)},
     spell_recurrence_loop,
     TAR_IGNORE,
     POS_FIGHTING,
     NULL,
     SLOT(508),
     40,
     24,
     TRUE,
     "recurrence loop",
     "!Recurrence Loop!",
     ""},

    {NORM,
     "chain lightning",
     {LEVELS_INIT, L(CLASS_MAG, 65)},
     spell_chain_lightning,
     TAR_IGNORE,
     POS_FIGHTING,
     NULL,
     SLOT(509),
     25,
     24,
     TRUE,
     "lightening bolt",
     "!chain-light!",
     ""},

    {NORM,
     "static",
     {LEVELS_INIT},
     spell_static,
     TAR_CHAR_OFFENSIVE,
     POS_FIGHTING,
     NULL,
     SLOT(510),
     40,
     24,
     TRUE,
     "discharge",
     "!static!",
     ""},

    {NORM,
     "cloak:absorption",
     {LEVELS_INIT},
     spell_cloak_absorb,
     TAR_CHAR_DEFENSIVE,
     POS_STANDING,
     NULL,
     SLOT(221),
     500,
     12,
     FALSE,
     "",
     "@@NThe @@lcloak@@N around your body fades.",
     "@@NThe @@lcloak@@N around $n's body fades."},

    {NORM,
     "cloak:reflection",
     {LEVELS_INIT},
     spell_cloak_reflect,
     TAR_CHAR_DEFENSIVE,
     POS_STANDING,
     NULL,
     SLOT(222),
     500,
     12,
     FALSE,
     "",
     "@@NThe @@lc@@el@@ro@@ya@@ak@@N around your body fades.",
     "@@NThe @@lc@@el@@ro@@ya@@ak@@N around $n's body fades."},

    {NORM,
     "cloak:flaming",
     {LEVELS_INIT, L(CLASS_SOR, 48)},
     spell_cloak_flaming,
     TAR_CHAR_DEFENSIVE,
     POS_STANDING,
     NULL,
     SLOT(223),
     750,
     12,
     FALSE,
     "",
     "@@NThe @@ecloak@@N around your body fades.",
     "@@NThe @@ecloak@@N around $n's body fades."},

    {NORM,
     "cloak:elements",
     {LEVELS_INIT, L(CLASS_WIZ, 48)},
     spell_cloak_elements,
     TAR_CHAR_DEFENSIVE,
     POS_STANDING,
     NULL,
     SLOT(225),
     750,
     12,
     FALSE,
     "",
     "@@NThe @@lcloak@@N around your body fades.",
     "@@NThe @@lcloak@@N around $n's body fades."},

    {NORM,
     "cloak:adept",
     {LEVELS_INIT},
     spell_cloak_adept,
     TAR_CHAR_DEFENSIVE,
     POS_STANDING,
     NULL,
     SLOT(226),
     500,
     12,
     FALSE,
     "",
     "@@NThe @@Wcloak@@N around your body fades.",
     "@@NThe @@Wcloak@@N around $n's body fades."},

    {NORM,
     "psishield",
     {LEVELS_INIT, L(CLASS_EGO, 48)},
     spell_psishield,
     TAR_CHAR_DEFENSIVE,
     POS_FIGHTING,
     NULL,
     SLOT(767),
     400,
     12,
     FALSE,
     "",
     "",
     ""},

    {NORM,
     "arcaneshield",
     {LEVELS_INIT, L(CLASS_BRA, 48)},
     spell_arcaneshield,
     TAR_CHAR_DEFENSIVE,
     POS_FIGHTING,
     NULL,
     SLOT(768),
     350,
     12,
     FALSE,
     "",
     "",
     ""},

    {NORM,
     "holyshield",
     {LEVELS_INIT, L(CLASS_PRI, 48)},
     spell_holyshield,
     TAR_CHAR_DEFENSIVE,
     POS_FIGHTING,
     NULL,
     SLOT(770),
     400,
     12,
     FALSE,
     "",
     "",
     ""},

    {NORM,
     "acid breath",
     {LEVELS_INIT},
     spell_acid_breath,
     TAR_CHAR_OFFENSIVE,
     POS_FIGHTING,
     NULL,
     SLOT(200),
     0,
     4,
     FALSE,
     "blast of acid",
     "!Acid Breath!",
     ""},

    {NORM,
     "fire breath",
     {LEVELS_INIT},
     spell_fire_breath,
     TAR_CHAR_OFFENSIVE,
     POS_FIGHTING,
     NULL,
     SLOT(201),
     0,
     4,
     FALSE,
     "blast of flame",
     "!Fire Breath!",
     ""},

    {NORM,
     "frost breath",
     {LEVELS_INIT},
     spell_frost_breath,
     TAR_CHAR_OFFENSIVE,
     POS_FIGHTING,
     NULL,
     SLOT(202),
     0,
     4,
     FALSE,
     "blast of frost",
     "!Frost Breath!",
     ""},

    {NORM,
     "gas breath",
     {LEVELS_INIT},
     spell_gas_breath,
     TAR_IGNORE,
     POS_FIGHTING,
     NULL,
     SLOT(203),
     0,
     4,
     FALSE,
     "blast of gas",
     "!Gas Breath!",
     ""},

    {NORM,
     "lightning breath",
     {LEVELS_INIT},
     spell_lightning_breath,
     TAR_CHAR_OFFENSIVE,
     POS_FIGHTING,
     NULL,
     SLOT(204),
     0,
     4,
     FALSE,
     "blast of lightning",
     "!Lightning Breath!",
     ""},

    /* New spells: Magi */
    {NORM,
     "arcane lock",
     {LEVELS_INIT, L(CLASS_MAG, 18)},
     spell_arcane_lock,
     TAR_IGNORE,
     POS_STANDING,
     NULL,
     SLOT(703),
     15,
     24,
     FALSE,
     "",
     "!Arcane Lock!",
     ""},

    {NORM,
     "elemental ward",
     {LEVELS_INIT, L(CLASS_MAG, 55)},
     spell_elemental_ward,
     TAR_CHAR_SELF,
     POS_STANDING,
     NULL,
     SLOT(702),
     50,
     24,
     FALSE,
     "",
     "!Elemental Ward!",
     ""},

    {NORM,
     "mana barrier",
     {LEVELS_INIT, L(CLASS_MAG, 25)},
     spell_mana_barrier,
     TAR_CHAR_SELF,
     POS_STANDING,
     NULL,
     SLOT(701),
     30,
     24,
     FALSE,
     "",
     "!Mana Barrier!",
     ""},

    {NORM,
     "mirror image",
     {LEVELS_INIT, L(CLASS_MAG, 38)},
     spell_mirror_image,
     TAR_CHAR_SELF,
     POS_STANDING,
     NULL,
     SLOT(704),
     25,
     24,
     FALSE,
     "",
     "!Mirror Image!",
     ""},

    {NORM,
     "wall of fire",
     {LEVELS_INIT, L(CLASS_MAG, 32)},
     spell_wall_of_fire,
     TAR_IGNORE,
     POS_FIGHTING,
     NULL,
     SLOT(700),
     30,
     24,
     TRUE,
     "wall of fire",
     "!Wall of Fire!",
     ""},

    /* New spells: Cleric */
    {NORM,
     "consecrate",
     {LEVELS_INIT, L(CLASS_CLE, 35)},
     spell_consecrate,
     TAR_IGNORE,
     POS_STANDING,
     NULL,
     SLOT(708),
     50,
     24,
     FALSE,
     "",
     "!Consecrate!",
     ""},

    {NORM,
     "divine strike",
     {LEVELS_INIT, L(CLASS_CLE, 4)},
     spell_divine_strike,
     TAR_CHAR_OFFENSIVE,
     POS_FIGHTING,
     NULL,
     SLOT(705),
     15,
     12,
     TRUE,
     "divine strike",
     "!Divine Strike!",
     ""},

    {NORM,
     "exorcism",
     {LEVELS_INIT, L(CLASS_CLE, 55)},
     spell_exorcism,
     TAR_CHAR_OFFENSIVE,
     POS_FIGHTING,
     NULL,
     SLOT(711),
     25,
     12,
     TRUE,
     "exorcism",
     "!Exorcism!",
     ""},

    {NORM,
     "disk's word",
     {LEVELS_INIT, L(CLASS_CLE, 60)},
     spell_holy_word,
     TAR_IGNORE,
     POS_FIGHTING,
     NULL,
     SLOT(710),
     50,
     24,
     TRUE,
     "disk's word",
     "!Disk's Word!",
     ""},

    {NORM,
     "solar invocation",
     {LEVELS_INIT, L(CLASS_CLE, 22)},
     spell_prayer,
     TAR_IGNORE,
     POS_STANDING,
     NULL,
     SLOT(712),
     25,
     24,
     FALSE,
     "",
     "!Solar Invocation!",
     ""},

    {NORM,
     "restoration",
     {LEVELS_INIT, L(CLASS_CLE, 45)},
     spell_restoration,
     TAR_CHAR_DEFENSIVE,
     POS_STANDING,
     NULL,
     SLOT(707),
     40,
     24,
     FALSE,
     "",
     "!Restoration!",
     ""},

    {NORM,
     "solar flare",
     {LEVELS_INIT, L(CLASS_CLE, 50)},
     spell_solar_flare,
     TAR_CHAR_OFFENSIVE,
     POS_FIGHTING,
     NULL,
     SLOT(709),
     25,
     12,
     TRUE,
     "solar flare",
     "!Solar Flare!",
     ""},

    {NORM,
     "turn undead",
     {LEVELS_INIT, L(CLASS_CLE, 15)},
     spell_turn_undead,
     TAR_IGNORE,
     POS_FIGHTING,
     NULL,
     SLOT(706),
     20,
     24,
     FALSE,
     "",
     "!Turn Undead!",
     ""},

    /* New spells: Psionicist */
    {NORM,
     "astral projection",
     {LEVELS_INIT, L(CLASS_PSI, 60)},
     spell_astral_projection,
     TAR_CHAR_SELF,
     POS_STANDING,
     NULL,
     SLOT(713),
     40,
     24,
     FALSE,
     "",
     "!Astral Projection!",
     ""},

    {NORM,
     "mindwall",
     {LEVELS_INIT, L(CLASS_PSI, 22)},
     spell_mindwall,
     TAR_CHAR_SELF,
     POS_STANDING,
     NULL,
     SLOT(717),
     25,
     24,
     FALSE,
     "",
     "!Mindwall!",
     ""},

    {NORM,
     "pain",
     {LEVELS_INIT, L(CLASS_PSI, 28)},
     spell_pain,
     TAR_CHAR_OFFENSIVE,
     POS_FIGHTING,
     NULL,
     SLOT(714),
     25,
     12,
     TRUE,
     "psychic pain",
     "!Pain!",
     ""},

    {NORM,
     "precognition",
     {LEVELS_INIT, L(CLASS_PSI, 45)},
     spell_precognition,
     TAR_CHAR_SELF,
     POS_STANDING,
     NULL,
     SLOT(716),
     30,
     24,
     FALSE,
     "",
     "!Precognition!",
     ""},

    {NORM,
     "thoughtsteal",
     {LEVELS_INIT, L(CLASS_PSI, 40)},
     spell_thoughtsteal,
     TAR_CHAR_OFFENSIVE,
     POS_FIGHTING,
     NULL,
     SLOT(715),
     30,
     12,
     TRUE,
     "thoughtsteal",
     "!Thoughtsteal!",
     ""},

    /* Grand Magi adept spells */

    {NORM,
     "elemental confluence",
     {LEVELS_INIT, L(CLASS_GMA, 18)},
     spell_elemental_confluence,
     TAR_CHAR_OFFENSIVE,
     POS_FIGHTING,
     NULL,
     SLOT(760),
     200,
     12,
     TRUE,
     "elemental confluence",
     "!elemental confluence!",
     ""},

    {NORM,
     "convergence shield",
     {LEVELS_INIT, L(CLASS_GMA, 8)},
     spell_convergence_shield,
     TAR_CHAR_SELF,
     POS_STANDING,
     NULL,
     SLOT(761),
     100,
     12,
     FALSE,
     "",
     "Your convergence shield dissipates.",
     "The elemental barrier around $n fades."},

    /* Templar adept spells */

    {NORM,
     "sacred ward",
     {LEVELS_INIT, L(CLASS_TEM, 5)},
     spell_sacred_ward,
     TAR_IGNORE,
     POS_STANDING,
     NULL,
     SLOT(762),
     80,
     24,
     FALSE,
     "",
     "The sacred ward's warmth fades.",
     "The sacred ward around $n fades."},

    /* Kinetimancer adept spells */

    {NORM,
     "momentum drain",
     {LEVELS_INIT, L(CLASS_KIN, 5)},
     spell_momentum_drain,
     TAR_CHAR_OFFENSIVE,
     POS_FIGHTING,
     NULL,
     SLOT(763),
     100,
     12,
     TRUE,
     "momentum drain",
     "Your momentum returns to normal.",
     "$n's momentum returns to normal."},

    {NORM,
     "entropic shield",
     {LEVELS_INIT, L(CLASS_KIN, 8)},
     spell_entropic_shield,
     TAR_CHAR_SELF,
     POS_STANDING,
     NULL,
     SLOT(764),
     100,
     12,
     FALSE,
     "",
     "Your entropic shield dissipates.",
     "The entropic field around $n fades."},

    {NORM,
     "cognitive disruption",
     {LEVELS_INIT, L(CLASS_KIN, 12)},
     spell_cognitive_disruption,
     TAR_CHAR_OFFENSIVE,
     POS_FIGHTING,
     NULL,
     SLOT(765),
     120,
     12,
     TRUE,
     "cognitive disruption",
     "Your concentration returns.",
     "$n's concentration returns."},

    {NORM,
     "predictive collapse",
     {LEVELS_INIT, L(CLASS_KIN, 15)},
     spell_predictive_collapse,
     TAR_CHAR_OFFENSIVE,
     POS_FIGHTING,
     NULL,
     SLOT(766),
     150,
     12,
     TRUE,
     "predictive collapse",
     "Your combat patterns stabilize.",
     "$n's combat patterns stabilize."},

    /* ================================================================
     * Druid spells (slots 800-849, growth > 0 triggers Overgrowth)
     * ================================================================ */

    /* --- Offensive (14) --- */
    {NORM,
     "thornlash",
     {LEVELS_INIT, L(CLASS_DRU, 3)},
     spell_thornlash,
     TAR_CHAR_OFFENSIVE,
     POS_FIGHTING,
     NULL,
     SLOT(800),
     12,
     12,
     TRUE,
     "thornlash",
     "!Thornlash!",
     "",
     .growth = 3},

    {NORM,
     "nettlesting",
     {LEVELS_INIT, L(CLASS_DRU, 6)},
     spell_nettlesting,
     TAR_CHAR_OFFENSIVE,
     POS_FIGHTING,
     NULL,
     SLOT(801),
     12,
     12,
     TRUE,
     "nettlesting",
     "!Nettlesting!",
     "",
     .growth = 3},

    {NORM,
     "rockburst",
     {LEVELS_INIT, L(CLASS_DRU, 10)},
     spell_rockburst,
     TAR_CHAR_OFFENSIVE,
     POS_FIGHTING,
     NULL,
     SLOT(802),
     15,
     12,
     TRUE,
     "rockburst",
     "!Rockburst!",
     "",
     .growth = 4},

    {NORM,
     "wither",
     {LEVELS_INIT, L(CLASS_DRU, 16)},
     spell_wither,
     TAR_CHAR_OFFENSIVE,
     POS_FIGHTING,
     NULL,
     SLOT(803),
     15,
     12,
     TRUE,
     "wither",
     "!Wither!",
     "",
     .growth = 4},

    {NORM,
     "briar volley",
     {LEVELS_INIT, L(CLASS_DRU, 20)},
     spell_briar_volley,
     TAR_CHAR_OFFENSIVE,
     POS_FIGHTING,
     NULL,
     SLOT(804),
     18,
     12,
     TRUE,
     "briar volley",
     "!Briar Volley!",
     "",
     .growth = 4},

    {NORM,
     "blight touch",
     {LEVELS_INIT, L(CLASS_DRU, 25)},
     spell_blight_touch,
     TAR_CHAR_OFFENSIVE,
     POS_FIGHTING,
     NULL,
     SLOT(805),
     20,
     12,
     TRUE,
     "blight touch",
     "The blight fades from your skin.",
     "$n's blight fades.",
     .growth = 5},

    {NORM,
     "tremor",
     {LEVELS_INIT, L(CLASS_DRU, 32)},
     spell_tremor,
     TAR_CHAR_OFFENSIVE,
     POS_FIGHTING,
     NULL,
     SLOT(806),
     20,
     12,
     TRUE,
     "tremor",
     "!Tremor!",
     "",
     .growth = 5},

    {NORM,
     "creeping rot",
     {LEVELS_INIT, L(CLASS_DRU, 38)},
     spell_creeping_rot,
     TAR_CHAR_OFFENSIVE,
     POS_FIGHTING,
     NULL,
     SLOT(807),
     22,
     12,
     TRUE,
     "creeping rot",
     "The rot consuming you fades.",
     "$n's rot fades.",
     .growth = 5},

    {NORM,
     "fissure",
     {LEVELS_INIT, L(CLASS_DRU, 46)},
     spell_fissure,
     TAR_CHAR_OFFENSIVE,
     POS_FIGHTING,
     NULL,
     SLOT(808),
     25,
     12,
     TRUE,
     "fissure",
     "!Fissure!",
     "",
     .growth = 6},

    {NORM,
     "fungal eruption",
     {LEVELS_INIT, L(CLASS_DRU, 55)},
     spell_fungal_eruption,
     TAR_IGNORE,
     POS_FIGHTING,
     NULL,
     SLOT(809),
     30,
     12,
     TRUE,
     "fungal eruption",
     "!Fungal Eruption!",
     "",
     .growth = 6},

    {NORM,        "quake",    {LEVELS_INIT, L(CLASS_DRU, 60)},
     spell_quake, TAR_IGNORE, POS_FIGHTING,
     NULL,        SLOT(810),  30,
     12,          TRUE,       "quake",
     "!Quake!",   "",         .growth = 6},

    {NORM,
     "strangling vines",
     {LEVELS_INIT, L(CLASS_DRU, 65)},
     spell_strangling_vines,
     TAR_CHAR_OFFENSIVE,
     POS_FIGHTING,
     NULL,
     SLOT(811),
     35,
     12,
     TRUE,
     "strangling vines",
     "The vines around your legs wither away.",
     "The vines around $n wither away.",
     .growth = 5},

    {NORM,
     "rot",
     {LEVELS_INIT, L(CLASS_DRU, 75)},
     spell_rot,
     TAR_CHAR_OFFENSIVE,
     POS_FIGHTING,
     NULL,
     SLOT(812),
     40,
     12,
     TRUE,
     "rot",
     "!Rot!",
     "",
     .growth = 7},

    {NORM,
     "upheaval",
     {LEVELS_INIT, L(CLASS_DRU, 85)},
     spell_upheaval,
     TAR_IGNORE,
     POS_FIGHTING,
     NULL,
     SLOT(813),
     50,
     12,
     TRUE,
     "upheaval",
     "!Upheaval!",
     "",
     .growth = 7},

    /* --- Healing (7) --- */
    {NORM,
     "sap mend",
     {LEVELS_INIT, L(CLASS_DRU, 3)},
     spell_sap_mend,
     TAR_CHAR_DEFENSIVE,
     POS_STANDING,
     NULL,
     SLOT(814),
     8,
     12,
     FALSE,
     "",
     "!Sap Mend!",
     "",
     .growth = 3},

    {NORM,
     "mend wounds",
     {LEVELS_INIT, L(CLASS_DRU, 12)},
     spell_mend_wounds,
     TAR_CHAR_DEFENSIVE,
     POS_STANDING,
     NULL,
     SLOT(815),
     12,
     12,
     FALSE,
     "",
     "!Mend Wounds!",
     "",
     .growth = 4},

    {NORM,
     "purge toxin",
     {LEVELS_INIT, L(CLASS_DRU, 22)},
     spell_purge_toxin,
     TAR_CHAR_DEFENSIVE,
     POS_STANDING,
     NULL,
     SLOT(816),
     10,
     12,
     FALSE,
     "",
     "!Purge Toxin!",
     "",
     .growth = 3},

    {NORM,
     "verdant mend",
     {LEVELS_INIT, L(CLASS_DRU, 35)},
     spell_verdant_mend,
     TAR_CHAR_DEFENSIVE,
     POS_STANDING,
     NULL,
     SLOT(817),
     20,
     12,
     FALSE,
     "",
     "!Verdant Mend!",
     "",
     .growth = 5},

    {NORM,
     "heartwood balm",
     {LEVELS_INIT, L(CLASS_DRU, 50)},
     spell_heartwood_balm,
     TAR_CHAR_DEFENSIVE,
     POS_STANDING,
     NULL,
     SLOT(818),
     15,
     12,
     FALSE,
     "",
     "!Heartwood Balm!",
     "",
     .growth = 5},

    {NORM,
     "primal restoration",
     {LEVELS_INIT, L(CLASS_DRU, 70)},
     spell_primal_restoration,
     TAR_CHAR_DEFENSIVE,
     POS_STANDING,
     NULL,
     SLOT(819),
     35,
     12,
     FALSE,
     "",
     "!Primal Restoration!",
     "",
     .growth = 6},

    {NORM,
     "sap transfusion",
     {LEVELS_INIT, L(CLASS_DRU, 80)},
     spell_sap_transfusion,
     TAR_CHAR_NOTSELF,
     POS_STANDING,
     NULL,
     SLOT(820),
     10,
     12,
     FALSE,
     "",
     "!Sap Transfusion!",
     "",
     .growth = 3},

    /* --- Buff (8) --- */
    {NORM,
     "barkskin",
     {LEVELS_INIT, L(CLASS_DRU, 5)},
     spell_barkskin,
     TAR_CHAR_SELF,
     POS_STANDING,
     NULL,
     SLOT(821),
     10,
     24,
     FALSE,
     "",
     "Your bark-like skin softens.",
     "$n's bark-like skin softens.",
     .growth = 2},

    {NORM,
     "roothold",
     {LEVELS_INIT, L(CLASS_DRU, 9)},
     spell_roothold,
     TAR_CHAR_SELF,
     POS_STANDING,
     NULL,
     SLOT(822),
     12,
     24,
     FALSE,
     "",
     "The roots holding you dissolve.",
     "The roots holding $n dissolve.",
     .growth = 2},

    {NORM,
     "thornhide",
     {LEVELS_INIT, L(CLASS_DRU, 14)},
     spell_thornhide,
     TAR_CHAR_SELF,
     POS_STANDING,
     NULL,
     SLOT(823),
     15,
     24,
     FALSE,
     "",
     "The thorns on your skin retract.",
     "The thorns on $n's skin retract.",
     .growth = 2},

    /* stone skin is shared with Magi (slot 66, CLASS_DRU level 28) */

    {NORM,
     "ironpine vigor",
     {LEVELS_INIT, L(CLASS_DRU, 36)},
     spell_ironpine_vigor,
     TAR_CHAR_DEFENSIVE,
     POS_STANDING,
     NULL,
     SLOT(824),
     20,
     24,
     FALSE,
     "",
     "The ironpine vigor fades.",
     "$n's ironpine vigor fades.",
     .growth = 3},

    {NORM,
     "gift of the forest",
     {LEVELS_INIT, L(CLASS_DRU, 45)},
     spell_gift_of_the_forest,
     TAR_CHAR_DEFENSIVE,
     POS_STANDING,
     NULL,
     SLOT(825),
     20,
     24,
     FALSE,
     "",
     "The forest's gift fades from you.",
     "The forest's gift fades from $n.",
     .growth = 3},

    {NORM,
     "natures ward",
     {LEVELS_INIT, L(CLASS_DRU, 55)},
     spell_natures_ward,
     TAR_CHAR_SELF,
     POS_STANDING,
     NULL,
     SLOT(826),
     25,
     24,
     FALSE,
     "",
     "Nature's ward fades.",
     "Nature's ward around $n fades.",
     .growth = 3},

    {NORM,
     "ancient bark",
     {LEVELS_INIT, L(CLASS_DRU, 68)},
     spell_ancient_bark,
     TAR_CHAR_SELF,
     POS_STANDING,
     NULL,
     SLOT(827),
     35,
     24,
     FALSE,
     "",
     "The ancient bark encasing you crumbles away.",
     "The ancient bark encasing $n crumbles away.",
     .growth = 3},

    /* --- Debuff (7) --- */
    {NORM,
     "tangling roots",
     {LEVELS_INIT, L(CLASS_DRU, 8)},
     spell_tangling_roots,
     TAR_CHAR_OFFENSIVE,
     POS_FIGHTING,
     NULL,
     SLOT(828),
     10,
     12,
     TRUE,
     "",
     "The roots tangling you wither.",
     "The roots tangling $n wither.",
     .growth = 3},

    {NORM,
     "sap strength",
     {LEVELS_INIT, L(CLASS_DRU, 18)},
     spell_sap_strength,
     TAR_CHAR_OFFENSIVE,
     POS_FIGHTING,
     NULL,
     SLOT(829),
     15,
     12,
     TRUE,
     "",
     "Your strength returns.",
     "$n looks stronger.",
     .growth = 4},

    {NORM,
     "spore cloud",
     {LEVELS_INIT, L(CLASS_DRU, 30)},
     spell_spore_cloud,
     TAR_CHAR_OFFENSIVE,
     POS_FIGHTING,
     NULL,
     SLOT(830),
     18,
     12,
     TRUE,
     "",
     "The spores clear from your eyes.",
     "$n blinks the spores from $s eyes.",
     .growth = 4},

    {NORM,
     "wither limbs",
     {LEVELS_INIT, L(CLASS_DRU, 40)},
     spell_wither_limbs,
     TAR_CHAR_OFFENSIVE,
     POS_FIGHTING,
     NULL,
     SLOT(831),
     20,
     12,
     TRUE,
     "",
     "Your limbs feel normal again.",
     "$n's limbs return to normal.",
     .growth = 4},

    {NORM,
     "entangling growth",
     {LEVELS_INIT, L(CLASS_DRU, 52)},
     spell_entangling_growth,
     TAR_CHAR_OFFENSIVE,
     POS_FIGHTING,
     NULL,
     SLOT(832),
     25,
     12,
     TRUE,
     "",
     "The entangling growth withers.",
     "The growth around $n withers.",
     .growth = 4},

    {NORM,
     "curse of decay",
     {LEVELS_INIT, L(CLASS_DRU, 62)},
     spell_curse_of_decay,
     TAR_CHAR_OFFENSIVE,
     POS_FIGHTING,
     NULL,
     SLOT(833),
     30,
     12,
     TRUE,
     "",
     "The curse of decay lifts.",
     "The curse of decay lifts from $n.",
     .growth = 5},

    {NORM,
     "creeping blight",
     {LEVELS_INIT, L(CLASS_DRU, 78)},
     spell_creeping_blight,
     TAR_CHAR_OFFENSIVE,
     POS_FIGHTING,
     NULL,
     SLOT(834),
     40,
     12,
     TRUE,
     "",
     "The creeping blight fades.",
     "The creeping blight fades from $n.",
     .growth = 5},

    /* --- Utility (8) --- */
    {NORM,
     "forestsight",
     {LEVELS_INIT, L(CLASS_DRU, 7)},
     spell_forestsight,
     TAR_CHAR_SELF,
     POS_STANDING,
     NULL,
     SLOT(835),
     5,
     12,
     FALSE,
     "",
     "Your forest-attuned vision fades.",
     "",
     .growth = 1},

    {NORM,
     "sense life",
     {LEVELS_INIT, L(CLASS_DRU, 11)},
     spell_sense_life,
     TAR_CHAR_SELF,
     POS_STANDING,
     NULL,
     SLOT(836),
     5,
     12,
     FALSE,
     "",
     "Your sense of life fades.",
     "",
     .growth = 1},

    {NORM,
     "know terrain",
     {LEVELS_INIT, L(CLASS_DRU, 15)},
     spell_know_terrain,
     TAR_CHAR_DEFENSIVE,
     POS_STANDING,
     NULL,
     SLOT(837),
     8,
     12,
     FALSE,
     "",
     "!Know Terrain!",
     "",
     .growth = 1},

    {NORM,
     "passage",
     {LEVELS_INIT, L(CLASS_DRU, 24)},
     spell_passage,
     TAR_CHAR_SELF,
     POS_STANDING,
     NULL,
     SLOT(838),
     12,
     12,
     FALSE,
     "",
     "You feel solid again.",
     "$n looks solid again.",
     .growth = 2},

    {NORM,
     "greensight",
     {LEVELS_INIT, L(CLASS_DRU, 42)},
     spell_greensight,
     TAR_CHAR_SELF,
     POS_STANDING,
     NULL,
     SLOT(839),
     15,
     12,
     FALSE,
     "",
     "Your verdant vision fades.",
     "",
     .growth = 2},

    {NORM,
     "rootway",
     {LEVELS_INIT, L(CLASS_DRU, 58)},
     spell_rootway,
     TAR_CHAR_SELF,
     POS_STANDING,
     NULL,
     SLOT(840),
     30,
     12,
     FALSE,
     "",
     "!Rootway!",
     "",
     .growth = 3},

    {NORM,
     "call of the wild",
     {LEVELS_INIT, L(CLASS_DRU, 72)},
     spell_call_of_the_wild,
     TAR_IGNORE,
     POS_STANDING,
     NULL,
     SLOT(841),
     40,
     12,
     FALSE,
     "",
     "!Call of the Wild!",
     "",
     .growth = 3},

    {NORM,
     "living bridge",
     {LEVELS_INIT, L(CLASS_DRU, 90)},
     spell_living_bridge,
     TAR_IGNORE,
     POS_STANDING,
     NULL,
     SLOT(842),
     60,
     18,
     FALSE,
     "",
     "!Living Bridge!",
     "",
     .growth = 3},

    /* ================================================================
     * Level 1 active spells for mortal classes
     * ================================================================ */

    {NORM,
     "ember spark",
     {LEVELS_INIT, L(CLASS_MAG, 1)},
     spell_ember_spark,
     TAR_CHAR_OFFENSIVE,
     POS_FIGHTING,
     NULL,
     SLOT(843),
     8,
     12,
     FALSE,
     "ember spark",
     "!Ember Spark!",
     ""},

    {NORM,
     "solar brand",
     {LEVELS_INIT, L(CLASS_CLE, 1)},
     spell_solar_brand,
     TAR_CHAR_OFFENSIVE,
     POS_FIGHTING,
     NULL,
     SLOT(844),
     8,
     12,
     FALSE,
     "solar brand",
     "!Solar Brand!",
     ""},

    {NORM,
     "cognitive pressure",
     {LEVELS_INIT, L(CLASS_PSI, 1)},
     spell_cognitive_pressure,
     TAR_CHAR_OFFENSIVE,
     POS_FIGHTING,
     NULL,
     SLOT(845),
     8,
     12,
     FALSE,
     "cognitive pressure",
     "!Cognitive Pressure!",
     ""},

    {NORM,
     "root touch",
     {LEVELS_INIT, L(CLASS_DRU, 1)},
     spell_root_touch,
     TAR_CHAR_OFFENSIVE,
     POS_FIGHTING,
     NULL,
     SLOT(846),
     0,
     12,
     FALSE,
     "root touch",
     "!Root Touch!",
     "",
     .growth = 3},
