
/*
 * Magic spells.
 */

{NORM, "reserved", {LEVELS_INIT}, 0, TAR_IGNORE, POS_STANDING, NULL, SLOT(0), 0, 0, FALSE, "",
 "",   ""},

    {NORM,
     "acid blast",
     {LEVELS_INIT, L(CLASS_MAG, 50)},
     spell_acid_blast,
     TAR_CHAR_OFFENSIVE,
     POS_FIGHTING,
     NULL,
     SLOT(70),
     20,
     12,
     TRUE,
     "acid blast",
     "!Acid Blast!",
     ""},

    {NORM,
     "armor",
     {LEVELS_INIT, L(CLASS_MAG, 3)},
     spell_armor,
     TAR_CHAR_DEFENSIVE,
     POS_STANDING,
     NULL,
     SLOT(1),
     5,
     12,
     FALSE,
     "",
     "You feel less protected.",
     ""},

    {NORM,
     "animate",
     {LEVELS_INIT},
     spell_animate,
     TAR_IGNORE,
     POS_STANDING,
     NULL,
     SLOT(525),
     50,
     24,
     FALSE,
     "",
     "!Animate!",
     ""},

    {NORM,
     "revenant",
     {LEVELS_INIT, L(CLASS_NEC, 70)},
     spell_revenant,
     TAR_IGNORE,
     POS_STANDING,
     NULL,
     SLOT(755),
     75,
     24,
     FALSE,
     "",
     "!Revenant!",
     ""},

    {NORM,
     "bad breath",
     {LEVELS_INIT},
     spell_badbreath,
     TAR_CHAR_OFFENSIVE,
     POS_FIGHTING,
     NULL,
     SLOT(502),
     10,
     12,
     TRUE,
     "bad breath",
     "!Bad Breath!",
     ""},

    {NORM,
     "bark skin",
     {LEVELS_INIT},
     spell_bark_skin,
     TAR_CHAR_SELF,
     POS_STANDING,
     NULL,
     SLOT(514),
     20,
     24,
     FALSE,
     "",
     "Your skin feels softer.",
     "$n's skin looks less wooden."},

    {NORM,
     "bless",
     {LEVELS_INIT, L(CLASS_CLE, 8)},
     spell_bless,
     TAR_CHAR_DEFENSIVE,
     POS_STANDING,
     NULL,
     SLOT(3),
     5,
     12,
     FALSE,
     "",
     "You feel less righteous.",
     "$n looks less Holy."},

    {NORM,
     "blindness",
     {LEVELS_INIT, L(CLASS_MAG, 16)},
     spell_blindness,
     TAR_CHAR_OFFENSIVE,
     POS_FIGHTING,
     &gsn_blindness,
     SLOT(4),
     5,
     12,
     TRUE,
     "",
     "You can see again.",
     "$n's vision returns."},

    {NORM,
     "bloody tears",
     {LEVELS_INIT, L(CLASS_PSI, 26)},
     spell_bloody_tears,
     TAR_CHAR_OFFENSIVE,
     POS_FIGHTING,
     NULL,
     SLOT(518),
     12,
     12,
     TRUE,
     "Bloody Tears",
     "!Bloody Tears!",
     ""},

    {NORM,
     "burning hands",
     {LEVELS_INIT, L(CLASS_MAG, 6)},
     spell_burning_hands,
     TAR_CHAR_OFFENSIVE,
     POS_FIGHTING,
     NULL,
     SLOT(5),
     15,
     12,
     TRUE,
     "burning hands",
     "!Burning Hands!",
     ""},

    {NORM,
     "call lightning",
     {LEVELS_INIT, L(CLASS_CLE, 36)},
     spell_call_lightning,
     TAR_IGNORE,
     POS_FIGHTING,
     NULL,
     SLOT(6),
     15,
     12,
     TRUE,
     "lightning bolt",
     "!Call Lightning!",
     ""},

    {NORM,       "calm",     {LEVELS_INIT, L(CLASS_PSI, 52)},
     spell_calm, TAR_IGNORE, POS_FIGHTING,
     NULL,       SLOT(531),  30,
     24,         FALSE,      "",
     "!Calm!",   ""},

    {NORM,
     "cause critical",
     {LEVELS_INIT, L(CLASS_CLE, 58)},
     spell_cause_critical,
     TAR_CHAR_OFFENSIVE,
     POS_FIGHTING,
     NULL,
     SLOT(63),
     20,
     12,
     TRUE,
     "spell",
     "!Cause Critical!",
     ""},

    {NORM,
     "cause light",
     {LEVELS_INIT},
     spell_cause_light,
     TAR_CHAR_OFFENSIVE,
     POS_FIGHTING,
     NULL,
     SLOT(62),
     15,
     12,
     TRUE,
     "spell",
     "!Cause Light!",
     ""},

    {NORM,
     "cause serious",
     {LEVELS_INIT, L(CLASS_CLE, 40)},
     spell_cause_serious,
     TAR_CHAR_OFFENSIVE,
     POS_FIGHTING,
     NULL,
     SLOT(64),
     17,
     12,
     TRUE,
     "spell",
     "!Cause Serious!",
     ""},

    {NORM,
     "change sex",
     {LEVELS_INIT},
     spell_change_sex,
     TAR_CHAR_DEFENSIVE,
     POS_FIGHTING,
     NULL,
     SLOT(82),
     15,
     12,
     FALSE,
     "",
     "Your body feels familiar again.",
     "$n looks $mself again."},

    {NORM,
     "charm person",
     {LEVELS_INIT},
     spell_charm_person,
     TAR_CHAR_OFFENSIVE,
     POS_STANDING,
     &gsn_charm_person,
     SLOT(7),
     5,
     12,
     FALSE,
     "",
     "You feel more self-confident.",
     "The glazed look in $n's eyes fades."},

    {NORM,
     "chill touch",
     {LEVELS_INIT, L(CLASS_MAG, 8)},
     spell_chill_touch,
     TAR_CHAR_OFFENSIVE,
     POS_FIGHTING,
     NULL,
     SLOT(8),
     15,
     12,
     TRUE,
     "chilling touch",
     "You feel less cold.",
     ""},

    {NORM,
     "color spray",
     {LEVELS_INIT, L(CLASS_MAG, 7)},
     spell_color_spray,
     TAR_CHAR_OFFENSIVE,
     POS_FIGHTING,
     NULL,
     SLOT(10),
     15,
     12,
     TRUE,
     "color spray",
     "!color Spray!",
     ""},

    {NORM,
     "continual light",
     {LEVELS_INIT, L(CLASS_MAG, 11), L(CLASS_CLE, 27)},
     spell_continual_light,
     TAR_IGNORE,
     POS_STANDING,
     NULL,
     SLOT(57),
     7,
     12,
     FALSE,
     "",
     "!Continual Light!",
     ""},

    {NORM,
     "control weather",
     {LEVELS_INIT, L(CLASS_CLE, 79)},
     spell_control_weather,
     TAR_IGNORE,
     POS_STANDING,
     NULL,
     SLOT(11),
     25,
     12,
     FALSE,
     "",
     "!Control Weather!",
     ""},

    {NORM,
     "cure blindness",
     {LEVELS_INIT, L(CLASS_CLE, 28)},
     spell_cure_blindness,
     TAR_CHAR_DEFENSIVE,
     POS_FIGHTING,
     NULL,
     SLOT(14),
     5,
     12,
     FALSE,
     "",
     "!Cure Blindness!",
     ""},

    {NORM,
     "cure critical",
     {LEVELS_INIT},
     spell_cure_critical,
     TAR_CHAR_DEFENSIVE,
     POS_FIGHTING,
     NULL,
     SLOT(15),
     20,
     12,
     FALSE,
     "",
     "!Cure Critical!",
     ""},

    {NORM,
     "cure light",
     {LEVELS_INIT},
     spell_cure_light,
     TAR_CHAR_DEFENSIVE,
     POS_FIGHTING,
     NULL,
     SLOT(16),
     10,
     12,
     FALSE,
     "",
     "!Cure Light!",
     ""},

    {NORM,
     "cure poison",
     {LEVELS_INIT, L(CLASS_CLE, 32)},
     spell_cure_poison,
     TAR_CHAR_DEFENSIVE,
     POS_FIGHTING,
     NULL,
     SLOT(43),
     5,
     12,
     FALSE,
     "",
     "!Cure Poison!",
     ""},

    {NORM,
     "purify",
     {LEVELS_INIT, L(CLASS_PSI, 19)},
     spell_purify,
     TAR_CHAR_SELF,
     POS_FIGHTING,
     NULL,
     SLOT(231),
     5,
     12,
     FALSE,
     "Purify",
     "!Purify!",
     ""},

    {NORM,
     "cure serious",
     {LEVELS_INIT},
     spell_cure_serious,
     TAR_CHAR_DEFENSIVE,
     POS_FIGHTING,
     NULL,
     SLOT(61),
     15,
     12,
     TRUE,
     "",
     "!Cure Serious!",
     ""},

    {NORM,
     "curse",
     {LEVELS_INIT, L(CLASS_MAG, 35), L(CLASS_CLE, 26)},
     spell_curse,
     TAR_CHAR_OFFENSIVE,
     POS_FIGHTING,
     &gsn_curse,
     SLOT(17),
     20,
     12,
     FALSE,
     "curse",
     "The curse wears off.",
     "$n starts to look more Holy."},

    {NORM,
     "detect evil",
     {LEVELS_INIT, L(CLASS_MAG, 12), L(CLASS_CLE, 8)},
     spell_detect_evil,
     TAR_CHAR_SELF,
     POS_STANDING,
     NULL,
     SLOT(18),
     5,
     12,
     FALSE,
     "",
     "The red in your vision disappears.",
     ""},

    {NORM,
     "detect hidden",
     {LEVELS_INIT, L(CLASS_MAG, 17), L(CLASS_CLE, 16)},
     spell_detect_hidden,
     TAR_CHAR_SELF,
     POS_STANDING,
     NULL,
     SLOT(44),
     5,
     12,
     FALSE,
     "",
     "You feel less aware of your suroundings.",
     ""},

    {NORM,
     "detect invis",
     {LEVELS_INIT, L(CLASS_MAG, 19)},
     spell_detect_invis,
     TAR_CHAR_SELF,
     POS_STANDING,
     NULL,
     SLOT(19),
     5,
     12,
     FALSE,
     "",
     "You no longer see invisible objects.",
     ""},

    {NORM,
     "detect magic",
     {LEVELS_INIT, L(CLASS_MAG, 7), L(CLASS_CLE, 7)},
     spell_detect_magic,
     TAR_CHAR_SELF,
     POS_STANDING,
     NULL,
     SLOT(20),
     5,
     12,
     FALSE,
     "",
     "The detect magic wears off.",
     ""},

    {NORM,
     "detect poison",
     {LEVELS_INIT, L(CLASS_CLE, 10)},
     spell_detect_poison,
     TAR_OBJ_INV,
     POS_STANDING,
     NULL,
     SLOT(21),
     5,
     12,
     FALSE,
     "",
     "!Detect Poison!",
     ""},

    {NORM,
     "detect undead",
     {LEVELS_INIT, L(CLASS_MAG, 8)},
     spell_detect_undead,
     TAR_CHAR_SELF,
     POS_STANDING,
     NULL,
     SLOT(513),
     8,
     12,
     FALSE,
     "",
     "You no longer sense undead beings.",
     ""},

    {NORM,
     "detection",
     {LEVELS_INIT, L(CLASS_PSI, 22)},
     spell_detection,
     TAR_IGNORE,
     POS_STANDING,
     NULL,
     SLOT(527),
     12,
     24,
     FALSE,
     "",
     "!Detection!",
     ""},

    {NORM,
     "dimension blade",
     {LEVELS_INIT},
     spell_dimension_blade,
     TAR_OBJ_INV,
     POS_STANDING,
     NULL,
     SLOT(523),
     100,
     41,
     FALSE,
     "",
     "!Dimension Blade!",
     ""},

    {NORM,
     "dispel evil",
     {LEVELS_INIT}, /* was 82, 63, ... */
     spell_dispel_evil,
     TAR_CHAR_OFFENSIVE,
     POS_FIGHTING,
     NULL,
     SLOT(22),
     15,
     12,
     FALSE,
     "dispel evil",
     "!Dispel Evil!",
     ""},

    {NORM,
     "dispel object",
     {LEVELS_INIT, L(CLASS_MAG, 60), L(CLASS_CLE, 70), L(CLASS_PSI, 80)},
     spell_dispel_object,
     TAR_IGNORE,
     POS_FIGHTING,
     NULL,
     SLOT(0),
     15,
     12,
     FALSE,
     "",
     "!Dispel Object!",
     ""},

    {NORM,
     "dispel magic",
     {LEVELS_INIT, L(CLASS_MAG, 68), L(CLASS_CLE, 89)},
     spell_dispel_magic,
     TAR_IGNORE,
     POS_FIGHTING,
     NULL,
     SLOT(59),
     15,
     12,
     TRUE,
     "",
     "!Dispel Magic!",
     ""},

    {NORM,
     "purge",
     {LEVELS_INIT, L(CLASS_PSI, 50)},
     spell_dispel_magic,
     TAR_CHAR_NOTSELF,
     POS_FIGHTING,
     NULL,
     SLOT(0),
     15,
     12,
     TRUE,
     "",
     "!Purge!",
     ""},

    {NORM,
     "earthquake",
     {LEVELS_INIT, L(CLASS_CLE, 78)},
     spell_earthquake,
     TAR_IGNORE,
     POS_FIGHTING,
     NULL,
     SLOT(23),
     15,
     12,
     TRUE,
     "earthquake",
     "!Earthquake!",
     ""},

    {NORM,
     "ego whip",
     {LEVELS_INIT, L(CLASS_PSI, 25)},
     spell_ego_whip,
     TAR_CHAR_OFFENSIVE,
     POS_FIGHTING,
     NULL,
     SLOT(535),
     35,
     24,
     TRUE,
     "ego whip",
     "!Ego Whip!",
     ""},

    {NORM,
     "enchant weapon",
     {LEVELS_INIT, L(CLASS_MAG, 39)},
     spell_enchant_weapon,
     TAR_OBJ_INV,
     POS_STANDING,
     NULL,
     SLOT(24),
     100,
     24,
     FALSE,
     "",
     "!Enchant Weapon!",
     ""},

    {NORM,
     "energy drain",
     {LEVELS_INIT},
     spell_energy_drain,
     TAR_CHAR_OFFENSIVE,
     POS_FIGHTING,
     NULL,
     SLOT(25),
     12,
     12,
     TRUE,
     "energy drain",
     "!Energy Drain!",
     ""},

    {NORM,
     "enhance weapon",
     {LEVELS_INIT},
     spell_enhance_weapon,
     TAR_OBJ_INV,
     POS_STANDING,
     NULL,
     SLOT(517),
     50,
     24,
     FALSE,
     "",
     "!Enhance Weapon!",
     ""},

    {NORM,
     "faerie fire",
     {LEVELS_INIT, L(CLASS_MAG, 3)},
     spell_faerie_fire,
     TAR_CHAR_DEFENSIVE,
     POS_FIGHTING,
     NULL,
     SLOT(72),
     5,
     12,
     TRUE,
     "faerie fire",
     "The pink aura around you fades away.",
     "The pink aura around $n fades away."},

    {NORM,
     "faerie fog",
     {LEVELS_INIT, L(CLASS_CLE, 14)},
     spell_faerie_fog,
     TAR_IGNORE,
     POS_STANDING,
     NULL,
     SLOT(73),
     12,
     12,
     FALSE,
     "faerie fog",
     "!Faerie Fog!",
     ""},

    {NORM,
     "fighting trance",
     {LEVELS_INIT, L(CLASS_PSI, 60)},
     spell_fighting_trance,
     TAR_CHAR_SELF,
     POS_STANDING,
     NULL,
     SLOT(521),
     60,
     24,
     FALSE,
     "",
     "Your fighting trance fades.",
     "$n's fighting trance fades."},

    {NORM,
     "fireball",
     {LEVELS_INIT, L(CLASS_MAG, 28)},
     spell_fireball,
     TAR_CHAR_OFFENSIVE,
     POS_FIGHTING,
     NULL,
     SLOT(26),
     15,
     12,
     TRUE,
     "fireball",
     "!Fireball!",
     ""},

    {NORM,
     "flamestrike",
     {LEVELS_INIT, L(CLASS_CLE, 54)},
     spell_flamestrike,
     TAR_CHAR_OFFENSIVE,
     POS_FIGHTING,
     NULL,
     SLOT(65),
     20,
     12,
     TRUE,
     "flamestrike",
     "!Flamestrike!",
     ""},

    {NORM,
     "flare",
     {LEVELS_INIT},
     spell_flare,
     TAR_CHAR_OFFENSIVE,
     POS_FIGHTING,
     NULL,
     SLOT(591),
     18,
     12,
     TRUE,
     "flare",
     "Your vision returns.",
     "$n blinks, and starts to see again."},

    {NORM,
     "fly",
     {LEVELS_INIT, L(CLASS_MAG, 24)},
     spell_fly,
     TAR_CHAR_DEFENSIVE,
     POS_STANDING,
     NULL,
     SLOT(56),
     10,
     18,
     FALSE,
     "",
     "You slowly float to the ground.",
     "$n slowly floats to the ground."},

    {NORM,         "gate", {LEVELS_INIT}, spell_gate, TAR_CHAR_DEFENSIVE,
     POS_FIGHTING, NULL,   SLOT(83),      50,         12,
     FALSE,        "",     "!Gate!",      ""},

    {NORM,
     "giant strength",
     {LEVELS_INIT, L(CLASS_SOR, 18), L(CLASS_WIZ, 18)},
     spell_giant_strength,
     TAR_CHAR_DEFENSIVE,
     POS_STANDING,
     NULL,
     SLOT(39),
     20,
     12,
     FALSE,
     "",
     "You feel weaker.",
     "$n looks weaker."},

    {NORM,         "harm",       {LEVELS_INIT}, spell_harm, TAR_CHAR_OFFENSIVE,
     POS_FIGHTING, NULL,         SLOT(27),      35,         12,
     TRUE,         "harm spell", "!Harm!",      ""},

    {NORM,
     "heal",
     {LEVELS_INIT, L(CLASS_CLE, 5)},
     spell_heal,
     TAR_CHAR_DEFENSIVE,
     POS_FIGHTING,
     NULL,
     SLOT(28),
     50,
     12,
     TRUE,
     "",
     "!Heal!",
     ""},

    {NORM,
     "group heal",
     {LEVELS_INIT, L(CLASS_PAL, 5), L(CLASS_PRI, 25)},
     spell_group_heal,
     TAR_CHAR_DEFENSIVE,
     POS_FIGHTING,
     NULL,
     SLOT(169),
     50,
     12,
     TRUE,
     "",
     "!Group Heal!",
     ""},

    {NORM,
     "hypnosis",
     {LEVELS_INIT, L(CLASS_PSI, 14)},
     spell_hypnosis,
     TAR_CHAR_OFFENSIVE,
     POS_STANDING,
     NULL,
     SLOT(532),
     30,
     24,
     FALSE,
     "",
     "!Hypnosis!",
     ""},

    {NORM,
     "identify",
     {LEVELS_INIT, L(CLASS_MAG, 9)},
     spell_identify,
     TAR_OBJ_INV,
     POS_STANDING,
     NULL,
     SLOT(53),
     12,
     24,
     FALSE,
     "",
     "!Identify!",
     ""},

    {NORM,
     "infravision",
     {LEVELS_INIT, L(CLASS_MAG, 20)},
     spell_infravision,
     TAR_CHAR_DEFENSIVE,
     POS_STANDING,
     NULL,
     SLOT(77),
     5,
     18,
     FALSE,
     "",
     "You no longer see in the dark.",
     ""},

    {NORM,
     "influx",
     {LEVELS_INIT, L(CLASS_CLE, 65)},
     spell_influx,
     TAR_CHAR_DEFENSIVE,
     POS_FIGHTING,
     NULL,
     SLOT(503),
     75,
     24,
     TRUE,
     "",
     "!Influx!",
     ""},

    {NORM,
     "invis",
     {LEVELS_INIT, L(CLASS_MAG, 17)},
     spell_invis,
     TAR_IGNORE,
     POS_STANDING,
     &gsn_invis,
     SLOT(29),
     5,
     12,
     FALSE,
     "",
     "You are no longer invisible.",
     "$n's invisibilty fades."},

    {NORM,
     "know alignment",
     {LEVELS_INIT, L(CLASS_MAG, 13), L(CLASS_CLE, 22)},
     spell_know_alignment,
     TAR_CHAR_DEFENSIVE,
     POS_FIGHTING,
     NULL,
     SLOT(58),
     9,
     12,
     FALSE,
     "",
     "!Know Alignment!",
     ""},

    {NORM,
     "know weakness",
     {LEVELS_INIT, L(CLASS_PSI, 18)},
     spell_know_weakness,
     TAR_CHAR_SELF,
     POS_STANDING,
     NULL,
     SLOT(530),
     15,
     12,
     FALSE,
     "",
     "You are less aware of your enemy's weaknesses.",
     ""},

    {NORM,
     "know critical",
     {LEVELS_INIT, L(CLASS_PSI, 28)},
     spell_know_weakness,
     TAR_CHAR_SELF,
     POS_STANDING,
     NULL,
     SLOT(530),
     15,
     12,
     FALSE,
     "",
     "You are less aware of critical damage points.",
     ""},

    {NORM,
     "know item",
     {LEVELS_INIT, L(CLASS_PSI, 9)},
     spell_identify,
     TAR_OBJ_INV,
     POS_STANDING,
     NULL,
     SLOT(533),
     20,
     24,
     FALSE,
     "",
     "!Know Item!",
     ""},

    {NORM,
     "laser bolt",
     {LEVELS_INIT},
     spell_laserbolt,
     TAR_CHAR_OFFENSIVE,
     POS_FIGHTING,
     NULL,
     SLOT(511),
     35,
     12,
     FALSE,
     "laserbolt",
     "!laserbolt!",
     ""},

    {NORM,
     "lightning bolt",
     {LEVELS_INIT, L(CLASS_MAG, 24)},
     spell_lightning_bolt,
     TAR_CHAR_OFFENSIVE,
     POS_FIGHTING,
     NULL,
     SLOT(30),
     15,
     12,
     TRUE,
     "lightning bolt",
     "!Lightning Bolt!",
     ""},

    {NORM,
     "locate object",
     {LEVELS_INIT, L(CLASS_MAG, 16), L(CLASS_CLE, 30)},
     spell_locate_object,
     TAR_IGNORE,
     POS_STANDING,
     NULL,
     SLOT(31),
     20,
     18,
     FALSE,
     "",
     "!Locate Object!",
     ""},

    {NORM,
     "magic missile",
     {LEVELS_INIT, L(CLASS_MAG, 3)},
     spell_magic_missile,
     TAR_CHAR_OFFENSIVE,
     POS_FIGHTING,
     NULL,
     SLOT(32),
     15,
     12,
     TRUE,
     "magic missile",
     "!Magic Missile!",
     ""},

    {NORM,
     "mass invis",
     {LEVELS_INIT, L(CLASS_MAG, 60)},
     spell_mass_invis,
     TAR_IGNORE,
     POS_STANDING,
     &gsn_mass_invis,
     SLOT(69),
     20,
     24,
     FALSE,
     "",
     "!Mass Invis!",
     ""},

    {NORM,
     "mind flail",
     {LEVELS_INIT, L(CLASS_PSI, 4)},
     spell_mind_flail,
     TAR_CHAR_OFFENSIVE,
     POS_FIGHTING,
     NULL,
     SLOT(536),
     12,
     24,
     TRUE,
     "mind flail",
     "!Mind Flail!",
     ""},

    {NORM,
     "mystic armour",
     {LEVELS_INIT, L(CLASS_MAG, 10)},
     spell_mystic_armor,
     TAR_CHAR_DEFENSIVE,
     POS_STANDING,
     NULL,
     SLOT(590),
     18,
     24,
     FALSE,
     ""
     "Your Mystic Armour fades away",
     "The Mystic Armour around someone in the room fades away."},

    {NORM,
     "nerve fire",
     {LEVELS_INIT, L(CLASS_PSI, 60)},
     spell_nerve_fire,
     TAR_IGNORE,
     POS_FIGHTING,
     NULL,
     SLOT(520),
     50,
     24,
     TRUE,
     "nerve fire",
     "!Nerve Fire!",
     ""},

    {NORM,
     "night vision",
     {LEVELS_INIT, L(CLASS_PSI, 19)},
     spell_night_vision,
     TAR_CHAR_SELF,
     POS_STANDING,
     NULL,
     SLOT(538),
     17,
     24,
     FALSE,
     "",
     "Your eyes feel weaker.",
     ""},

    {NORM,
     "pass door",
     {LEVELS_INIT, L(CLASS_MAG, 46)},
     spell_pass_door,
     TAR_CHAR_SELF,
     POS_STANDING,
     NULL,
     SLOT(74),
     20,
     12,
     FALSE,
     "",
     "You feel solid again.",
     "$n's body becomes more solid."},

    {NORM,
     "phase",
     {LEVELS_INIT, L(CLASS_PSI, 45)},
     spell_phase,
     TAR_CHAR_SELF,
     POS_STANDING,
     NULL,
     SLOT(522),
     20,
     12,
     FALSE,
     "",
     "You feel solid again.",
     "$n's body becomes more solid."},

    {NORM,
     "psychic crush",
     {LEVELS_INIT, L(CLASS_PSI, 19)},
     spell_physic_thrust,
     TAR_CHAR_OFFENSIVE,
     POS_FIGHTING,
     NULL,
     SLOT(537),
     33,
     24,
     TRUE,
     "psychic crush",
     "!Psychic Crush!",
     ""},

    {NORM,
     "psychic thrust",
     {LEVELS_INIT, L(CLASS_PSI, 7)},
     spell_physic_thrust,
     TAR_CHAR_OFFENSIVE,
     POS_FIGHTING,
     NULL,
     SLOT(537),
     22,
     24,
     TRUE,
     "psychic thrust",
     "!Physic Thrust!",
     ""},

    {NORM,
     "poison",
     {LEVELS_INIT},
     spell_poison,
     TAR_CHAR_OFFENSIVE,
     POS_STANDING,
     &gsn_poison,
     SLOT(33),
     10,
     12,
     FALSE,
     "poison",
     "You feel less sick.",
     "$n looks less sick."},

    {NORM,
     "protection",
     {LEVELS_INIT, L(CLASS_MAG, 9), L(CLASS_CLE, 12)},
     spell_protection,
     TAR_CHAR_SELF,
     POS_STANDING,
     NULL,
     SLOT(34),
     5,
     12,
     FALSE,
     "",
     "You feel less protected.",
     ""},

    {NORM,
     "psionic recovery",
     {LEVELS_INIT, L(CLASS_PSI, 5)},
     spell_psionic_recovery,
     TAR_CHAR_SELF,
     POS_FIGHTING,
     NULL,
     SLOT(78),
     5,
     12,
     TRUE,
     "",
     "You feel less protected.",
     ""},

    {NORM,
     "refresh",
     {LEVELS_INIT, L(CLASS_CLE, 11)},
     spell_refresh,
     TAR_CHAR_DEFENSIVE,
     POS_STANDING,
     NULL,
     SLOT(81),
     12,
     18,
     FALSE,
     "refresh",
     "!Refresh!",
     ""},

    {NORM,
     "refresh mana",
     {LEVELS_INIT},
     spell_refresh_mana,
     TAR_CHAR_DEFENSIVE,
     POS_STANDING,
     NULL,
     SLOT(81),
     12,
     18,
     FALSE,
     "refresh mana",
     "!Refresh mana!",
     ""},

    {NORM,
     "regen",
     {LEVELS_INIT},
     spell_regen,
     TAR_CHAR_DEFENSIVE,
     POS_FIGHTING,
     NULL,
     SLOT(271),
     12,
     18,
     TRUE,
     "",
     "You are no longer regenerating quickly.",
     "$n is no longer regenerating quickly."},

    {NORM,
     "haste",
     {LEVELS_INIT, L(CLASS_WIZ, 84)},
     spell_haste,
     TAR_CHAR_DEFENSIVE,
     POS_FIGHTING,
     NULL,
     SLOT(271),
     12,
     18,
     TRUE,
     "",
     "You are no longer moving quickly.",
     "$n is no longer moving quickly."},

    {NORM,
     "overdrive",
     {LEVELS_INIT, L(CLASS_EGO, 57)},
     spell_overdrive,
     TAR_CHAR_SELF,
     POS_FIGHTING,
     NULL,
     SLOT(271),
     12,
     18,
     TRUE,
     "",
     "You are no longer acting quickly.",
     "$n is no longer acting quickly."},

    {NORM,
     "magical supremacy",
     {LEVELS_INIT, L(CLASS_WIZ, 42), L(CLASS_EGO, 13)},
     spell_magical_supremacy,
     TAR_CHAR_SELF,
     POS_FIGHTING,
     NULL,
     SLOT(271),
     12,
     18,
     TRUE,
     "",
     "You no longer have magical supremacy.",
     "$n no longer has magical supremacy."},

    {NORM,
     "slow",
     {LEVELS_INIT, L(CLASS_WIZ, 92)},
     spell_slow,
     TAR_CHAR_OFFENSIVE,
     POS_FIGHTING,
     NULL,
     SLOT(271),
     12,
     18,
     TRUE,
     "",
     "You are no longer acting slowly.",
     "$n is no longer acting slowly."},

    {NORM,
     "feeble mind",
     {LEVELS_INIT, L(CLASS_NEC, 45)},
     spell_feeble_mind,
     TAR_CHAR_OFFENSIVE,
     POS_FIGHTING,
     NULL,
     SLOT(271),
     12,
     18,
     TRUE,
     "",
     "You are now thinking quickly.",
     "$n is now thinking quickly."},

    {NORM,
     "feeble body",
     {LEVELS_INIT, L(CLASS_NEC, 45)},
     spell_feeble_body,
     TAR_CHAR_OFFENSIVE,
     POS_FIGHTING,
     NULL,
     SLOT(271),
     12,
     18,
     TRUE,
     "",
     "You are now moving quickly.",
     "$n is now moving quickly."},

    {NORM,
     "remove curse",
     {LEVELS_INIT, L(CLASS_MAG, 36), L(CLASS_CLE, 27)},
     spell_remove_curse,
     TAR_CHAR_DEFENSIVE,
     POS_STANDING,
     NULL,
     SLOT(35),
     5,
     12,
     FALSE,
     "",
     "!Remove Curse!",
     ""},

    {NORM,
     "sanctuary",
     {LEVELS_INIT, L(CLASS_CLE, 70)},
     spell_sanctuary,
     TAR_CHAR_DEFENSIVE,
     POS_STANDING,
     NULL,
     SLOT(36),
     75,
     12,
     FALSE,
     "",
     "The white aura around your body fades.",
     "The white aura around $n's body fades."},

    {NORM,
     "refuge",
     {LEVELS_INIT, L(CLASS_PAL, 32), L(CLASS_PRI, 32)},
     spell_refuge,
     TAR_CHAR_DEFENSIVE,
     POS_STANDING,
     NULL,
     SLOT(0),
     75,
     12,
     TRUE,
     "",
     "The rainbow aura around your body fades.",
     "The rainbow aura around $n's body fades."},

    {NORM,
     "seal room",
     {LEVELS_INIT, L(CLASS_MAG, 70), L(CLASS_CLE, 50)},
     spell_seal_room,
     TAR_IGNORE,
     POS_STANDING,
     NULL,
     SLOT(541),
     75,
     12,
     FALSE,
     "",
     "The Energy web around this room fades.",
     ""},

    {NORM,
     "see magic",
     {LEVELS_INIT, L(CLASS_PSI, 7)},
     spell_see_magic,
     TAR_CHAR_SELF,
     POS_STANDING,
     NULL,
     SLOT(526),
     8,
     12,
     FALSE,
     "",
     "You no longer see magical auras.",
     ""},

    {NORM,
     "sense evil",
     {LEVELS_INIT, L(CLASS_PSI, 10)},
     spell_sense_evil,
     TAR_CHAR_SELF,
     POS_STANDING,
     NULL,
     SLOT(515),
     12,
     12,
     FALSE,
     "",
     "You no longer sense evil.",
     ""},

    {NORM,
     "shield",
     {LEVELS_INIT, L(CLASS_MAG, 9)},
     spell_shield,
     TAR_CHAR_DEFENSIVE,
     POS_STANDING,
     NULL,
     SLOT(67),
     12,
     18,
     FALSE,
     "",
     "Your force shield shimmers, then fades away.",
     "$n's force field shimmers, then fades away."},

    {NORM,
     "shocking grasp",
     {LEVELS_INIT, L(CLASS_MAG, 5)},
     spell_shocking_grasp,
     TAR_CHAR_OFFENSIVE,
     POS_FIGHTING,
     NULL,
     SLOT(82),
     15,
     12,
     TRUE,
     "shocking grasp",
     "!Shocking Grasp!",
     ""},

    {NORM,
     "sight",
     {LEVELS_INIT, L(CLASS_MAG, 30)},
     spell_cure_blindness,
     TAR_CHAR_DEFENSIVE,
     POS_STANDING,
     NULL,
     SLOT(592),
     20,
     24,
     FALSE,
     "",
     "!Sight!",
     ""},

    {NORM,
     "sleep",
     {LEVELS_INIT},
     spell_sleep,
     TAR_CHAR_OFFENSIVE,
     POS_STANDING,
     &gsn_sleep,
     SLOT(38),
     15,
     12,
     FALSE,
     "",
     "You feel less tired.",
     "$n starts looking much more awake."},

    {NORM,          "stalker",
     {LEVELS_INIT}, spell_stalker,
     TAR_IGNORE,    POS_STANDING,
     NULL,          SLOT(401),
     100,           24,
     FALSE,         "",
     "!Stalker!",   ""},

    {NORM,
     "stone skin",
     {LEVELS_INIT, L(CLASS_MAG, 36)},
     spell_stone_skin,
     TAR_CHAR_SELF,
     POS_STANDING,
     NULL,
     SLOT(66),
     12,
     18,
     TRUE,
     "",
     "Your skin feels soft again.",
     "$n's skin loses it's stone-like look."},

    {NORM,
     "suffocate",
     {LEVELS_INIT, L(CLASS_PSI, 46)},
     spell_suffocate,
     TAR_CHAR_OFFENSIVE,
     POS_FIGHTING,
     NULL,
     SLOT(516),
     30,
     24,
     TRUE,
     "a choking hand",
     "!Suffocate!",
     ""},

    {NORM,         "summon",   {LEVELS_INIT, L(CLASS_MAG, 35)},
     spell_summon, TAR_IGNORE, POS_STANDING,
     NULL,         SLOT(40),   50,
     12,           FALSE,      "",
     "!Summon!",   ""},

    {NORM,
     "teleport",
     {LEVELS_INIT, L(CLASS_MAG, 40)},
     spell_teleport,
     TAR_CHAR_SELF,
     POS_FIGHTING,
     NULL,
     SLOT(2),
     35,
     12,
     FALSE,
     "",
     "!Teleport!",
     ""},

    {NORM,
     "travel",
     {LEVELS_INIT},
     spell_travel,
     TAR_CHAR_SELF,
     POS_STANDING,
     NULL,
     SLOT(599),
     50,
     24,
     FALSE,
     "",
     "!Travel!",
     ""},

    {NORM,
     "ventriloquate",
     {LEVELS_INIT, L(CLASS_MAG, 3)},
     spell_ventriloquate,
     TAR_IGNORE,
     POS_STANDING,
     NULL,
     SLOT(41),
     5,
     12,
     FALSE,
     "",
     "!Ventriloquate!",
     ""},

    {NORM,
     "weaken",
     {LEVELS_INIT},
     spell_weaken,
     TAR_CHAR_OFFENSIVE,
     POS_FIGHTING,
     NULL,
     SLOT(68),
     20,
     12,
     FALSE,
     "spell",
     "You feel stronger.",
     "$n looks stronger."},

    {NORM,         "beacon",   {LEVELS_INIT, L(CLASS_MAG, 70)},
     spell_beacon, TAR_IGNORE, POS_STANDING,
     NULL,         SLOT(399),  25,
     12,           FALSE,      "",
     "!Beacon!",   ""},

    {NORM,         "portal",   {LEVELS_INIT, L(CLASS_MAG, 80)},
     spell_portal, TAR_IGNORE, POS_FIGHTING,
     NULL,         SLOT(334),  100,
     12,           FALSE,      "",
     "!Portal!",   ""},

    {NORM,         "window",   {LEVELS_INIT, L(CLASS_MAG, 70)},
     spell_window, TAR_IGNORE, POS_STANDING,
     NULL,         SLOT(333),  100,
     12,           FALSE,      "",
     "!Window!",   ""},

    {NORM,
     "word of recall",
     {LEVELS_INIT, L(CLASS_CLE, 66)},
     spell_word_of_recall,
     TAR_CHAR_SELF,
     POS_RESTING,
     NULL,
     SLOT(42),
     5,
     12,
     FALSE,
     "",
     "!Word of Recall!",
     ""},

    {NORM,
     "hellspawn",
     {LEVELS_INIT},
     spell_hellspawn,
     TAR_CHAR_OFFENSIVE,
     POS_FIGHTING,
     NULL,
     SLOT(512),
     50,
     12,
     TRUE,
     "HellSpawn",
     "!Hellspawn!",
     ""},

    {NORM,
     "planergy",
     {LEVELS_INIT, L(CLASS_PSI, 5)},
     spell_planergy,
     TAR_CHAR_OFFENSIVE,
     POS_FIGHTING,
     NULL,
     SLOT(504),
     25,
     24,
     TRUE,
     "energy",
     "!planergy!",
     ""},

    {NORM,        "visit",    {LEVELS_INIT, L(CLASS_PSI, 32)},
     spell_visit, TAR_IGNORE, POS_STANDING,
     NULL,        SLOT(505),  50,
     48,          FALSE,      "",
     "!visit!",   ""},

    {NORM,
     "barrier",
     {LEVELS_INIT, L(CLASS_PSI, 8)},
     spell_barrier,
     TAR_CHAR_SELF,
     POS_STANDING,
     NULL,
     SLOT(506),
     30,
     24,
     FALSE,
     "",
     "Your barrier slowly fades.",
     "The barrier around $n fades."},

    {NORM,
     "phobia",
     {LEVELS_INIT, L(CLASS_PSI, 10)},
     spell_phobia,
     TAR_CHAR_OFFENSIVE,
     POS_FIGHTING,
     NULL,
     SLOT(507),
     32,
     24,
     FALSE,
     "phobia attack",
     "!phobia!",
     ""},

    {NORM,
     "mind bolt",
     {LEVELS_INIT, L(CLASS_PSI, 12)},
     spell_mind_bolt,
     TAR_CHAR_OFFENSIVE,
     POS_FIGHTING,
     NULL,
     SLOT(519),
     40,
     12,
     TRUE,
     "Mind Bolt",
     "!MindBolt!",
     ""},

    {NORM,
     "mindflame",
     {LEVELS_INIT, L(CLASS_PSI, 35)},
     spell_mindflame,
     TAR_IGNORE,
     POS_FIGHTING,
     NULL,
     SLOT(508),
     40,
     24,
     TRUE,
     "Mind Flame",
     "!mindflame!",
     ""},

    {NORM,
     "chain lightning",
     {LEVELS_INIT, L(CLASS_MAG, 65)},
     spell_chain_lightning,
     TAR_IGNORE,
     POS_FIGHTING,
     NULL,
     SLOT(509),
     25,
     24,
     TRUE,
     "lightening bolt",
     "!chain-light!",
     ""},

    {NORM,
     "static",
     {LEVELS_INIT},
     spell_static,
     TAR_CHAR_OFFENSIVE,
     POS_FIGHTING,
     NULL,
     SLOT(510),
     40,
     24,
     TRUE,
     "discharge",
     "!static!",
     ""},

    {NORM,
     "cloak:absorption",
     {LEVELS_INIT},
     spell_cloak_absorb,
     TAR_CHAR_DEFENSIVE,
     POS_STANDING,
     NULL,
     SLOT(221),
     500,
     12,
     FALSE,
     "",
     "@@NThe @@lcloak@@N around your body fades.",
     "@@NThe @@lcloak@@N around $n's body fades."},

    {NORM,
     "cloak:reflection",
     {LEVELS_INIT},
     spell_cloak_reflect,
     TAR_CHAR_DEFENSIVE,
     POS_STANDING,
     NULL,
     SLOT(222),
     500,
     12,
     FALSE,
     "",
     "@@NThe @@lc@@el@@ro@@ya@@ak@@N around your body fades.",
     "@@NThe @@lc@@el@@ro@@ya@@ak@@N around $n's body fades."},

    {NORM,
     "cloak:flaming",
     {LEVELS_INIT, L(CLASS_SOR, 48)},
     spell_cloak_flaming,
     TAR_CHAR_DEFENSIVE,
     POS_STANDING,
     NULL,
     SLOT(223),
     750,
     12,
     FALSE,
     "",
     "@@NThe @@ecloak@@N around your body fades.",
     "@@NThe @@ecloak@@N around $n's body fades."},

    {NORM,
     "cloak:elements",
     {LEVELS_INIT, L(CLASS_WIZ, 48)},
     spell_cloak_elements,
     TAR_CHAR_DEFENSIVE,
     POS_STANDING,
     NULL,
     SLOT(225),
     750,
     12,
     FALSE,
     "",
     "@@NThe @@lcloak@@N around your body fades.",
     "@@NThe @@lcloak@@N around $n's body fades."},

    {NORM,
     "cloak:adept",
     {LEVELS_INIT},
     spell_cloak_adept,
     TAR_CHAR_DEFENSIVE,
     POS_STANDING,
     NULL,
     SLOT(226),
     500,
     12,
     FALSE,
     "",
     "@@NThe @@Wcloak@@N around your body fades.",
     "@@NThe @@Wcloak@@N around $n's body fades."},

    {NORM,
     "acid breath",
     {LEVELS_INIT},
     spell_acid_breath,
     TAR_CHAR_OFFENSIVE,
     POS_FIGHTING,
     NULL,
     SLOT(200),
     0,
     4,
     FALSE,
     "blast of acid",
     "!Acid Breath!",
     ""},

    {NORM,
     "fire breath",
     {LEVELS_INIT},
     spell_fire_breath,
     TAR_CHAR_OFFENSIVE,
     POS_FIGHTING,
     NULL,
     SLOT(201),
     0,
     4,
     FALSE,
     "blast of flame",
     "!Fire Breath!",
     ""},

    {NORM,
     "frost breath",
     {LEVELS_INIT},
     spell_frost_breath,
     TAR_CHAR_OFFENSIVE,
     POS_FIGHTING,
     NULL,
     SLOT(202),
     0,
     4,
     FALSE,
     "blast of frost",
     "!Frost Breath!",
     ""},

    {NORM,
     "gas breath",
     {LEVELS_INIT},
     spell_gas_breath,
     TAR_IGNORE,
     POS_FIGHTING,
     NULL,
     SLOT(203),
     0,
     4,
     FALSE,
     "blast of gas",
     "!Gas Breath!",
     ""},

    {NORM,
     "lightning breath",
     {LEVELS_INIT},
     spell_lightning_breath,
     TAR_CHAR_OFFENSIVE,
     POS_FIGHTING,
     NULL,
     SLOT(204),
     0,
     4,
     FALSE,
     "blast of lightning",
     "!Lightning Breath!",
     ""},

    /* New spells: Magi */
    {NORM,
     "arcane lock",
     {LEVELS_INIT, L(CLASS_MAG, 18)},
     spell_arcane_lock,
     TAR_IGNORE,
     POS_STANDING,
     NULL,
     SLOT(703),
     15,
     24,
     FALSE,
     "",
     "!Arcane Lock!",
     ""},

    {NORM,
     "elemental ward",
     {LEVELS_INIT, L(CLASS_MAG, 55)},
     spell_elemental_ward,
     TAR_CHAR_SELF,
     POS_STANDING,
     NULL,
     SLOT(702),
     50,
     24,
     FALSE,
     "",
     "!Elemental Ward!",
     ""},

    {NORM,
     "mana barrier",
     {LEVELS_INIT, L(CLASS_MAG, 25)},
     spell_mana_barrier,
     TAR_CHAR_SELF,
     POS_STANDING,
     NULL,
     SLOT(701),
     30,
     24,
     FALSE,
     "",
     "!Mana Barrier!",
     ""},

    {NORM,
     "mirror image",
     {LEVELS_INIT, L(CLASS_MAG, 38)},
     spell_mirror_image,
     TAR_CHAR_SELF,
     POS_STANDING,
     NULL,
     SLOT(704),
     25,
     24,
     FALSE,
     "",
     "!Mirror Image!",
     ""},

    {NORM,
     "wall of fire",
     {LEVELS_INIT, L(CLASS_MAG, 32)},
     spell_wall_of_fire,
     TAR_IGNORE,
     POS_FIGHTING,
     NULL,
     SLOT(700),
     30,
     24,
     TRUE,
     "wall of fire",
     "!Wall of Fire!",
     ""},

    /* New spells: Cleric */
    {NORM,
     "consecrate",
     {LEVELS_INIT, L(CLASS_CLE, 35)},
     spell_consecrate,
     TAR_IGNORE,
     POS_STANDING,
     NULL,
     SLOT(708),
     50,
     24,
     FALSE,
     "",
     "!Consecrate!",
     ""},

    {NORM,
     "divine strike",
     {LEVELS_INIT, L(CLASS_CLE, 4)},
     spell_divine_strike,
     TAR_CHAR_OFFENSIVE,
     POS_FIGHTING,
     NULL,
     SLOT(705),
     15,
     12,
     TRUE,
     "divine strike",
     "!Divine Strike!",
     ""},

    {NORM,
     "exorcism",
     {LEVELS_INIT, L(CLASS_CLE, 55)},
     spell_exorcism,
     TAR_CHAR_OFFENSIVE,
     POS_FIGHTING,
     NULL,
     SLOT(711),
     25,
     12,
     TRUE,
     "exorcism",
     "!Exorcism!",
     ""},

    {NORM,
     "holy word",
     {LEVELS_INIT, L(CLASS_CLE, 60)},
     spell_holy_word,
     TAR_IGNORE,
     POS_FIGHTING,
     NULL,
     SLOT(710),
     50,
     24,
     TRUE,
     "holy word",
     "!Holy Word!",
     ""},

    {NORM,         "prayer",   {LEVELS_INIT, L(CLASS_CLE, 22)},
     spell_prayer, TAR_IGNORE, POS_STANDING,
     NULL,         SLOT(712),  25,
     24,           FALSE,      "",
     "!Prayer!",   ""},

    {NORM,
     "restoration",
     {LEVELS_INIT, L(CLASS_CLE, 45)},
     spell_restoration,
     TAR_CHAR_DEFENSIVE,
     POS_STANDING,
     NULL,
     SLOT(707),
     40,
     24,
     FALSE,
     "",
     "!Restoration!",
     ""},

    {NORM,
     "solar flare",
     {LEVELS_INIT, L(CLASS_CLE, 50)},
     spell_solar_flare,
     TAR_CHAR_OFFENSIVE,
     POS_FIGHTING,
     NULL,
     SLOT(709),
     25,
     12,
     TRUE,
     "solar flare",
     "!Solar Flare!",
     ""},

    {NORM,
     "turn undead",
     {LEVELS_INIT, L(CLASS_CLE, 15)},
     spell_turn_undead,
     TAR_IGNORE,
     POS_FIGHTING,
     NULL,
     SLOT(706),
     20,
     24,
     FALSE,
     "",
     "!Turn Undead!",
     ""},

    /* New spells: Psionicist */
    {NORM,
     "astral projection",
     {LEVELS_INIT, L(CLASS_PSI, 60)},
     spell_astral_projection,
     TAR_CHAR_SELF,
     POS_STANDING,
     NULL,
     SLOT(713),
     40,
     24,
     FALSE,
     "",
     "!Astral Projection!",
     ""},

    {NORM,
     "mindwall",
     {LEVELS_INIT, L(CLASS_PSI, 22)},
     spell_mindwall,
     TAR_CHAR_SELF,
     POS_STANDING,
     NULL,
     SLOT(717),
     25,
     24,
     FALSE,
     "",
     "!Mindwall!",
     ""},

    {NORM,
     "pain",
     {LEVELS_INIT, L(CLASS_PSI, 28)},
     spell_pain,
     TAR_CHAR_OFFENSIVE,
     POS_FIGHTING,
     NULL,
     SLOT(714),
     25,
     12,
     TRUE,
     "psychic pain",
     "!Pain!",
     ""},

    {NORM,
     "precognition",
     {LEVELS_INIT, L(CLASS_PSI, 45)},
     spell_precognition,
     TAR_CHAR_SELF,
     POS_STANDING,
     NULL,
     SLOT(716),
     30,
     24,
     FALSE,
     "",
     "!Precognition!",
     ""},

    {NORM,
     "thoughtsteal",
     {LEVELS_INIT, L(CLASS_PSI, 40)},
     spell_thoughtsteal,
     TAR_CHAR_OFFENSIVE,
     POS_FIGHTING,
     NULL,
     SLOT(715),
     30,
     12,
     TRUE,
     "thoughtsteal",
     "!Thoughtsteal!",
     ""},

    /* Grand Magi adept spells */

    {NORM,
     "elemental confluence",
     {LEVELS_INIT, L(CLASS_GMA, 18)},
     spell_elemental_confluence,
     TAR_CHAR_OFFENSIVE,
     POS_FIGHTING,
     NULL,
     SLOT(760),
     200,
     12,
     TRUE,
     "elemental confluence",
     "!elemental confluence!",
     ""},

    {NORM,
     "convergence shield",
     {LEVELS_INIT, L(CLASS_GMA, 8)},
     spell_convergence_shield,
     TAR_CHAR_SELF,
     POS_STANDING,
     NULL,
     SLOT(761),
     100,
     12,
     FALSE,
     "",
     "Your convergence shield dissipates.",
     "The elemental barrier around $n fades."},

    /* Templar adept spells */

    {NORM,
     "sacred ward",
     {LEVELS_INIT, L(CLASS_TEM, 5)},
     spell_sacred_ward,
     TAR_IGNORE,
     POS_STANDING,
     NULL,
     SLOT(762),
     80,
     24,
     FALSE,
     "",
     "The sacred ward's warmth fades.",
     "The sacred ward around $n fades."},

    /* Kinetimancer adept spells */

    {NORM,
     "momentum drain",
     {LEVELS_INIT, L(CLASS_KIN, 5)},
     spell_momentum_drain,
     TAR_CHAR_OFFENSIVE,
     POS_FIGHTING,
     NULL,
     SLOT(763),
     100,
     12,
     TRUE,
     "momentum drain",
     "Your momentum returns to normal.",
     "$n's momentum returns to normal."},

    {NORM,
     "entropic shield",
     {LEVELS_INIT, L(CLASS_KIN, 8)},
     spell_entropic_shield,
     TAR_CHAR_SELF,
     POS_STANDING,
     NULL,
     SLOT(764),
     100,
     12,
     FALSE,
     "",
     "Your entropic shield dissipates.",
     "The entropic field around $n fades."},

    {NORM,
     "cognitive disruption",
     {LEVELS_INIT, L(CLASS_KIN, 12)},
     spell_cognitive_disruption,
     TAR_CHAR_OFFENSIVE,
     POS_FIGHTING,
     NULL,
     SLOT(765),
     120,
     12,
     TRUE,
     "cognitive disruption",
     "Your concentration returns.",
     "$n's concentration returns."},

    {NORM,
     "predictive collapse",
     {LEVELS_INIT, L(CLASS_KIN, 15)},
     spell_predictive_collapse,
     TAR_CHAR_OFFENSIVE,
     POS_FIGHTING,
     NULL,
     SLOT(766),
     150,
     12,
     TRUE,
     "predictive collapse",
     "Your combat patterns stabilize.",
     "$n's combat patterns stabilize."},
