
/*
 * Fighter and thief skills.
 */

{NORM,
 "appraise",
 {LEVELS_INIT, L(CLASS_CIP, 12)},
 spell_null,
 TAR_IGNORE,
 POS_STANDING,
 &gsn_appraise,
 SLOT(0),
 0,
 24,
 FALSE,
 "",
 "!Appraise!",
 ""},

    {NORM,       "bash",     {LEVELS_INIT, L(CLASS_WAR, 28)},
     spell_null, TAR_IGNORE, POS_FIGHTING,
     &gsn_bash,  SLOT(0),    0,
     24,         TRUE,       "bash",
     "!bash!",   ""},

    {NORM,
     "berserk",
     {LEVELS_INIT, L(CLASS_WAR, 34)},
     spell_null,
     TAR_IGNORE,
     POS_FIGHTING,
     &gsn_beserk,
     SLOT(0),
     0,
     24,
     TRUE,
     "berserk",
     "You calm down!",
     "$n looks calmer!"},

    {NORM,       "climb",    {LEVELS_INIT, L(CLASS_CIP, 25)},
     spell_null, TAR_IGNORE, POS_FIGHTING,
     &gsn_climb, SLOT(0),    0,
     24,         FALSE,      "",
     "!Climb!",  ""},

    {NORM,
     "dirt",
     {LEVELS_INIT, L(CLASS_CIP, 36), L(CLASS_WAR, 35), L(CLASS_PUG, 47), L(CLASS_SEN, 42)},
     spell_null,
     TAR_IGNORE,
     POS_FIGHTING,
     &gsn_dirt,
     SLOT(0),
     1,
     24,
     TRUE,
     "",
     "!dirt!",
     ""},

    {NORM,
     "nodisarm",
     {LEVELS_INIT, L(CLASS_CIP, 40), L(CLASS_WAR, 30), L(CLASS_SEN, 40)},
     spell_null,
     TAR_IGNORE,
     POS_FIGHTING,
     &gsn_nodisarm,
     SLOT(0),
     0,
     0,
     FALSE,
     "",
     "!nodisarm!",
     ""},

    {NORM,  "smash", {LEVELS_INIT}, spell_null, TAR_IGNORE, POS_STANDING, &gsn_smash, SLOT(0), 0, 0,
     FALSE, "",      "!smash!",     ""},

    {NORM,       "steal",    {LEVELS_INIT, L(CLASS_CIP, 20)},
     spell_null, TAR_IGNORE, POS_FIGHTING,
     &gsn_steal, SLOT(0),    1,
     18,         TRUE,       "steal",
     "!steal!",  ""},

    {NORM,        "circle",   {LEVELS_INIT, L(CLASS_CIP, 19)},
     spell_null,  TAR_IGNORE, POS_FIGHTING,
     &gsn_circle, SLOT(0),    1,
     18,          TRUE,       "circle",
     "!circle!",  ""},

    {NORM,
     "backstab",
     {LEVELS_INIT, L(CLASS_CIP, 10)},
     spell_null,
     TAR_IGNORE,
     POS_STANDING,
     &gsn_backstab,
     SLOT(0),
     1,
     18,
     TRUE,
     "backstab",
     "!Backstab!",
     ""},

    {NORM,        "disarm",   {LEVELS_INIT, L(CLASS_CIP, 53), L(CLASS_WAR, 12), L(CLASS_SEN, 38)},
     spell_null,  TAR_IGNORE, POS_FIGHTING,
     &gsn_disarm, SLOT(0),    1,
     18,          TRUE,       "",
     "!Disarm!",  ""},

    {NORM,       "dodge",    {LEVELS_INIT, L(CLASS_CIP, 7), L(CLASS_PUG, 27), L(CLASS_SEN, 18)},
     spell_null, TAR_IGNORE, POS_FIGHTING,
     &gsn_dodge, SLOT(0),    0,
     0,          FALSE,      "",
     "!Dodge!",  ""},

    {NORM,
     "dualwield",
     {LEVELS_INIT, L(CLASS_ASS, 5), L(CLASS_WLK, 5)},
     spell_null,
     TAR_IGNORE,
     POS_FIGHTING,
     &gsn_dualwield,
     SLOT(0),
     0,
     0,
     FALSE,
     "",
     "!DualWield!",
     ""},

    {NORM,
     "enhanced damage",
     {LEVELS_INIT, L(CLASS_WAR, 20)},
     spell_null,
     TAR_IGNORE,
     POS_FIGHTING,
     &gsn_enhanced_damage,
     SLOT(0),
     0,
     0,
     FALSE,
     "",
     "!Enhanced Damage!",
     ""},

    {NORM,
     "equip buckler",
     {LEVELS_INIT, L(CLASS_PAL, 1), L(CLASS_KNI, 1), L(CLASS_SWO, 1)},
     spell_null,
     TAR_IGNORE,
     POS_FIGHTING,
     &gsn_equip_buckler,
     SLOT(0),
     0,
     0,
     FALSE,
     "",
     "!Equip Buckler!",
     ""},

    {NORM,
     "equip fist",
     {LEVELS_INIT, L(CLASS_MON, 1), L(CLASS_BRA, 1)},
     spell_null,
     TAR_IGNORE,
     POS_FIGHTING,
     &gsn_equip_fist,
     SLOT(0),
     0,
     0,
     FALSE,
     "",
     "!Equip Fist!",
     ""},

    {NORM,
     "dual fist",
     {LEVELS_INIT, L(CLASS_MON, 35), L(CLASS_BRA, 35)},
     spell_null,
     TAR_IGNORE,
     POS_FIGHTING,
     &gsn_dual_fist,
     SLOT(0),
     0,
     0,
     FALSE,
     "",
     "!Dual Fist!",
     ""},

    {NORM,
     "equip wand",
     {LEVELS_INIT, L(CLASS_SOR, 1), L(CLASS_NEC, 1), L(CLASS_WIZ, 1), L(CLASS_PRI, 1),
      L(CLASS_EGO, 1)},
     spell_null,
     TAR_IGNORE,
     POS_FIGHTING,
     &gsn_equip_wand,
     SLOT(0),
     0,
     0,
     FALSE,
     "",
     "!Equip Wand!",
     ""},

    {NORM,
     "flee timer",
     {LEVELS_INIT},
     spell_null,
     TAR_IGNORE,
     POS_STANDING,
     &gsn_flee_timer,
     SLOT(0),
     0,
     24,
     FALSE,
     "",
     "Your anti-flee timer has expired!",
     ""},

    {NORM,
     "find doors",
     {LEVELS_INIT, L(CLASS_CIP, 16)},
     spell_null,
     TAR_IGNORE,
     POS_FIGHTING,
     &gsn_find_doors,
     SLOT(0),
     0,
     0,
     FALSE,
     "",
     "!Find Doors!",
     ""},

    {NORM,
     "counter",
     {LEVELS_INIT, L(CLASS_PUG, 20)},
     spell_null,
     TAR_IGNORE,
     POS_FIGHTING,
     &gsn_counter,
     SLOT(0),
     0,
     0,
     FALSE,
     "counter",
     "!Counter!",
     ""},

    {NORM,
     "enhanced critical",
     {LEVELS_INIT, L(CLASS_CIP, 20)},
     spell_null,
     TAR_IGNORE,
     POS_FIGHTING,
     &gsn_enhanced_critical,
     SLOT(0),
     0,
     0,
     FALSE,
     "",
     "!Enhanced Crit!",
     ""},

    {NORM,
     "enhanced heal",
     {LEVELS_INIT, L(CLASS_TEM, 1)},
     spell_null,
     TAR_IGNORE,
     POS_FIGHTING,
     &gsn_enhanced_heal,
     SLOT(0),
     0,
     0,
     FALSE,
     "",
     "!Enhanced Heal!",
     ""},

    {NORM,
     "enhanced purify",
     {LEVELS_INIT, L(CLASS_EGO, 44)},
     spell_null,
     TAR_IGNORE,
     POS_FIGHTING,
     &gsn_enhanced_purify,
     SLOT(0),
     0,
     0,
     FALSE,
     "",
     "!Enhanced Purify!",
     ""},

    {NORM,
     "spell critical",
     {LEVELS_INIT, L(CLASS_PSI, 20)},
     spell_null,
     TAR_IGNORE,
     POS_FIGHTING,
     &gsn_spell_critical,
     SLOT(0),
     0,
     0,
     FALSE,
     "",
     "!Spell Crit!",
     ""},

    {NORM,
     "spell critical damage",
     {LEVELS_INIT, L(CLASS_CLE, 20)},
     spell_null,
     TAR_IGNORE,
     POS_FIGHTING,
     &gsn_spell_critical_damage,
     SLOT(0),
     0,
     0,
     FALSE,
     "",
     "!Spell Critical Damage!",
     ""},

    {NORM,
     "headbutt",
     {LEVELS_INIT, L(CLASS_WAR, 6)},
     spell_null,
     TAR_CHAR_OFFENSIVE,
     POS_FIGHTING,
     &gsn_headbutt,
     SLOT(0),
     1,
     18,
     TRUE,
     "headbutt",
     "!HeadButt!",
     ""},

    {NORM,       "hide",     {LEVELS_INIT, L(CLASS_CIP, 12)},
     spell_null, TAR_IGNORE, POS_RESTING,
     &gsn_hide,  SLOT(0),    0,
     12,         FALSE,      "",
     "!Hide!",   ""},

    {NORM,       "hunt",     {LEVELS_INIT, L(CLASS_CIP, 70)},
     spell_null, TAR_IGNORE, POS_RESTING,
     &gsn_hunt,  SLOT(0),    0,
     12,         FALSE,      "",
     "!Hunt!",   ""},

    {NORM,
     "kick",
     {LEVELS_INIT, L(CLASS_WAR, 14)},
     spell_null,
     TAR_CHAR_OFFENSIVE,
     POS_FIGHTING,
     &gsn_kick,
     SLOT(0),
     1,
     18,
     TRUE,
     "kick",
     "!Kick!",
     ""},

    {NORM,
     "knee",
     {LEVELS_INIT, L(CLASS_WAR, 8)},
     spell_null,
     TAR_CHAR_OFFENSIVE,
     POS_FIGHTING,
     &gsn_knee,
     SLOT(0),
     1,
     18,
     TRUE,
     "knee",
     "!Knee",
     ""},

    {NORM,       "detox",    {LEVELS_INIT, L(CLASS_CIP, 27)},
     spell_null, TAR_IGNORE, POS_STANDING,
     &gsn_detox, SLOT(0),    0,
     24,         FALSE,      "detox",
     "!Detox",   ""},

    {NORM,
     "martial arts",
     {LEVELS_INIT, L(CLASS_PUG, 10)},
     spell_null,
     TAR_IGNORE,
     POS_FIGHTING,
     &gsn_martial_arts,
     SLOT(0),
     0,
     0,
     FALSE,
     "",
     "!Martial Arts!",
     ""},

    {NORM,       "parry",    {LEVELS_INIT, L(CLASS_CIP, 52), L(CLASS_WAR, 10), L(CLASS_SEN, 8)},
     spell_null, TAR_IGNORE, POS_FIGHTING,
     &gsn_parry, SLOT(0),    0,
     0,          FALSE,      "",
     "!Parry!",  ""},

    {NORM,       "peek",     {LEVELS_INIT, L(CLASS_CIP, 20)},
     spell_null, TAR_IGNORE, POS_STANDING,
     &gsn_peek,  SLOT(0),    0,
     0,          FALSE,      "",
     "!Peek!",   ""},

    {NORM,
     "pick lock",
     {LEVELS_INIT, L(CLASS_CIP, 25)},
     spell_null,
     TAR_IGNORE,
     POS_STANDING,
     &gsn_pick_lock,
     SLOT(0),
     0,
     12,
     FALSE,
     "",
     "!Pick!",
     ""},

    {NORM,       "punch",    {LEVELS_INIT, L(CLASS_WAR, 5)},
     spell_null, TAR_IGNORE, POS_STANDING,
     &gsn_punch, SLOT(0),    1,
     18,         TRUE,       "punch",
     "!Punch!",  ""},

    {NORM,        "rescue",   {LEVELS_INIT, L(CLASS_WAR, 15), L(CLASS_SEN, 15)},
     spell_null,  TAR_IGNORE, POS_FIGHTING,
     &gsn_rescue, SLOT(0),    0,
     12,          FALSE,      "",
     "!Rescue!",  ""},

    {NORM,
     "shadowform",
     {LEVELS_INIT, L(CLASS_PSI, 9)},
     spell_null,
     TAR_IGNORE,
     POS_STANDING,
     &gsn_shadow,
     SLOT(0),
     0,
     0,
     FALSE,
     "",
     NULL,
     ""},

    {NORM,
     "shield block",
     {LEVELS_INIT, L(CLASS_WAR, 40), L(CLASS_PUG, 18), L(CLASS_SEN, 28)},
     spell_null,
     TAR_IGNORE,
     POS_STANDING,
     &gsn_shield_block,
     SLOT(0),
     0,
     12,
     FALSE,
     "",
     "!Shield Block!",
     ""},

    {NORM,       "sneak",    {LEVELS_INIT, L(CLASS_CIP, 5)},
     spell_null, TAR_IGNORE, POS_STANDING,
     &gsn_sneak, SLOT(0),    0,
     12,         FALSE,      "",
     NULL,       ""},

    {NORM,       "stun",     {LEVELS_INIT},
     spell_null, TAR_IGNORE, POS_FIGHTING,
     &gsn_stun,  SLOT(0),    0,
     24,         FALSE,      "",
     "",         ""},

    {NORM,
     "disguise",
     {LEVELS_INIT, L(CLASS_ASS, 25), L(CLASS_WLK, 25)},
     spell_null,
     TAR_IGNORE,
     POS_STANDING,
     &gsn_disguise,
     SLOT(0),
     0,
     0,
     FALSE,
     "",
     "!Disguise!",
     ""},

    {NORM,
     "frenzy",
     {LEVELS_INIT, L(CLASS_KNI, 27), L(CLASS_PRI, 41), L(CLASS_SWO, 28)},
     spell_null,
     TAR_CHAR_OFFENSIVE,
     POS_FIGHTING,
     &gsn_frenzy,
     SLOT(0),
     0,
     24,
     FALSE,
     "frenzy",
     "!FRENZY!",
     ""},

    {NORM,        "warcry",   {LEVELS_INIT, L(CLASS_WAR, 10)},
     spell_null,  TAR_IGNORE, POS_STANDING,
     &gsn_warcry, SLOT(0),    0,
     24,          TRUE,       "warcry",
     "!Warcry!",  ""},

    {NORM,
     "emotion control",
     {LEVELS_INIT, L(CLASS_PSI, 75)},
     spell_null,
     TAR_CHAR_OFFENSIVE,
     POS_FIGHTING,
     &gsn_emotion_control,
     SLOT(0),
     0,
     24,
     FALSE,
     "emotion control",
     "!EMOTION CONTROL!",
     ""},

    /*
     *  Spells for mega1.are from Glop/Erkenbrand.
     */
    {NORM,
     "general purpose",
     {LEVELS_INIT},
     spell_general_purpose,
     TAR_CHAR_OFFENSIVE,
     POS_FIGHTING,
     NULL,
     SLOT(205),
     0,
     12,
     FALSE,
     "general purpose ammo",
     "!General Purpose Ammo!",
     ""},

    {NORM,
     "high explosive",
     {LEVELS_INIT},
     spell_high_explosive,
     TAR_CHAR_OFFENSIVE,
     POS_FIGHTING,
     NULL,
     SLOT(206),
     0,
     12,
     FALSE,
     "high explosive ammo",
     "!High Explosive Ammo!",
     ""},

    {NORM,
     "deflect weapon",
     {LEVELS_INIT, L(CLASS_NEC, 22), L(CLASS_EGO, 22)},
     spell_deflect_weapon,
     TAR_CHAR_DEFENSIVE,
     POS_STANDING,
     NULL,
     SLOT(600),
     25,
     12,
     TRUE,
     "",
     "Your mind shield melts away.",
     ""},

    {NORM,
     "black hand",
     {LEVELS_INIT, L(CLASS_NEC, 7), L(CLASS_EGO, 7)},
     spell_black_hand,
     TAR_CHAR_OFFENSIVE,
     POS_FIGHTING,
     NULL,
     SLOT(601),
     50,
     12,
     TRUE,
     "Black Hand",
     "The hand dissolves from around your throat into nothingness.",
     ""},
    {NORM,
     "throwing needle",
     {LEVELS_INIT, L(CLASS_WLK, 7)},
     spell_throw_needle,
     TAR_CHAR_OFFENSIVE,
     POS_FIGHTING,
     NULL,
     SLOT(602),
     40,
     12,
     TRUE,
     "Throwing Needle",
     "!Throwing Needle!",
     ""},

    {NORM,        "morale",   {LEVELS_INIT, L(CLASS_PAL, 21), L(CLASS_KNI, 10)},
     spell_null,  TAR_IGNORE, POS_STANDING,
     &gsn_morale, SLOT(0),    75,
     24,          TRUE,       "Morale",
     "!Morale!",  ""},

    {NORM,
     "leadership",
     {LEVELS_INIT, L(CLASS_PAL, 24), L(CLASS_KNI, 12)},
     spell_null,
     TAR_IGNORE,
     POS_STANDING,
     &gsn_leadership,
     SLOT(0),
     75,
     24,
     TRUE,
     "Leadership",
     "!Leadership!",
     ""},

    {NORM,
     "two handed",
     {LEVELS_INIT, L(CLASS_PAL, 8), L(CLASS_KNI, 6), L(CLASS_SWO, 6)},
     spell_null,
     TAR_IGNORE,
     POS_FIGHTING,
     &gsn_two_handed,
     SLOT(0),
     0,
     0,
     FALSE,
     "",
     "!Two Handed!",
     ""},

    {NORM,
     "palmstrike",
     {LEVELS_INIT, L(CLASS_BRA, 19)},
     spell_null,
     TAR_CHAR_OFFENSIVE,
     POS_FIGHTING,
     &gsn_palmstrike,
     SLOT(0),
     0,
     0,
     TRUE,
     "Palmstrike",
     "!Palm Strike!",
     ""},

    {NORM,
     "bare hand",
     {LEVELS_INIT, L(CLASS_MON, 6), L(CLASS_BRA, 6)},
     spell_null,
     TAR_IGNORE,
     POS_FIGHTING,
     &gsn_bare_hand,
     SLOT(0),
     0,
     0,
     FALSE,
     "",
     "!Enhanced Sword!",
     ""},

    {NORM,
     "weapon bond",
     {LEVELS_INIT, L(CLASS_SWO, 1)},
     spell_null,
     TAR_IGNORE,
     POS_STANDING,
     &gsn_weapon_bond,
     SLOT(0),
     0,
     0,
     FALSE,
     "",
     "!Weapon Bond!",
     ""},

    {NORM,
     "enhanced sword damage",
     {LEVELS_INIT, L(CLASS_SWO, 20)},
     spell_null,
     TAR_IGNORE,
     POS_FIGHTING,
     &gsn_enhanced_sword,
     SLOT(0),
     0,
     0,
     FALSE,
     "",
     "!Enhanced Sword!",
     ""},

    {NORM,
     "enhanced sword critical",
     {LEVELS_INIT, L(CLASS_SWO, 40)},
     spell_null,
     TAR_IGNORE,
     POS_FIGHTING,
     &gsn_enhanced_sword_critical,
     SLOT(0),
     0,
     0,
     FALSE,
     "",
     "!Enhanced Sword Critical!",
     ""},

    {NORM,
     "Ice Bolt",
     {LEVELS_INIT, L(CLASS_SOR, 3)},
     spell_ice_bolt,
     TAR_CHAR_OFFENSIVE,
     POS_FIGHTING,
     NULL,
     SLOT(605),
     20,
     12,
     TRUE,
     "Ice Bolt",
     "!Ice Bolt!",
     ""},
    {NORM,
     "water elemental",
     {LEVELS_INIT, L(CLASS_SOR, 6)},
     spell_waterelem,
     TAR_IGNORE,
     POS_STANDING,
     NULL,
     SLOT(606),
     80,
     24,
     FALSE,
     "",
     "!Stalker!",
     ""},
    {NORM,
     "skeleton",
     {LEVELS_INIT, L(CLASS_NEC, 9), L(CLASS_EGO, 9)},
     spell_skeleton,
     TAR_IGNORE,
     POS_STANDING,
     NULL,
     SLOT(607),
     80,
     24,
     FALSE,
     "",
     "!Stalker!",
     ""},
    {NORM,
     "poison weapon",
     {LEVELS_INIT, L(CLASS_ASS, 25), L(CLASS_WLK, 5)},
     spell_poison_weapon,
     TAR_OBJ_INV,
     POS_STANDING,
     NULL,
     SLOT(608),
     100,
     24,
     FALSE,
     "",
     "!Enchant Weapon!",
     ""},

    {NORM,
     "adrenaline",
     {LEVELS_INIT, L(CLASS_PAL, 42), L(CLASS_KNI, 21), L(CLASS_MON, 28), L(CLASS_PRI, 42),
      L(CLASS_SWO, 21), L(CLASS_BRA, 28)},
     spell_null,
     TAR_IGNORE,
     POS_FIGHTING,
     &gsn_adrenaline,
     SLOT(0),
     0,
     0,
     FALSE,
     "",
     "!ADRENALINE!",
     ""},

    {NORM,
     "throwing star",
     {LEVELS_INIT, L(CLASS_ASS, 43), L(CLASS_WLK, 12)},
     spell_throw_needle,
     TAR_CHAR_OFFENSIVE,
     POS_FIGHTING,
     NULL,
     SLOT(628),
     85,
     12,
     TRUE,
     "Throwing Star",
     "!Throwing Star!",
     ""},

    /* THIS IS A SPELL AFFECT HOLDER FOR THE SKILL ADRENALINE..DO NOT CAST! */

    {NORM,
     "adrenaline bonus",
     {LEVELS_INIT},
     spell_null,
     TAR_IGNORE,
     POS_FIGHTING,
     NULL,
     SLOT(612),
     0,
     0,
     FALSE,
     "",
     "!ADRENALINE BONUS!",
     ""},

    {NORM,
     "fire elemental",
     {LEVELS_INIT, L(CLASS_SOR, 11)},
     spell_fireelem,
     TAR_IGNORE,
     POS_STANDING,
     NULL,
     SLOT(612),
     120,
     24,
     FALSE,
     "",
     "!FIRE ELEMENTAL!",
     ""},
    {NORM,
     "rune:fire",
     {LEVELS_INIT, L(CLASS_SOR, 40), L(CLASS_WIZ, 40)},
     spell_rune_fire,
     TAR_IGNORE,
     POS_STANDING,
     NULL,
     SLOT(613),
     150,
     12,
     FALSE,
     "",
     "The rune dissipates.",
     ""},

    {NORM,
     "rune:shock",
     {LEVELS_INIT, L(CLASS_SOR, 56), L(CLASS_NEC, 15), L(CLASS_WIZ, 56), L(CLASS_EGO, 15)},
     spell_rune_shock,
     TAR_IGNORE,
     POS_STANDING,
     NULL,
     SLOT(614),
     150,
     12,
     FALSE,
     "",
     "The rune dissipates.",
     ""},

    {NORM,
     "rune:poison",
     {LEVELS_INIT, L(CLASS_ASS, 38), L(CLASS_NEC, 40), L(CLASS_WLK, 8)},
     spell_rune_poison,
     TAR_IGNORE,
     POS_STANDING,
     NULL,
     SLOT(615),
     80,
     12,
     FALSE,
     "",
     "The rune dissipates.",
     ""},

    {NORM,
     "healing light",
     {LEVELS_INIT, L(CLASS_PAL, 42), L(CLASS_PRI, 11)},
     spell_healing_light,
     TAR_IGNORE,
     POS_STANDING,
     NULL,
     SLOT(616),
     150,
     12,
     FALSE,
     "",
     "@@NThe @@mHealing Light@@N dissipates.",
     ""},

    {NORM,
     "withering shadow",
     {LEVELS_INIT},
     spell_wither_shadow,
     TAR_IGNORE,
     POS_STANDING,
     NULL,
     SLOT(617),
     150,
     12,
     FALSE,
     "",
     "@@NThe @@dWithering Shadow@@N dissipates.",
     ""},

    {NORM,
     "mana flare",
     {LEVELS_INIT, L(CLASS_SOR, 18), L(CLASS_WIZ, 18)},
     spell_mana_flare,
     TAR_IGNORE,
     POS_STANDING,
     NULL,
     SLOT(618),
     80,
     12,
     FALSE,
     "",
     "@@NThe @@eMana Flare@@N dissipates.",
     ""},

    {NORM,
     "mana drain",
     {LEVELS_INIT, L(CLASS_SOR, 11), L(CLASS_NEC, 15), L(CLASS_WIZ, 11), L(CLASS_EGO, 15)},
     spell_mana_drain,
     TAR_IGNORE,
     POS_STANDING,
     NULL,
     SLOT(619),
     150,
     12,
     FALSE,
     "",
     "@@NThe @@dMana Drain@@N dissipates.",
     ""},

    {NORM,
     "cage",
     {LEVELS_INIT, L(CLASS_SOR, 18), L(CLASS_PAL, 31), L(CLASS_ASS, 40), L(CLASS_KNI, 19),
      L(CLASS_NEC, 13), L(CLASS_WIZ, 18), L(CLASS_PRI, 31), L(CLASS_WLK, 40), L(CLASS_SWO, 19),
      L(CLASS_EGO, 13)},
     spell_cage,
     TAR_IGNORE,
     POS_STANDING,
     NULL,
     SLOT(620),
     150,
     12,
     FALSE,
     "",
     "@@NThe @@rCage@@N dissipates.",
     ""},

    {NORM,
     "room dispel",
     {LEVELS_INIT, L(CLASS_SOR, 22), L(CLASS_NEC, 34), L(CLASS_WIZ, 22), L(CLASS_EGO, 34)},
     spell_room_dispel,
     TAR_IGNORE,
     POS_STANDING,
     NULL,
     SLOT(625),
     120,
     12,
     FALSE,
     "",
     "",
     ""},

    {NORM,
     "soul net",
     {LEVELS_INIT, L(CLASS_NEC, 58), L(CLASS_EGO, 58)},
     spell_soul_net,
     TAR_IGNORE,
     POS_STANDING,
     NULL,
     SLOT(629),
     350,
     12,
     FALSE,
     "",
     "@@NThe @@dSoul Net@@N dissipates.",
     ""},

    {NORM,
     "condense soul",
     {LEVELS_INIT, L(CLASS_NEC, 78), L(CLASS_EGO, 78)},
     spell_condense_soul,
     TAR_OBJ_INV,
     POS_STANDING,
     NULL,
     SLOT(630),
     800,
     24,
     FALSE,
     "",
     "!Soul Potion!",
     ""},

    {NORM,
     "restoration",
     {LEVELS_INIT},
     spell_restoration,
     TAR_CHAR_DEFENSIVE,
     POS_FIGHTING,
     NULL,
     SLOT(632),
     50,
     12,
     FALSE,
     "",
     "!restoration!",
     ""},

    {NORM,
     "infuse",
     {LEVELS_INIT, L(CLASS_NEC, 71), L(CLASS_EGO, 71)},
     spell_infuse,
     TAR_OBJ_INV,
     POS_STANDING,
     NULL,
     SLOT(633),
     1000,
     24,
     FALSE,
     "",
     "!Infuse Soul!",
     ""},

    {NORM,
     "holy light",
     {LEVELS_INIT, L(CLASS_PAL, 43), L(CLASS_WIZ, 82), L(CLASS_PRI, 14)},
     spell_holy_light,
     TAR_IGNORE,
     POS_STANDING,
     NULL,
     SLOT(634),
     75,
     24,
     FALSE,
     "Holy Light",
     "!Holy Light!",
     ""},

    {NORM,
     "target",
     {LEVELS_INIT, L(CLASS_PAL, 32), L(CLASS_KNI, 20), L(CLASS_MON, 18), L(CLASS_PRI, 32),
      L(CLASS_SWO, 20), L(CLASS_BRA, 18)},
     spell_null,
     TAR_CHAR_OFFENSIVE,
     POS_FIGHTING,
     &gsn_target,
     SLOT(0),
     0,
     24,
     FALSE,
     "target",
     "!target",
     ""},

    {NORM,
     "charge",
     {LEVELS_INIT, L(CLASS_PAL, 89), L(CLASS_KNI, 30), L(CLASS_PRI, 89), L(CLASS_SWO, 30)},
     spell_null,
     TAR_CHAR_OFFENSIVE,
     POS_FIGHTING,
     &gsn_charge,
     SLOT(0),
     1,
     24,
     TRUE,
     "Charge",
     "!Charge",
     ""},

    {NORM,
     "scout",
     {LEVELS_INIT, L(CLASS_PAL, 45), L(CLASS_ASS, 26), L(CLASS_KNI, 30), L(CLASS_MON, 43),
      L(CLASS_PRI, 45), L(CLASS_WLK, 26), L(CLASS_SWO, 30), L(CLASS_BRA, 43)},
     spell_null,
     TAR_IGNORE,
     POS_STANDING,
     &gsn_scout,
     SLOT(0),
     0,
     0,
     FALSE,
     "",
     "",
     ""},
    {NORM,
     "divine intervention",
     {LEVELS_INIT, L(CLASS_PAL, 67), L(CLASS_PRI, 12)},
     spell_divine_intervention,
     TAR_CHAR_DEFENSIVE,
     POS_FIGHTING,
     NULL,
     SLOT(635),
     150,
     12,
     TRUE,
     "",
     "!Intervention!",
     ""},

    {NORM,
     "holy armor",
     {LEVELS_INIT, L(CLASS_PAL, 30), L(CLASS_PRI, 19)},
     spell_holy_armor,
     TAR_CHAR_DEFENSIVE,
     POS_STANDING,
     NULL,
     SLOT(636),
     100,
     12,
     FALSE,
     "",
     "Your armor is no longer blessed.",
     ""},

    {NORM,
     "unit tactics",
     {LEVELS_INIT, L(CLASS_KNI, 16), L(CLASS_SWO, 16)},
     spell_null,
     TAR_IGNORE,
     POS_STANDING,
     &gsn_unit_tactics,
     SLOT(0),
     0,
     24,
     FALSE,
     "Unit Tactics",
     "!Unit Tactics!",
     ""},

    {NORM,
     "earth elemental",
     {LEVELS_INIT, L(CLASS_SOR, 52)},
     spell_earthelem,
     TAR_IGNORE,
     POS_STANDING,
     NULL,
     SLOT(637),
     500,
     24,
     FALSE,
     "",
     "!EARTH ELEMENTAL!",
     ""},

    {NORM,
     "iron golem",
     {LEVELS_INIT, L(CLASS_WIZ, 63)},
     spell_iron_golem,
     TAR_IGNORE,
     POS_STANDING,
     NULL,
     SLOT(638),
     800,
     24,
     FALSE,
     "",
     "!IRON GOLEM!",
     ""},

    {NORM,
     "diamond golem",
     {LEVELS_INIT, L(CLASS_WIZ, 77)},
     spell_diamond_golem,
     TAR_IGNORE,
     POS_STANDING,
     NULL,
     SLOT(639),
     1100,
     24,
     FALSE,
     "",
     "!DIAMOND GOLEM!",
     ""},
    {NORM,
     "soul thief",
     {LEVELS_INIT, L(CLASS_NEC, 67), L(CLASS_EGO, 67)},
     spell_soul_thief,
     TAR_IGNORE,
     POS_STANDING,
     NULL,
     SLOT(640),
     900,
     24,
     FALSE,
     "",
     "!SOUL THIEF!",
     ""},
    {NORM,
     "holy avenger",
     {LEVELS_INIT, L(CLASS_PAL, 76), L(CLASS_PRI, 76)},
     spell_holy_avenger,
     TAR_IGNORE,
     POS_STANDING,
     NULL,
     SLOT(641),
     1200,
     24,
     FALSE,
     "",
     "!HOLY AVENGER!",
     ""},
    {NORM,
     "heat armor",
     {LEVELS_INIT, L(CLASS_SOR, 57), L(CLASS_NEC, 78), L(CLASS_WIZ, 57), L(CLASS_EGO, 78)},
     spell_heat_armor,
     TAR_CHAR_OFFENSIVE,
     POS_FIGHTING,
     NULL,
     SLOT(642),
     350,
     12,
     TRUE,
     "Heat Armor",
     "!Heat Armor!",
     ""},

    {NORM,
     "Retributive Strike",
     {LEVELS_INIT, L(CLASS_SOR, 72), L(CLASS_NEC, 78), L(CLASS_WIZ, 72), L(CLASS_EGO, 78)},
     spell_retri_strike,
     TAR_IGNORE,
     POS_FIGHTING,
     NULL,
     SLOT(643),
     800,
     12,
     TRUE,
     "Retributive strike",
     "!Retributive Strike!",
     ""},

    {NORM,
     "Lava Burst",
     {LEVELS_INIT, L(CLASS_SOR, 40), L(CLASS_WIZ, 40)},
     spell_lava_burst,
     TAR_CHAR_OFFENSIVE,
     POS_FIGHTING,
     NULL,
     SLOT(644),
     350,
     12,
     TRUE,
     "Lava Burst",
     "!Lava Burst!",
     ""},

    {NORM,
     "fireshield",
     {LEVELS_INIT, L(CLASS_SOR, 80), L(CLASS_WIZ, 80)},
     spell_fireshield,
     TAR_CHAR_DEFENSIVE,
     POS_FIGHTING,
     NULL,
     SLOT(645),
     400,
     12,
     FALSE,
     "",
     "",
     ""},

    {NORM,
     "iceshield",
     {LEVELS_INIT, L(CLASS_SOR, 65), L(CLASS_WIZ, 65)},
     spell_iceshield,
     TAR_CHAR_DEFENSIVE,
     POS_FIGHTING,
     NULL,
     SLOT(646),
     350,
     12,
     FALSE,
     "",
     "",
     ""},

    {NORM,
     "shockshield",
     {LEVELS_INIT, L(CLASS_SOR, 55), L(CLASS_WIZ, 55)},
     spell_shockshield,
     TAR_CHAR_DEFENSIVE,
     POS_FIGHTING,
     NULL,
     SLOT(647),
     400,
     12,
     FALSE,
     "",
     "",
     ""},

    {NORM,
     "shadowshield",
     {LEVELS_INIT},
     spell_shadowshield,
     TAR_CHAR_DEFENSIVE,
     POS_FIGHTING,
     NULL,
     SLOT(648),
     400,
     12,
     FALSE,
     "",
     "@@NThe @@rshield@@N shatters!!",
     "@@NThe @@rshield@@N protecting $n shatters!!"},
    {NORM,
     "thoughtshield",
     {LEVELS_INIT},
     spell_thoughtshield,
     TAR_CHAR_DEFENSIVE,
     POS_FIGHTING,
     NULL,
     SLOT(649),
     400,
     12,
     FALSE,
     "",
     "@@NThe @@rshield@@N shatters!!",
     "@@NThe @@rshield@@N protecting $n shatters!!"},

    {NORM,
     "summon pegasus",
     {LEVELS_INIT},
     spell_summon_pegasus,
     TAR_IGNORE,
     POS_STANDING,
     NULL,
     SLOT(659),
     1200,
     24,
     FALSE,
     "",
     "",
     ""},

    {NORM,
     "summon nightmare",
     {LEVELS_INIT},
     spell_summon_nightmare,
     TAR_IGNORE,
     POS_STANDING,
     NULL,
     SLOT(660),
     1200,
     24,
     FALSE,
     "",
     "",
     ""},

    {NORM,
     "summon beast",
     {LEVELS_INIT},
     spell_summon_beast,
     TAR_IGNORE,
     POS_STANDING,
     NULL,
     SLOT(661),
     1200,
     24,
     FALSE,
     "",
     "",
     ""},

    {NORM,
     "summon devourer",
     {LEVELS_INIT},
     spell_summon_devourer,
     TAR_IGNORE,
     POS_STANDING,
     NULL,
     SLOT(662),
     1200,
     24,
     FALSE,
     "",
     "",
     ""},

    {NORM,
     "summon shadow",
     {LEVELS_INIT},
     spell_summon_shadow,
     TAR_IGNORE,
     POS_STANDING,
     NULL,
     SLOT(663),
     1200,
     24,
     FALSE,
     "",
     "",
     ""},

    {NORM,
     "thought devourer",
     {LEVELS_INIT, L(CLASS_EGO, 65)},
     spell_summon_thought_devourer,
     TAR_IGNORE,
     POS_STANDING,
     NULL,
     SLOT(754),
     1200,
     24,
     FALSE,
     "",
     "",
     ""},

    {NORM,
     "creature bond",
     {LEVELS_INIT, L(CLASS_SOR, 77), L(CLASS_NEC, 55), L(CLASS_WIZ, 60)},
     spell_creature_bond,
     TAR_CHAR_DEFENSIVE,
     POS_FIGHTING,
     NULL,
     SLOT(664),
     100,
     12,
     FALSE,
     "",
     "",
     ""},

    {NORM,
     "corrupt bond",
     {LEVELS_INIT, L(CLASS_NEC, 33), L(CLASS_EGO, 50)},
     spell_corrupt_bond,
     TAR_CHAR_DEFENSIVE,
     POS_FIGHTING,
     NULL,
     SLOT(665),
     100,
     12,
     FALSE,
     "",
     "",
     ""},

    {NORM,
     "Fire Blast",
     {LEVELS_INIT, L(CLASS_SOR, 34), L(CLASS_NEC, 55)},
     spell_fireblast,
     TAR_CHAR_OFFENSIVE,
     POS_FIGHTING,
     NULL,
     SLOT(666),
     80,
     12,
     TRUE,
     "Fire Blast",
     "!Fire Blast!",
     ""},

    {NORM,
     "Shock Storm",
     {LEVELS_INIT, L(CLASS_SOR, 42), L(CLASS_NEC, 68), L(CLASS_EGO, 68)},
     spell_shockstorm,
     TAR_CHAR_OFFENSIVE,
     POS_FIGHTING,
     NULL,
     SLOT(667),
     100,
     12,
     TRUE,
     "Shock Storm",
     "!Shock Storm!",
     ""},

    {NORM,
     "Cone of cold",
     {LEVELS_INIT, L(CLASS_SOR, 56)},
     spell_cone_cold,
     TAR_CHAR_OFFENSIVE,
     POS_FIGHTING,
     NULL,
     SLOT(668),
     100,
     12,
     TRUE,
     "Cone of Cold",
     "!Cone of Cold!",
     ""},

    {NORM,
     "Earth Shatter",
     {LEVELS_INIT, L(CLASS_SOR, 60)},
     spell_earth_shatter,
     TAR_CHAR_OFFENSIVE,
     POS_FIGHTING,
     NULL,
     SLOT(690),
     100,
     12,
     TRUE,
     "Earth Shatter",
     "!Earth Shatter!",
     ""},

    {NORM,
     "arc lightning",
     {LEVELS_INIT, L(CLASS_WIZ, 30)},
     spell_arc_lightning,
     TAR_CHAR_OFFENSIVE,
     POS_FIGHTING,
     NULL,
     SLOT(682),
     120,
     12,
     TRUE,
     "arc lightning",
     "!arc lightning!",
     ""},

    {NORM,
     "terra rend",
     {LEVELS_INIT, L(CLASS_WIZ, 40)},
     spell_terra_rend,
     TAR_CHAR_OFFENSIVE,
     POS_FIGHTING,
     NULL,
     SLOT(683),
     120,
     12,
     TRUE,
     "terra rend",
     "!terra rend!",
     ""},

    {NORM,
     "tidal lash",
     {LEVELS_INIT, L(CLASS_WIZ, 50)},
     spell_tidal_lash,
     TAR_CHAR_OFFENSIVE,
     POS_FIGHTING,
     NULL,
     SLOT(684),
     120,
     12,
     TRUE,
     "tidal lash",
     "!tidal lash!",
     ""},

    {NORM,
     "phoenix flare",
     {LEVELS_INIT, L(CLASS_WIZ, 60)},
     spell_phoenix_flare,
     TAR_CHAR_OFFENSIVE,
     POS_FIGHTING,
     NULL,
     SLOT(685),
     120,
     12,
     TRUE,
     "phoenix flare",
     "!phoenix flare!",
     ""},

    {NORM,
     "elemental inferno",
     {LEVELS_INIT, L(CLASS_GMA, 1)},
     spell_elemental_inferno,
     TAR_CHAR_OFFENSIVE,
     POS_FIGHTING,
     NULL,
     SLOT(686),
     120,
     12,
     TRUE,
     "elemental inferno",
     "!elemental inferno!",
     ""},

    {NORM,
     "elemental shock",
     {LEVELS_INIT, L(CLASS_GMA, 5)},
     spell_elemental_shock,
     TAR_CHAR_OFFENSIVE,
     POS_FIGHTING,
     NULL,
     SLOT(687),
     120,
     12,
     TRUE,
     "elemental shock",
     "!elemental shock!",
     ""},

    {NORM,
     "elemental deluge",
     {LEVELS_INIT, L(CLASS_GMA, 10)},
     spell_elemental_deluge,
     TAR_CHAR_OFFENSIVE,
     POS_FIGHTING,
     NULL,
     SLOT(688),
     120,
     12,
     TRUE,
     "elemental deluge",
     "!elemental deluge!",
     ""},

    {NORM,
     "elemental rupture",
     {LEVELS_INIT, L(CLASS_GMA, 15)},
     spell_elemental_rupture,
     TAR_CHAR_OFFENSIVE,
     POS_FIGHTING,
     NULL,
     SLOT(689),
     120,
     12,
     TRUE,
     "elemental rupture",
     "!elemental rupture!",
     ""},

    {NORM,
     "Holy Wrath",
     {LEVELS_INIT, L(CLASS_PAL, 80), L(CLASS_PRI, 40)},
     spell_holy_wrath,
     TAR_CHAR_OFFENSIVE,
     POS_FIGHTING,
     NULL,
     SLOT(669),
     140,
     12,
     TRUE,
     "Holy Wrath",
     "!Holy Wrath!",
     ""},

    {NORM,
     "Wraith Touch",
     {LEVELS_INIT, L(CLASS_NEC, 46)},
     spell_wraith_touch,
     TAR_CHAR_OFFENSIVE,
     POS_FIGHTING,
     NULL,
     SLOT(670),
     120,
     12,
     TRUE,
     "Wraith Touch",
     "!Wraith Touch!",
     ""},

    {NORM,
     "Thought Vise",
     {LEVELS_INIT, L(CLASS_EGO, 70)},
     spell_thought_vise,
     TAR_CHAR_OFFENSIVE,
     POS_FIGHTING,
     NULL,
     SLOT(670),
     200,
     12,
     TRUE,
     "Thought Vise",
     "!Thought Vise!",
     ""},

    {NORM,
     "black curse",
     {LEVELS_INIT, L(CLASS_NEC, 65), L(CLASS_EGO, 65)},
     spell_black_curse,
     TAR_CHAR_OFFENSIVE,
     POS_FIGHTING,
     NULL,
     SLOT(0),
     120,
     12,
     TRUE,
     "Black Curse",
     "!Black Curse!",
     ""},

    {NORM,
     "spirit curse",
     {LEVELS_INIT, L(CLASS_NEC, 77), L(CLASS_EGO, 77)},
     spell_spirit_curse,
     TAR_CHAR_OFFENSIVE,
     POS_FIGHTING,
     NULL,
     SLOT(0),
     120,
     12,
     TRUE,
     "Spirit Curse",
     "!Spirit Curse!",
     ""},

    {NORM,
     "rictus curse",
     {LEVELS_INIT, L(CLASS_NEC, 100), L(CLASS_EGO, 100)},
     spell_rictus_curse,
     TAR_CHAR_OFFENSIVE,
     POS_FIGHTING,
     NULL,
     SLOT(0),
     120,
     12,
     TRUE,
     "Rictus Curse",
     "!Rictus Curse!",
     ""},

    {NORM,
     "Predictive Collapse",
     {LEVELS_INIT, L(CLASS_KIN, 2)},
     spell_predictive_collapse,
     TAR_CHAR_OFFENSIVE,
     POS_FIGHTING,
     NULL,
     SLOT(0),
     120,
     12,
     TRUE,
     "Predictive Collapse",
     "!Predictive Collapse!",
     ""},

    {NORM,
     "cloak:misery",
     {LEVELS_INIT, L(CLASS_ASS, 80), L(CLASS_NEC, 73), L(CLASS_WLK, 80), L(CLASS_EGO, 73)},
     spell_cloak_misery,
     TAR_CHAR_DEFENSIVE,
     POS_STANDING,
     NULL,
     SLOT(672),
     550,
     12,
     FALSE,
     "",
     "@@NThe @@Rcloak@@N around your body fades.",
     "@@NThe @@Rcloak@@N around $n's body fades."},

    {NORM,
     "cloak:drain",
     {LEVELS_INIT, L(CLASS_NEC, 48)},
     spell_cloak_drain,
     TAR_CHAR_DEFENSIVE,
     POS_STANDING,
     NULL,
     SLOT(677),
     550,
     12,
     FALSE,
     "",
     "@@NThe @@rcloak@@N around your body fades.",
     "@@NThe @@rcloak@@N around $n's body fades."},

    {NORM,
     "cloak:iron",
     {LEVELS_INIT, L(CLASS_KNI, 48)},
     spell_cloak_iron,
     TAR_CHAR_DEFENSIVE,
     POS_STANDING,
     NULL,
     SLOT(678),
     550,
     12,
     FALSE,
     "",
     "@@NThe @@Wcloak@@N around your body fades.",
     "@@NThe @@Wcloak@@N around $n's body fades."},

    {NORM,
     "cloak:mental",
     {LEVELS_INIT, L(CLASS_MON, 48)},
     spell_cloak_mental,
     TAR_CHAR_DEFENSIVE,
     POS_STANDING,
     NULL,
     SLOT(679),
     550,
     12,
     FALSE,
     "",
     "@@NThe @@mcloak@@N around your body fades.",
     "@@NThe @@mcloak@@N around $n's body fades."},

    {NORM,
     "cloak:oathbreaker",
     {LEVELS_INIT, L(CLASS_WLK, 48)},
     spell_cloak_oathbreaker,
     TAR_CHAR_DEFENSIVE,
     POS_STANDING,
     NULL,
     SLOT(680),
     550,
     12,
     FALSE,
     "",
     "@@NThe @@dcloak@@N around your body fades.",
     "@@NThe @@dcloak@@N around $n's body fades."},

    {NORM,
     "cloak:transcendence",
     {LEVELS_INIT, L(CLASS_ASS, 48)},
     spell_cloak_transcendence,
     TAR_CHAR_DEFENSIVE,
     POS_STANDING,
     NULL,
     SLOT(681),
     550,
     12,
     FALSE,
     "",
     "@@NThe @@Ccloak@@N around your body fades.",
     "@@NThe @@Ccloak@@N around $n's body fades."},

    {NORM,
     "cloak:precision",
     {LEVELS_INIT, L(CLASS_SWO, 48)},
     spell_cloak_precision,
     TAR_CHAR_DEFENSIVE,
     POS_STANDING,
     NULL,
     SLOT(769),
     550,
     12,
     FALSE,
     "",
     "@@NThe @@ycloak@@N around your body fades.",
     "@@NThe @@ycloak@@N around $n's body fades."},

    {NORM,
     "cloak:valor",
     {LEVELS_INIT, L(CLASS_PAL, 48)},
     spell_cloak_valor,
     TAR_CHAR_DEFENSIVE,
     POS_STANDING,
     NULL,
     SLOT(771),
     550,
     12,
     FALSE,
     "",
     "@@NThe @@Wcloak@@N around your body fades.",
     "@@NThe @@Wcloak@@N around $n's body fades."},

    /* Affect holder for cloak:valor guaranteed crit proc */
    {NORM,
     "valor_crit",
     {LEVELS_INIT},
     spell_null,
     TAR_IGNORE,
     POS_FIGHTING,
     NULL,
     SLOT(772),
     0,
     0,
     FALSE,
     "",
     "Your righteous fury fades.",
     "$n's righteous fury fades."},

    {NORM,
     "poison:quinine",
     {LEVELS_INIT, L(CLASS_ASS, 56), L(CLASS_WLK, 21)},
     spell_null,
     TAR_CHAR_OFFENSIVE,
     POS_FIGHTING,
     &gsn_poison_quinine,
     SLOT(673),
     80,
     12,
     TRUE,
     "Poison Quinine",
     "@@N$n feels much better!",
     ""},

    {NORM,
     "poison:arsenic",
     {LEVELS_INIT, L(CLASS_ASS, 66), L(CLASS_WLK, 28)},
     spell_null,
     TAR_CHAR_OFFENSIVE,
     POS_FIGHTING,
     &gsn_poison_arsenic,
     SLOT(674),
     80,
     12,
     TRUE,
     "Poison Arsenic",
     "@@N$nFeels much better!",
     ""},

    {NORM,
     "poison:nightshade",
     {LEVELS_INIT, L(CLASS_NIG, 2)},
     spell_null,
     TAR_CHAR_OFFENSIVE,
     POS_FIGHTING,
     &gsn_poison_nightshade,
     SLOT(0),
     80,
     12,
     TRUE,
     "Poison Nightshade",
     "@@N$nFeels much better!",
     ""},

    {NORM,
     "riposte",
     {LEVELS_INIT, L(CLASS_SWO, 30)},
     spell_null,
     TAR_CHAR_OFFENSIVE,
     POS_FIGHTING,
     &gsn_riposte,
     SLOT(0),
     80,
     12,
     TRUE,
     "Riposte",
     "You are no longer in a position to riposte!",
     "$n is no longer in a position to riposte."},

    {NORM,
     "cripple",
     {LEVELS_INIT, L(CLASS_ASS, 89), L(CLASS_WLK, 92)},
     spell_null,
     TAR_CHAR_OFFENSIVE,
     POS_FIGHTING,
     &gsn_cripple,
     SLOT(0),
     80,
     12,
     TRUE,
     "Cripple",
     "You are no longer crippled!",
     "$n is no longer crippled."},

    {NORM,
     "pummel",
     {LEVELS_INIT, L(CLASS_PUG, 66)},
     spell_null,
     TAR_CHAR_OFFENSIVE,
     POS_FIGHTING,
     &gsn_pummel,
     SLOT(0),
     80,
     12,
     TRUE,
     "Pummel",
     "!!Pummel!!",
     "!!$n Pummel!!"},

    {NORM,
     "aurabolt",
     {LEVELS_INIT, L(CLASS_MON, 34), L(CLASS_BRA, 41)},
     spell_null,
     TAR_CHAR_OFFENSIVE,
     POS_FIGHTING,
     &gsn_aurabolt,
     SLOT(0),
     80,
     12,
     TRUE,
     "Aurabolt",
     "!!Aurabolt!!",
     "!!$n Aurabolt!!"},

    {NORM,
     "chiblock",
     {LEVELS_INIT, L(CLASS_MON, 86), L(CLASS_BRA, 84)},
     spell_null,
     TAR_CHAR_OFFENSIVE,
     POS_FIGHTING,
     &gsn_chiblock,
     SLOT(0),
     80,
     12,
     TRUE,
     "Chiblock",
     "You are no longer able to block with your chi!",
     "$n is no longer able to block with their chi."},

    {NORM,
     "spinfist",
     {LEVELS_INIT, L(CLASS_BRA, 66)},
     spell_null,
     TAR_CHAR_OFFENSIVE,
     POS_FIGHTING,
     &gsn_spinfist,
     SLOT(0),
     80,
     12,
     TRUE,
     "Spinfist",
     "!!SPINFIST!!",
     "!!$n SPINFIST!!"},

    {NORM,
     "phantomfist",
     {LEVELS_INIT, L(CLASS_MON, 51), L(CLASS_BRA, 34)},
     spell_null,
     TAR_CHAR_DEFENSIVE,
     POS_FIGHTING,
     &gsn_phantomfist,
     SLOT(0),
     80,
     12,
     TRUE,
     "Phantomfist (bugged)",
     "You no longer move like a phantom",
     "$n no longer moves like a phantom."},

    {NORM,
     "Mind Over Body",
     {LEVELS_INIT, L(CLASS_PUG, 21)},
     spell_null,
     TAR_CHAR_OFFENSIVE,
     POS_FIGHTING,
     &gsn_mindoverbody,
     SLOT(0),
     80,
     24,
     TRUE,
     "Mind Over Body",
     "You lose your focus on your mind over your body",
     "$n loses focus on mind over body."},

    {NORM,
     "Flurry",
     {LEVELS_INIT, L(CLASS_PUG, 45)},
     spell_null,
     TAR_CHAR_OFFENSIVE,
     POS_FIGHTING,
     &gsn_flurry,
     SLOT(0),
     80,
     24,
     TRUE,
     "Flurry",
     "",
     ""},

    {NORM,
     "chakra",
     {LEVELS_INIT, L(CLASS_MON, 55)},
     spell_null,
     TAR_CHAR_OFFENSIVE,
     POS_FIGHTING,
     &gsn_chakra,
     SLOT(0),
     80,
     24,
     TRUE,
     "Chakra",
     "",
     ""},

    {NORM,
     "shieldblock",
     {LEVELS_INIT, L(CLASS_PAL, 83), L(CLASS_KNI, 57)},
     spell_null,
     TAR_CHAR_OFFENSIVE,
     POS_FIGHTING,
     &gsn_riposte,
     SLOT(0),
     80,
     12,
     TRUE,
     "Shieldblock",
     "You are no longer ready to shield block!",
     "$n is no longer ready to shield block."},

    {NORM,
     "fleche",
     {LEVELS_INIT, L(CLASS_SWO, 45)},
     spell_null,
     TAR_CHAR_OFFENSIVE,
     POS_FIGHTING,
     &gsn_fleche,
     SLOT(0),
     80,
     12,
     TRUE,
     "Fleche",
     "!Fleche!",
     ""},

    {NORM,
     "holystrike",
     {LEVELS_INIT, L(CLASS_PAL, 44), L(CLASS_KNI, 29)},
     spell_null,
     TAR_CHAR_OFFENSIVE,
     POS_FIGHTING,
     &gsn_holystrike,
     SLOT(0),
     80,
     12,
     TRUE,
     "Holystrike",
     "!Holystrike!",
     ""},

    {NORM,
     "anti magic shell",
     {LEVELS_INIT, L(CLASS_CRU, 2)},
     spell_null,
     TAR_CHAR_OFFENSIVE,
     POS_FIGHTING,
     &gsn_anti_magic_shell,
     SLOT(0),
     80,
     12,
     TRUE,
     "Anti Magic Shell",
     "You are no longer surrounded by an anti-magic shell!",
     "$n is no longer surrounded by an anti-magic shell."},

    /* Martial Artist adept skills */

    {NORM,
     "chi surge",
     {LEVELS_INIT, L(CLASS_MAR, 5)},
     spell_null,
     TAR_CHAR_OFFENSIVE,
     POS_FIGHTING,
     &gsn_chi_surge,
     SLOT(0),
     80,
     24,
     TRUE,
     "chi surge",
     "!chi surge!",
     ""},

    {NORM,
     "breath of endurance",
     {LEVELS_INIT, L(CLASS_MAR, 10)},
     spell_null,
     TAR_IGNORE,
     POS_FIGHTING,
     &gsn_breath_of_endurance,
     SLOT(0),
     0,
     24,
     FALSE,
     "",
     "Your breath of endurance fades.",
     "$n's sustained breathing returns to normal."},

    {NORM,
     "fist of the interior form",
     {LEVELS_INIT, L(CLASS_MAR, 15)},
     spell_null,
     TAR_CHAR_OFFENSIVE,
     POS_FIGHTING,
     &gsn_fist_interior,
     SLOT(0),
     80,
     24,
     TRUE,
     "Fist of the Interior Form",
     "!Fist of the Interior Form!",
     ""},

    /* Crusader adept skills */

    {NORM,
     "momentum chain",
     {LEVELS_INIT, L(CLASS_CRU, 5)},
     spell_null,
     TAR_IGNORE,
     POS_FIGHTING,
     &gsn_momentum_chain,
     SLOT(0),
     0,
     24,
     TRUE,
     "",
     "Your momentum fades.",
     "$n's building momentum fades."},

    {NORM,
     "veteran's cadence",
     {LEVELS_INIT, L(CLASS_CRU, 10)},
     spell_null,
     TAR_IGNORE,
     POS_FIGHTING,
     &gsn_veterans_cadence,
     SLOT(0),
     0,
     24,
     TRUE,
     "",
     "Your campaign cadence breaks.",
     "$n's campaign cadence breaks."},

    {NORM,
     "overwhelming assault",
     {LEVELS_INIT, L(CLASS_CRU, 15)},
     spell_null,
     TAR_CHAR_OFFENSIVE,
     POS_FIGHTING,
     &gsn_overwhelming_assault,
     SLOT(0),
     80,
     24,
     TRUE,
     "Overwhelming Assault",
     "!Overwhelming Assault!",
     ""},

    /* Grand Magi adept passive */

    {NORM,
     "elemental attunement",
     {LEVELS_INIT, L(CLASS_GMA, 3)},
     spell_null,
     TAR_IGNORE,
     POS_STANDING,
     &gsn_elemental_attunement,
     SLOT(0),
     0,
     0,
     FALSE,
     "",
     "!Elemental Attunement!",
     ""},

    /* Templar adept skills */

    {NORM,
     "oathshield",
     {LEVELS_INIT, L(CLASS_TEM, 10)},
     spell_null,
     TAR_CHAR_DEFENSIVE,
     POS_FIGHTING,
     &gsn_oathshield,
     SLOT(0),
     0,
     24,
     TRUE,
     "",
     "The oathshield fades.",
     "The oathshield around $n fades."},

    {NORM,
     "sanctified strike",
     {LEVELS_INIT, L(CLASS_TEM, 15)},
     spell_null,
     TAR_CHAR_OFFENSIVE,
     POS_FIGHTING,
     &gsn_sanctified_strike,
     SLOT(0),
     80,
     24,
     TRUE,
     "sanctified strike",
     "!Sanctified Strike!",
     ""},

    /* Nightblade adept skills */

    {NORM,
     "shadow reading",
     {LEVELS_INIT, L(CLASS_NIG, 5)},
     spell_null,
     TAR_IGNORE,
     POS_FIGHTING,
     &gsn_shadow_reading,
     SLOT(0),
     0,
     24,
     TRUE,
     "",
     "Your shadow-sight fades.",
     "$n's shadow-sight fades."},

    {NORM,
     "hex ward",
     {LEVELS_INIT, L(CLASS_NIG, 10)},
     spell_null,
     TAR_CHAR_OFFENSIVE,
     POS_FIGHTING,
     &gsn_hex_ward,
     SLOT(0),
     0,
     24,
     TRUE,
     "",
     "The hex ward eroding your defenses fades.",
     "The hex ward eroding $n's defenses fades."},

    {NORM,
     "reflex disruption",
     {LEVELS_INIT, L(CLASS_NIG, 15)},
     spell_null,
     TAR_CHAR_OFFENSIVE,
     POS_FIGHTING,
     &gsn_reflex_disruption,
     SLOT(0),
     0,
     24,
     TRUE,
     "",
     "Your reflexes return to normal.",
     "$n's reflexes return to normal."},

    {NORM,
     "sonic blast",
     {LEVELS_INIT, L(CLASS_EGO, 67)},
     spell_sonic_blast,
     TAR_CHAR_OFFENSIVE,
     POS_FIGHTING,
     NULL,
     SLOT(675),
     140,
     12,
     TRUE,
     "Sonic Blast",
     "@@N$nFeels much better!",
     ""},

    {NORM,
     "mystical potency",
     {LEVELS_INIT, L(CLASS_MAG, 20)},
     spell_null,
     TAR_IGNORE,
     POS_STANDING,
     &gsn_potency,
     SLOT(0),
     0,
     0,
     FALSE,
     "",
     "!Enhanced Damage!",
     ""},

    {NORM,
     "mystical focus",
     {LEVELS_INIT, L(CLASS_SOR, 55), L(CLASS_NEC, 48), L(CLASS_WIZ, 45), L(CLASS_EGO, 47)},
     spell_mystical_focus,
     TAR_CHAR_SELF,
     POS_STANDING,
     NULL,
     SLOT(676),
     200,
     10,
     TRUE,
     "",
     "Your lose your mystical focus.",
     "$N shakes his head, and seems less focused."},

    /* Cipher skills */
    {NORM,             "reach silence",   {LEVELS_INIT, L(CLASS_CIP, 30)},
     spell_null,       TAR_IGNORE,        POS_STANDING,
     &gsn_garrote,     SLOT(0),           1,
     24,               TRUE,              "reach silence",
     "!Reach Silence!", ""},

    {NORM,
     "feign death",
     {LEVELS_INIT, L(CLASS_CIP, 38)},
     spell_null,
     TAR_IGNORE,
     POS_STANDING,
     &gsn_feign_death,
     SLOT(0),
     0,
     24,
     TRUE,
     "",
     "!Feign Death!",
     ""},

    {NORM,
     "gap transit",
     {LEVELS_INIT, L(CLASS_CIP, 45)},
     spell_null,
     TAR_IGNORE,
     POS_STANDING,
     &gsn_shadow_step,
     SLOT(0),
     0,
     24,
     TRUE,
     "",
     "!Gap Transit!",
     ""},

    {NORM,
     "mark target",
     {LEVELS_INIT, L(CLASS_CIP, 15)},
     spell_null,
     TAR_IGNORE,
     POS_STANDING,
     &gsn_mark_target,
     SLOT(0),
     0,
     24,
     TRUE,
     "",
     "Your target mark fades.",
     ""},

    {NORM,         "conceal",  {LEVELS_INIT, L(CLASS_CIP, 8)},
     spell_null,   TAR_IGNORE, POS_STANDING,
     &gsn_conceal, SLOT(0),    0,
     12,           FALSE,      "",
     "!Conceal!",  ""},

    {NORM,
     "set trap",
     {LEVELS_INIT, L(CLASS_CIP, 35)},
     spell_null,
     TAR_IGNORE,
     POS_STANDING,
     &gsn_set_trap,
     SLOT(0),
     0,
     24,
     FALSE,
     "",
     "!Set Trap!",
     ""},

    {NORM,
     "read intent",
     {LEVELS_INIT, L(CLASS_CIP, 20), L(CLASS_WAR, 25), L(CLASS_SEN, 25)},
     spell_null,
     TAR_IGNORE,
     POS_STANDING,
     &gsn_read_intent,
     SLOT(0),
     0,
     24,
     TRUE,
     "",
     "Your combat awareness fades.",
     ""},

    /* Warden skills */
    {NORM,        "cleave",   {LEVELS_INIT, L(CLASS_WAR, 25)},
     spell_null,  TAR_IGNORE, POS_FIGHTING,
     &gsn_cleave, SLOT(0),    0,
     24,          TRUE,       "cleave",
     "!Cleave!",  ""},

    {NORM,
     "seven shade hold",
     {LEVELS_INIT, L(CLASS_WAR, 22), L(CLASS_SEN, 32)},
     spell_null,
     TAR_IGNORE,
     POS_STANDING,
     &gsn_fortify,
     SLOT(0),
     0,
     24,
     TRUE,
     "",
     "You release the Seven Shade Hold.",
     ""},

    {NORM,       "taunt",    {LEVELS_INIT, L(CLASS_WAR, 12)},
     spell_null, TAR_IGNORE, POS_STANDING,
     &gsn_taunt, SLOT(0),    0,
     18,         TRUE,       "taunt",
     "!Taunt!",  ""},

    {NORM,       "rend",     {LEVELS_INIT, L(CLASS_WAR, 36)},
     spell_null, TAR_IGNORE, POS_FIGHTING,
     &gsn_rend,  SLOT(0),    1,
     24,         TRUE,       "rend",
     "!Rend!",   ""},

    {NORM,
     "field patch",
     {LEVELS_INIT, L(CLASS_WAR, 30)},
     spell_null,
     TAR_IGNORE,
     POS_STANDING,
     &gsn_field_patch,
     SLOT(0),
     0,
     24,
     TRUE,
     "",
     "!Field Patch!",
     ""},

    {NORM,
     "weapon mastery",
     {LEVELS_INIT, L(CLASS_WAR, 5), L(CLASS_PUG, 15), L(CLASS_SEN, 5)},
     spell_null,
     TAR_IGNORE,
     POS_STANDING,
     &gsn_weapon_mastery,
     SLOT(0),
     0,
     24,
     FALSE,
     "",
     "Your weapon mastery fades.",
     ""},

    /* Pugilist skills */
    {NORM,         "grapple",  {LEVELS_INIT, L(CLASS_PUG, 15)},
     spell_null,   TAR_IGNORE, POS_FIGHTING,
     &gsn_grapple, SLOT(0),    1,
     18,           TRUE,       "grapple",
     "!Grapple!",  ""},

    {NORM,
     "choke hold",
     {LEVELS_INIT, L(CLASS_PUG, 30)},
     spell_null,
     TAR_IGNORE,
     POS_FIGHTING,
     &gsn_choke_hold,
     SLOT(0),
     1,
     24,
     TRUE,
     "choke hold",
     "!Choke Hold!",
     ""},

    {NORM,
     "leg sweep",
     {LEVELS_INIT, L(CLASS_PUG, 18)},
     spell_null,
     TAR_IGNORE,
     POS_FIGHTING,
     &gsn_leg_sweep,
     SLOT(0),
     1,
     18,
     TRUE,
     "leg sweep",
     "!Leg Sweep!",
     ""},

    {NORM,
     "iron skin",
     {LEVELS_INIT, L(CLASS_PUG, 22)},
     spell_null,
     TAR_IGNORE,
     POS_STANDING,
     &gsn_iron_skin,
     SLOT(0),
     0,
     24,
     FALSE,
     "",
     "Your iron skin fades.",
     ""},

    {NORM,
     "roll with blow",
     {LEVELS_INIT, L(CLASS_PUG, 12)},
     spell_null,
     TAR_IGNORE,
     POS_STANDING,
     &gsn_roll_with_blow,
     SLOT(0),
     0,
     24,
     FALSE,
     "",
     "Your fluid stance fades.",
     ""},

    {NORM,
     "applied understanding",
     {LEVELS_INIT, L(CLASS_PUG, 35)},
     spell_null,
     TAR_IGNORE,
     POS_FIGHTING,
     &gsn_pressure_point,
     SLOT(0),
     1,
     24,
     TRUE,
     "applied understanding",
     "!Applied Understanding!",
     ""},

    {NORM,
     "feint",
     {LEVELS_INIT, L(CLASS_PUG, 25)},
     spell_null,
     TAR_IGNORE,
     POS_FIGHTING,
     &gsn_feint,
     SLOT(0),
     0,
     18,
     TRUE,
     "",
     "Your feint bonus fades.",
     ""},

    {NORM,
     "conditioning",
     {LEVELS_INIT, L(CLASS_PUG, 5), L(CLASS_SEN, 5)},
     spell_null,
     TAR_IGNORE,
     POS_STANDING,
     &gsn_conditioning,
     SLOT(0),
     0,
     24,
     FALSE,
     "",
     "Your conditioning fades.",
     ""},

    /* Druid skills */
    {NORM,
     "substrate piercing",
     {LEVELS_INIT, L(CLASS_DRU, 20)},
     spell_null,
     TAR_IGNORE,
     POS_STANDING,
     &gsn_substrate_piercing,
     SLOT(0),
     0,
     0,
     FALSE,
     "",
     "!Substrate Piercing!",
     ""},

    /* Sentinel skills */
    {NORM,
     "vigilance",
     {LEVELS_INIT},
     spell_null,
     TAR_IGNORE,
     POS_STANDING,
     &gsn_vigilance,
     SLOT(0),
     0,
     0,
     FALSE,
     "",
     "!Vigilance!",
     ""},

    {NORM,
     "verdict",
     {LEVELS_INIT, L(CLASS_SEN, 20)},
     spell_null,
     TAR_CHAR_OFFENSIVE,
     POS_FIGHTING,
     &gsn_verdict,
     SLOT(0),
     0,
     24,
     TRUE,
     "verdict",
     "!Verdict!",
     ""},

    {NORM,
     "read opponent",
     {LEVELS_INIT, L(CLASS_SEN, 10)},
     spell_null,
     TAR_CHAR_OFFENSIVE,
     POS_FIGHTING,
     &gsn_read_opponent,
     SLOT(0),
     8,
     24,
     TRUE,
     "",
     "You lose your read on your opponent.",
     ""},

    {NORM,
     "binding strike",
     {LEVELS_INIT, L(CLASS_SEN, 22)},
     spell_null,
     TAR_CHAR_OFFENSIVE,
     POS_FIGHTING,
     &gsn_binding_strike,
     SLOT(0),
     5,
     18,
     TRUE,
     "binding strike",
     "Your movements are no longer impaired.",
     "$n's movements are no longer impaired."},

    {NORM,
     "testimonial guard",
     {LEVELS_INIT, L(CLASS_SEN, 12)},
     spell_null,
     TAR_IGNORE,
     POS_STANDING,
     &gsn_testimonial_guard,
     SLOT(0),
     0,
     0,
     FALSE,
     "",
     "!Testimonial Guard!",
     ""},

    {NORM,
     "ninth descent",
     {LEVELS_INIT, L(CLASS_SEN, 35)},
     spell_null,
     TAR_IGNORE,
     POS_FIGHTING,
     &gsn_ninth_descent,
     SLOT(0),
     25,
     12,
     TRUE,
     "",
     "Your heightened awareness fades.",
     ""},

    {NORM,
     "measured response",
     {LEVELS_INIT, L(CLASS_SEN, 30)},
     spell_null,
     TAR_IGNORE,
     POS_FIGHTING,
     &gsn_measured_response,
     SLOT(0),
     0,
     0,
     FALSE,
     "measured response",
     "!Measured Response!",
     ""},

    {NORM,
     "condemn",
     {LEVELS_INIT, L(CLASS_SEN, 45)},
     spell_null,
     TAR_CHAR_OFFENSIVE,
     POS_FIGHTING,
     &gsn_condemn,
     SLOT(0),
     15,
     24,
     TRUE,
     "",
     "The weight of condemnation lifts from you.",
     "$n is no longer condemned."},

    {NORM,
     "seal testimony",
     {LEVELS_INIT, L(CLASS_SEN, 50)},
     spell_null,
     TAR_IGNORE,
     POS_FIGHTING,
     &gsn_seal_testimony,
     SLOT(0),
     10,
     12,
     TRUE,
     "",
     "Your sealed testimony fades.",
     ""},
