
/*
 * Fighter and thief skills.
 */

{NORM,
 "appraise",
 {NO_USE, NO_USE, 12,     NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE,
  NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE},
 spell_null,
 TAR_IGNORE,
 POS_STANDING,
 &gsn_appraise,
 SLOT(0),
 0,
 24,
 FALSE,
 "",
 "!Appraise!",
 ""},

    {NORM,
     "bash",
     {NO_USE, NO_USE, NO_USE, 28,     NO_USE, NO_USE, NO_USE, NO_USE,
      NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE,
      NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE},
     spell_null,
     TAR_IGNORE,
     POS_FIGHTING,
     &gsn_bash,
     SLOT(0),
     0,
     24,
     TRUE,
     "bash",
     "!bash!",
     ""},

    {NORM,
     "berserk",
     {NO_USE, NO_USE, NO_USE, 34,     NO_USE, NO_USE, NO_USE, NO_USE,
      NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE,
      NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE},
     spell_null,
     TAR_IGNORE,
     POS_FIGHTING,
     &gsn_beserk,
     SLOT(0),
     0,
     24,
     TRUE,
     "berserk",
     "You calm down!",
     "$n looks calmer!"},

    {NORM,
     "climb",
     {NO_USE, NO_USE, 25,     NO_USE, NO_USE, NO_USE, NO_USE, NO_USE,
      NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE,
      NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE},
     spell_null,
     TAR_IGNORE,
     POS_FIGHTING,
     &gsn_climb,
     SLOT(0),
     0,
     24,
     FALSE,
     "",
     "!Climb!",
     ""},

    {NORM,
     "dirt",
     {NO_USE, NO_USE, 36,     35,     NO_USE, 47,     NO_USE, NO_USE,
      NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE,
      NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE},
     spell_null,
     TAR_IGNORE,
     POS_FIGHTING,
     &gsn_dirt,
     SLOT(0),
     1,
     24,
     TRUE,
     "",
     "!dirt!",
     ""},

    {NORM,
     "nodisarm",
     {NO_USE, NO_USE, 40,     30,     NO_USE, NO_USE, NO_USE, NO_USE,
      NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE,
      NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE},
     spell_null,
     TAR_IGNORE,
     POS_FIGHTING,
     &gsn_nodisarm,
     SLOT(0),
     0,
     0,
     FALSE,
     "",
     "!nodisarm!",
     ""},

    {NORM,
     "smash",
     {NO_USE, NO_USE, NO_USE, 30,     NO_USE, NO_USE, NO_USE, NO_USE,
      NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE,
      NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE},
     spell_null,
     TAR_IGNORE,
     POS_STANDING,
     &gsn_smash,
     SLOT(0),
     0,
     0,
     FALSE,
     "",
     "!smash!",
     ""},

    {NORM,
     "steal",
     {NO_USE, NO_USE, 20,     NO_USE, NO_USE, NO_USE, NO_USE, NO_USE,
      NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE,
      NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE},
     spell_null,
     TAR_IGNORE,
     POS_FIGHTING,
     &gsn_steal,
     SLOT(0),
     1,
     18,
     TRUE,
     "steal",
     "!steal!",
     ""},

    {NORM,
     "circle",
     {NO_USE, NO_USE, 19,     NO_USE, NO_USE, NO_USE, NO_USE, NO_USE,
      NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE,
      NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE},
     spell_null,
     TAR_IGNORE,
     POS_FIGHTING,
     &gsn_circle,
     SLOT(0),
     1,
     18,
     TRUE,
     "circle",
     "!circle!",
     ""},

    {NORM,
     "backstab",
     {NO_USE, NO_USE, 10,     NO_USE, NO_USE, NO_USE, NO_USE, NO_USE,
      NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE,
      NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE},
     spell_null,
     TAR_IGNORE,
     POS_STANDING,
     &gsn_backstab,
     SLOT(0),
     1,
     18,
     TRUE,
     "backstab",
     "!Backstab!",
     ""},

    {NORM,
     "disarm",
     {NO_USE, NO_USE, 53,     12,     NO_USE, NO_USE, NO_USE, NO_USE,
      NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE,
      NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE},
     spell_null,
     TAR_IGNORE,
     POS_FIGHTING,
     &gsn_disarm,
     SLOT(0),
     1,
     18,
     TRUE,
     "",
     "!Disarm!",
     ""},

    {NORM,
     "dodge",
     {NO_USE, NO_USE, 7,      NO_USE, NO_USE, 27,     NO_USE, NO_USE,
      NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE,
      NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE},
     spell_null,
     TAR_IGNORE,
     POS_FIGHTING,
     &gsn_dodge,
     SLOT(0),
     0,
     0,
     FALSE,
     "",
     "!Dodge!",
     ""},

    {NORM,
     "dualwield",
     {NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE,
      5,      NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, 5,      NO_USE,
      NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE},
     spell_null,
     TAR_IGNORE,
     POS_FIGHTING,
     &gsn_dualwield,
     SLOT(0),
     0,
     0,
     FALSE,
     "",
     "!DualWield!",
     ""},

    {NORM,
     "enhanced damage",
     {NO_USE, NO_USE, NO_USE, 20,     NO_USE, NO_USE, NO_USE, NO_USE,
      NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE,
      NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE},
     spell_null,
     TAR_IGNORE,
     POS_FIGHTING,
     &gsn_enhanced_damage,
     SLOT(0),
     0,
     0,
     FALSE,
     "",
     "!Enhanced Damage!",
     ""},

    {NORM,
     "equip buckler",
     {NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, 1,
      NO_USE, 1,      NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, 1,
      NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE},
     spell_null,
     TAR_IGNORE,
     POS_FIGHTING,
     &gsn_equip_buckler,
     SLOT(0),
     0,
     0,
     FALSE,
     "",
     "!Equip Buckler!",
     ""},

    {NORM,
     "equip fist",
     {NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE,
      NO_USE, NO_USE, NO_USE, 1,      NO_USE, NO_USE, NO_USE, NO_USE,
      NO_USE, 1,      NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE},
     spell_null,
     TAR_IGNORE,
     POS_FIGHTING,
     &gsn_equip_fist,
     SLOT(0),
     0,
     0,
     FALSE,
     "",
     "!Equip Fist!",
     ""},

    {NORM,
     "dual fist",
     {NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE,
      NO_USE, NO_USE, NO_USE, 35,     NO_USE, NO_USE, NO_USE, NO_USE,
      NO_USE, 35,     NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE},
     spell_null,
     TAR_IGNORE,
     POS_FIGHTING,
     &gsn_dual_fist,
     SLOT(0),
     0,
     0,
     FALSE,
     "",
     "!Dual Fist!",
     ""},

    {NORM,
     "equip wand",
     {NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, 1,      NO_USE,
      NO_USE, NO_USE, 1,      NO_USE, 1,      1,      NO_USE, NO_USE,
      1,      NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE},
     spell_null,
     TAR_IGNORE,
     POS_FIGHTING,
     &gsn_equip_wand,
     SLOT(0),
     0,
     0,
     FALSE,
     "",
     "!Equip Wand!",
     ""},

    {NORM,
     "flee timer",
     {NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE,
      NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE,
      NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE},
     spell_null,
     TAR_IGNORE,
     POS_STANDING,
     &gsn_flee_timer,
     SLOT(0),
     0,
     24,
     FALSE,
     "",
     "Your anti-flee timer has expired!",
     ""},

    {NORM,
     "find doors",
     {NO_USE, NO_USE, 16,     NO_USE, NO_USE, NO_USE, NO_USE, NO_USE,
      NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE,
      NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE},
     spell_null,
     TAR_IGNORE,
     POS_FIGHTING,
     &gsn_find_doors,
     SLOT(0),
     0,
     0,
     FALSE,
     "",
     "!Find Doors!",
     ""},

    {NORM,
     "counter",
     {NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, 20,     NO_USE, NO_USE,
      NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE,
      NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE},
     spell_null,
     TAR_IGNORE,
     POS_FIGHTING,
     &gsn_counter,
     SLOT(0),
     0,
     0,
     FALSE,
     "counter",
     "!Counter!",
     ""},

    {NORM,
     "enhanced critical",
     {NO_USE, NO_USE, 20,     NO_USE, NO_USE, NO_USE, NO_USE, NO_USE,
      NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE,
      NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE},
     spell_null,
     TAR_IGNORE,
     POS_FIGHTING,
     &gsn_enhanced_critical,
     SLOT(0),
     0,
     0,
     FALSE,
     "",
     "!Enhanced Crit!",
     ""},

    {NORM,
     "enhanced heal",
     {NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE,
      NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE,
      NO_USE, NO_USE, NO_USE, 1,      NO_USE, NO_USE, NO_USE, NO_USE},
     spell_null,
     TAR_IGNORE,
     POS_FIGHTING,
     &gsn_enhanced_heal,
     SLOT(0),
     0,
     0,
     FALSE,
     "",
     "!Enhanced Heal!",
     ""},

    {NORM,
     "enhanced purify",
     {NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE,
      NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE,
      44,     NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE},
     spell_null,
     TAR_IGNORE,
     POS_FIGHTING,
     &gsn_enhanced_purify,
     SLOT(0),
     0,
     0,
     FALSE,
     "",
     "!Enhanced Purify!",
     ""},

    {NORM,
     "spell critical",
     {NO_USE, NO_USE, NO_USE, NO_USE, 20,     NO_USE, NO_USE, NO_USE,
      NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE,
      NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE},
     spell_null,
     TAR_IGNORE,
     POS_FIGHTING,
     &gsn_spell_critical,
     SLOT(0),
     0,
     0,
     FALSE,
     "",
     "!Spell Crit!",
     ""},

    {NORM,
     "spell critical damage",
     {NO_USE, 20,     NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE,
      NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE,
      NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE},
     spell_null,
     TAR_IGNORE,
     POS_FIGHTING,
     &gsn_spell_critical_damage,
     SLOT(0),
     0,
     0,
     FALSE,
     "",
     "!Spell Critical Damage!",
     ""},

    {NORM,
     "headbutt",
     {NO_USE, NO_USE, NO_USE, 6,      NO_USE, NO_USE, NO_USE, NO_USE,
      NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE,
      NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE},
     spell_null,
     TAR_CHAR_OFFENSIVE,
     POS_FIGHTING,
     &gsn_headbutt,
     SLOT(0),
     1,
     18,
     TRUE,
     "headbutt",
     "!HeadButt!",
     ""},

    {NORM,
     "hide",
     {NO_USE, NO_USE, 12,     NO_USE, NO_USE, NO_USE, NO_USE, NO_USE,
      NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE,
      NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE},
     spell_null,
     TAR_IGNORE,
     POS_RESTING,
     &gsn_hide,
     SLOT(0),
     0,
     12,
     FALSE,
     "",
     "!Hide!",
     ""},

    {NORM,
     "hunt",
     {NO_USE, NO_USE, 70,     NO_USE, NO_USE, NO_USE, NO_USE, NO_USE,
      NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE,
      NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE},
     spell_null,
     TAR_IGNORE,
     POS_RESTING,
     &gsn_hunt,
     SLOT(0),
     0,
     12,
     FALSE,
     "",
     "!Hunt!",
     ""},

    {NORM,
     "kick",
     {NO_USE, NO_USE, NO_USE, 14,     NO_USE, NO_USE, NO_USE, NO_USE,
      NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE,
      NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE},
     spell_null,
     TAR_CHAR_OFFENSIVE,
     POS_FIGHTING,
     &gsn_kick,
     SLOT(0),
     1,
     18,
     TRUE,
     "kick",
     "!Kick!",
     ""},

    {NORM,
     "knee",
     {NO_USE, NO_USE, NO_USE, 8,      NO_USE, NO_USE, NO_USE, NO_USE,
      NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE,
      NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE},
     spell_null,
     TAR_CHAR_OFFENSIVE,
     POS_FIGHTING,
     &gsn_knee,
     SLOT(0),
     1,
     18,
     TRUE,
     "knee",
     "!Knee",
     ""},

    {NORM,
     "detox",
     {NO_USE, NO_USE, 27,     NO_USE, NO_USE, NO_USE, NO_USE, NO_USE,
      NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE,
      NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE},
     spell_null,
     TAR_IGNORE,
     POS_STANDING,
     &gsn_detox,
     SLOT(0),
     0,
     24,
     FALSE,
     "detox",
     "!Detox",
     ""},

    {NORM,
     "martial arts",
     {NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, 10,     NO_USE, NO_USE,
      NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE,
      NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE},
     spell_null,
     TAR_IGNORE,
     POS_FIGHTING,
     &gsn_martial_arts,
     SLOT(0),
     0,
     0,
     FALSE,
     "",
     "!Martial Arts!",
     ""},

    {NORM,
     "parry",
     {NO_USE, NO_USE, 52,     10,     NO_USE, NO_USE, NO_USE, NO_USE,
      NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE,
      NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE},
     spell_null,
     TAR_IGNORE,
     POS_FIGHTING,
     &gsn_parry,
     SLOT(0),
     0,
     0,
     FALSE,
     "",
     "!Parry!",
     ""},

    {NORM,
     "peek",
     {NO_USE, NO_USE, 20,     NO_USE, NO_USE, NO_USE, NO_USE, NO_USE,
      NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE,
      NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE},
     spell_null,
     TAR_IGNORE,
     POS_STANDING,
     &gsn_peek,
     SLOT(0),
     0,
     0,
     FALSE,
     "",
     "!Peek!",
     ""},

    {NORM,
     "pick lock",
     {NO_USE, NO_USE, 25,     NO_USE, NO_USE, NO_USE, NO_USE, NO_USE,
      NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE,
      NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE},
     spell_null,
     TAR_IGNORE,
     POS_STANDING,
     &gsn_pick_lock,
     SLOT(0),
     0,
     12,
     FALSE,
     "",
     "!Pick!",
     ""},

    {NORM,
     "punch",
     {NO_USE, NO_USE, NO_USE, 5,      NO_USE, NO_USE, NO_USE, NO_USE,
      NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE,
      NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE},
     spell_null,
     TAR_IGNORE,
     POS_STANDING,
     &gsn_punch,
     SLOT(0),
     1,
     18,
     TRUE,
     "punch",
     "!Punch!",
     ""},

    {NORM,
     "rescue",
     {NO_USE, NO_USE, NO_USE, 15,     NO_USE, NO_USE, NO_USE, NO_USE,
      NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE,
      NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE},
     spell_null,
     TAR_IGNORE,
     POS_FIGHTING,
     &gsn_rescue,
     SLOT(0),
     0,
     12,
     FALSE,
     "",
     "!Rescue!",
     ""},

    {NORM,
     "shadowform",
     {NO_USE, NO_USE, NO_USE, NO_USE, 9,      NO_USE, NO_USE, NO_USE,
      NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE,
      NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE},
     spell_null,
     TAR_IGNORE,
     POS_STANDING,
     &gsn_shadow,
     SLOT(0),
     0,
     0,
     FALSE,
     "",
     NULL,
     ""},

    {NORM,
     "shield block",
     {NO_USE, NO_USE, NO_USE, 40,     NO_USE, 18,     NO_USE, NO_USE,
      NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE,
      NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE},
     spell_null,
     TAR_IGNORE,
     POS_STANDING,
     &gsn_shield_block,
     SLOT(0),
     0,
     12,
     FALSE,
     "",
     "!Shield Block!",
     ""},

    {NORM,
     "sneak",
     {NO_USE, NO_USE, 5,      NO_USE, NO_USE, NO_USE, NO_USE, NO_USE,
      NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE,
      NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE},
     spell_null,
     TAR_IGNORE,
     POS_STANDING,
     &gsn_sneak,
     SLOT(0),
     0,
     12,
     FALSE,
     "",
     NULL,
     ""},

    {NORM,
     "stun",
     {NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE,
      NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE,
      NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE},
     spell_null,
     TAR_IGNORE,
     POS_FIGHTING,
     &gsn_stun,
     SLOT(0),
     0,
     24,
     FALSE,
     "",
     "",
     ""},

    {NORM,
     "disguise",
     {NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE,
      25,     NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, 25,     NO_USE,
      NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE},
     spell_null,
     TAR_IGNORE,
     POS_STANDING,
     &gsn_disguise,
     SLOT(0),
     0,
     0,
     FALSE,
     "",
     "!Disguise!",
     ""},

    {NORM,
     "frenzy",
     {NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE,
      NO_USE, 27,     NO_USE, NO_USE, NO_USE, 41,     NO_USE, 28,
      NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE},
     spell_null,
     TAR_CHAR_OFFENSIVE,
     POS_FIGHTING,
     &gsn_frenzy,
     SLOT(0),
     0,
     24,
     FALSE,
     "frenzy",
     "!FRENZY!",
     ""},

    {NORM,
     "warcry",
     {NO_USE, NO_USE, NO_USE, 10,     NO_USE, NO_USE, NO_USE, NO_USE,
      NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE,
      NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE},
     spell_null,
     TAR_IGNORE,
     POS_STANDING,
     &gsn_warcry,
     SLOT(0),
     0,
     24,
     TRUE,
     "warcry",
     "!Warcry!",
     ""},

    {NORM,
     "emotion control",
     {NO_USE, NO_USE, NO_USE, NO_USE, 75,     NO_USE, NO_USE, NO_USE,
      NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE,
      NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE},
     spell_null,
     TAR_CHAR_OFFENSIVE,
     POS_FIGHTING,
     &gsn_emotion_control,
     SLOT(0),
     0,
     24,
     FALSE,
     "emotion control",
     "!EMOTION CONTROL!",
     ""},

    /*
     *  Spells for mega1.are from Glop/Erkenbrand.
     */
    {NORM,
     "general purpose",
     {NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE,
      NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE,
      NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE},
     spell_general_purpose,
     TAR_CHAR_OFFENSIVE,
     POS_FIGHTING,
     NULL,
     SLOT(205),
     0,
     12,
     FALSE,
     "general purpose ammo",
     "!General Purpose Ammo!",
     ""},

    {NORM,
     "high explosive",
     {NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE,
      NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE,
      NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE},
     spell_high_explosive,
     TAR_CHAR_OFFENSIVE,
     POS_FIGHTING,
     NULL,
     SLOT(206),
     0,
     12,
     FALSE,
     "high explosive ammo",
     "!High Explosive Ammo!",
     ""},

    {NORM,
     "deflect weapon",
     {NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE,
      NO_USE, NO_USE, 22,     NO_USE, NO_USE, NO_USE, NO_USE, NO_USE,
      22,     NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE},
     spell_deflect_weapon,
     TAR_CHAR_DEFENSIVE,
     POS_STANDING,
     NULL,
     SLOT(600),
     25,
     12,
     TRUE,
     "",
     "Your mind shield melts away.",
     ""},

    {NORM,
     "black hand",
     {NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE,
      NO_USE, NO_USE, 7,      NO_USE, NO_USE, NO_USE, NO_USE, NO_USE,
      7,      NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE},
     spell_black_hand,
     TAR_CHAR_OFFENSIVE,
     POS_FIGHTING,
     NULL,
     SLOT(601),
     50,
     12,
     TRUE,
     "Black Hand",
     "The hand dissolves from around your throat into nothingness.",
     ""},
    {NORM,
     "throwing needle",
     {NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE,
      NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, 7,      NO_USE,
      NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE},
     spell_throw_needle,
     TAR_CHAR_OFFENSIVE,
     POS_FIGHTING,
     NULL,
     SLOT(602),
     40,
     12,
     TRUE,
     "Throwing Needle",
     "!Throwing Needle!",
     ""},

    {NORM,
     "morale",
     {NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, 21,
      NO_USE, 10,     NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE,
      NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE},
     spell_null,
     TAR_IGNORE,
     POS_STANDING,
     &gsn_morale,
     SLOT(0),
     75,
     24,
     TRUE,
     "Morale",
     "!Morale!",
     ""},

    {NORM,
     "leadership",
     {NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, 24,
      NO_USE, 12,     NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE,
      NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE},
     spell_null,
     TAR_IGNORE,
     POS_STANDING,
     &gsn_leadership,
     SLOT(0),
     75,
     24,
     TRUE,
     "Leadership",
     "!Leadership!",
     ""},

    {NORM,
     "two handed",
     {NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, 8,
      NO_USE, 6,      NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, 6,
      NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE},
     spell_null,
     TAR_IGNORE,
     POS_FIGHTING,
     &gsn_two_handed,
     SLOT(0),
     0,
     0,
     FALSE,
     "",
     "!Two Handed!",
     ""},

    {NORM,
     "palmstrike",
     {NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE,
      NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE,
      NO_USE, 19,     NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE},
     spell_null,
     TAR_CHAR_OFFENSIVE,
     POS_FIGHTING,
     &gsn_palmstrike,
     SLOT(0),
     0,
     0,
     TRUE,
     "Palmstrike",
     "!Palm Strike!",
     ""},

    {NORM,
     "bare hand",
     {NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE,
      NO_USE, NO_USE, NO_USE, 6,      NO_USE, NO_USE, NO_USE, NO_USE,
      NO_USE, 6,      NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE},
     spell_null,
     TAR_IGNORE,
     POS_FIGHTING,
     &gsn_bare_hand,
     SLOT(0),
     0,
     0,
     FALSE,
     "",
     "!Enhanced Sword!",
     ""},

    {NORM,
     "enhanced sword damage",
     {NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE,
      NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, 20,
      NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE},
     spell_null,
     TAR_IGNORE,
     POS_FIGHTING,
     &gsn_enhanced_sword,
     SLOT(0),
     0,
     0,
     FALSE,
     "",
     "!Enhanced Sword!",
     ""},

    {NORM,
     "enhanced sword critical",
     {NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE,
      NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, 40,
      NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE},
     spell_null,
     TAR_IGNORE,
     POS_FIGHTING,
     &gsn_enhanced_sword_critical,
     SLOT(0),
     0,
     0,
     FALSE,
     "",
     "!Enhanced Sword Critical!",
     ""},

    {NORM,
     "Ice Bolt",
     {NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, 3,      NO_USE,
      NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE,
      NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE},
     spell_ice_bolt,
     TAR_CHAR_OFFENSIVE,
     POS_FIGHTING,
     NULL,
     SLOT(605),
     20,
     12,
     TRUE,
     "Ice Bolt",
     "!Ice Bolt!",
     ""},
    {NORM,
     "water elemental",
     {NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, 6,      NO_USE,
      NO_USE, NO_USE, NO_USE, NO_USE, 6,      NO_USE, NO_USE, NO_USE,
      NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE},
     spell_waterelem,
     TAR_IGNORE,
     POS_STANDING,
     NULL,
     SLOT(606),
     80,
     24,
     FALSE,
     "",
     "!Stalker!",
     ""},
    {NORM,
     "skeleton",
     {NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE,
      NO_USE, NO_USE, 9,      NO_USE, NO_USE, NO_USE, NO_USE, NO_USE,
      9,      NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE},
     spell_skeleton,
     TAR_IGNORE,
     POS_STANDING,
     NULL,
     SLOT(607),
     80,
     24,
     FALSE,
     "",
     "!Stalker!",
     ""},
    {NORM,
     "poison weapon",
     {NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE,
      25,     NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, 5,      NO_USE,
      NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE},
     spell_poison_weapon,
     TAR_OBJ_INV,
     POS_STANDING,
     NULL,
     SLOT(608),
     100,
     24,
     FALSE,
     "",
     "!Enchant Weapon!",
     ""},

    {NORM,
     "adrenaline",
     {NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, 42,
      NO_USE, 21,     NO_USE, 28,     NO_USE, 42,     NO_USE, 21,
      NO_USE, 28,     NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE},
     spell_null,
     TAR_IGNORE,
     POS_FIGHTING,
     &gsn_adrenaline,
     SLOT(0),
     0,
     0,
     FALSE,
     "",
     "!ADRENALINE!",
     ""},

    {NORM,
     "throwing star",
     {NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE,
      43,     NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, 12,     NO_USE,
      NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE},
     spell_throw_needle,
     TAR_CHAR_OFFENSIVE,
     POS_FIGHTING,
     NULL,
     SLOT(628),
     85,
     12,
     TRUE,
     "Throwing Star",
     "!Throwing Star!",
     ""},

    /* THIS IS A SPELL AFFECT HOLDER FOR THE SKILL ADRENALINE..DO NOT CAST! */

    {NORM,
     "adrenaline bonus",
     {NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE,
      NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE,
      NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE},
     spell_null,
     TAR_IGNORE,
     POS_FIGHTING,
     NULL,
     SLOT(612),
     0,
     0,
     FALSE,
     "",
     "!ADRENALINE BONUS!",
     ""},

    {NORM,
     "fire elemental",
     {NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, 11,     NO_USE,
      NO_USE, NO_USE, NO_USE, NO_USE, 11,     NO_USE, NO_USE, NO_USE,
      NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE},
     spell_fireelem,
     TAR_IGNORE,
     POS_STANDING,
     NULL,
     SLOT(612),
     120,
     24,
     FALSE,
     "",
     "!FIRE ELEMENTAL!",
     ""},
    {NORM,
     "rune:fire",
     {NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, 40,     NO_USE,
      NO_USE, NO_USE, NO_USE, NO_USE, 40,     NO_USE, NO_USE, NO_USE,
      NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE},
     spell_rune_fire,
     TAR_IGNORE,
     POS_STANDING,
     NULL,
     SLOT(613),
     150,
     12,
     FALSE,
     "",
     "The rune dissipates.",
     ""},

    {NORM,
     "rune:shock",
     {NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, 56,     NO_USE,
      NO_USE, NO_USE, 15,     NO_USE, 56,     NO_USE, NO_USE, NO_USE,
      15,     NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE},
     spell_rune_shock,
     TAR_IGNORE,
     POS_STANDING,
     NULL,
     SLOT(614),
     150,
     12,
     FALSE,
     "",
     "The rune dissipates.",
     ""},

    {NORM,
     "rune:poison",
     {NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE,
      38,     NO_USE, 40,     NO_USE, NO_USE, NO_USE, 8,      NO_USE,
      NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE},
     spell_rune_poison,
     TAR_IGNORE,
     POS_STANDING,
     NULL,
     SLOT(615),
     80,
     12,
     FALSE,
     "",
     "The rune dissipates.",
     ""},

    {NORM,
     "healing light",
     {NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, 42,
      NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, 11,     NO_USE, NO_USE,
      NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE},
     spell_healing_light,
     TAR_IGNORE,
     POS_STANDING,
     NULL,
     SLOT(616),
     150,
     12,
     FALSE,
     "",
     "@@NThe @@mHealing Light@@N dissipates.",
     ""},

    {NORM,
     "withering shadow",
     {NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE,
      NO_USE, 17,     NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, 17,
      NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE},
     spell_wither_shadow,
     TAR_IGNORE,
     POS_STANDING,
     NULL,
     SLOT(617),
     150,
     12,
     FALSE,
     "",
     "@@NThe @@dWithering Shadow@@N dissipates.",
     ""},

    {NORM,
     "mana flare",
     {NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, 18,     NO_USE,
      NO_USE, NO_USE, NO_USE, NO_USE, 18,     NO_USE, NO_USE, NO_USE,
      NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE},
     spell_mana_flare,
     TAR_IGNORE,
     POS_STANDING,
     NULL,
     SLOT(618),
     80,
     12,
     FALSE,
     "",
     "@@NThe @@eMana Flare@@N dissipates.",
     ""},

    {NORM,
     "mana drain",
     {NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, 11,     NO_USE,
      NO_USE, NO_USE, 15,     NO_USE, 11,     NO_USE, NO_USE, NO_USE,
      15,     NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE},
     spell_mana_drain,
     TAR_IGNORE,
     POS_STANDING,
     NULL,
     SLOT(619),
     150,
     12,
     FALSE,
     "",
     "@@NThe @@dMana Drain@@N dissipates.",
     ""},

    {NORM,
     "cage",
     {NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, 18,     31,
      40,     19,     13,     NO_USE, 18,     31,     40,     19,
      13,     NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE},
     spell_cage,
     TAR_IGNORE,
     POS_STANDING,
     NULL,
     SLOT(620),
     150,
     12,
     FALSE,
     "",
     "@@NThe @@rCage@@N dissipates.",
     ""},

    {NORM,
     "room dispel",
     {NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, 22,     NO_USE,
      NO_USE, NO_USE, 34,     NO_USE, 22,     NO_USE, NO_USE, NO_USE,
      34,     NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE},
     spell_room_dispel,
     TAR_IGNORE,
     POS_STANDING,
     NULL,
     SLOT(625),
     120,
     12,
     FALSE,
     "",
     "",
     ""},

    {NORM,
     "soul net",
     {NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE,
      NO_USE, NO_USE, 58,     NO_USE, NO_USE, NO_USE, NO_USE, NO_USE,
      58,     NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE},
     spell_soul_net,
     TAR_IGNORE,
     POS_STANDING,
     NULL,
     SLOT(629),
     350,
     12,
     FALSE,
     "",
     "@@NThe @@dSoul Net@@N dissipates.",
     ""},

    {NORM,
     "condense soul",
     {NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE,
      NO_USE, NO_USE, 78,     NO_USE, NO_USE, NO_USE, NO_USE, NO_USE,
      78,     NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE},
     spell_condense_soul,
     TAR_OBJ_INV,
     POS_STANDING,
     NULL,
     SLOT(630),
     800,
     24,
     FALSE,
     "",
     "!Soul Potion!",
     ""},

    {NORM,
     "restoration",
     {NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE,
      NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE,
      NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE},
     spell_restoration,
     TAR_CHAR_DEFENSIVE,
     POS_FIGHTING,
     NULL,
     SLOT(632),
     50,
     12,
     FALSE,
     "",
     "!restoration!",
     ""},

    {NORM,
     "infuse",
     {NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE,
      NO_USE, NO_USE, 71,     NO_USE, NO_USE, NO_USE, NO_USE, NO_USE,
      71,     NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE},
     spell_infuse,
     TAR_OBJ_INV,
     POS_STANDING,
     NULL,
     SLOT(633),
     1000,
     24,
     FALSE,
     "",
     "!Infuse Soul!",
     ""},

    {NORM,
     "holy light",
     {NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, 43,
      NO_USE, NO_USE, NO_USE, NO_USE, 82,     14,     NO_USE, NO_USE,
      NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE},
     spell_holy_light,
     TAR_IGNORE,
     POS_STANDING,
     NULL,
     SLOT(634),
     75,
     24,
     FALSE,
     "Holy Light",
     "!Holy Light!",
     ""},

    {NORM,
     "target",
     {NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, 32,
      NO_USE, 20,     NO_USE, 18,     NO_USE, 32,     NO_USE, 20,
      NO_USE, 18,     NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE},
     spell_null,
     TAR_CHAR_OFFENSIVE,
     POS_FIGHTING,
     &gsn_target,
     SLOT(0),
     0,
     24,
     FALSE,
     "target",
     "!target",
     ""},

    {NORM,
     "charge",
     {NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, 89,
      NO_USE, 30,     NO_USE, NO_USE, NO_USE, 89,     NO_USE, 30,
      NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE},
     spell_null,
     TAR_CHAR_OFFENSIVE,
     POS_FIGHTING,
     &gsn_charge,
     SLOT(0),
     1,
     24,
     TRUE,
     "Charge",
     "!Charge",
     ""},

    {NORM,
     "scout",
     {NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, 45,
      26,     30,     NO_USE, 43,     NO_USE, 45,     26,     30,
      NO_USE, 43,     NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE},
     spell_null,
     TAR_IGNORE,
     POS_STANDING,
     &gsn_scout,
     SLOT(0),
     0,
     0,
     FALSE,
     "",
     "",
     ""},
    {NORM,
     "divine intervention",
     {NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, 67,
      NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, 12,     NO_USE, NO_USE,
      NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE},
     spell_divine_intervention,
     TAR_CHAR_DEFENSIVE,
     POS_FIGHTING,
     NULL,
     SLOT(635),
     150,
     12,
     TRUE,
     "",
     "!Intervention!",
     ""},

    {NORM,
     "holy armor",
     {NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, 30,
      NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, 19,     NO_USE, NO_USE,
      NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE},
     spell_holy_armor,
     TAR_CHAR_DEFENSIVE,
     POS_STANDING,
     NULL,
     SLOT(636),
     100,
     12,
     FALSE,
     "",
     "Your armor is no longer blessed.",
     ""},

    {NORM,
     "unit tactics",
     {NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE,
      NO_USE, 16,     NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, 16,
      NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE},
     spell_null,
     TAR_IGNORE,
     POS_STANDING,
     &gsn_unit_tactics,
     SLOT(0),
     0,
     24,
     FALSE,
     "Unit Tactics",
     "!Unit Tactics!",
     ""},

    {NORM,
     "earth elemental",
     {NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, 52,     NO_USE,
      NO_USE, NO_USE, NO_USE, NO_USE, 52,     NO_USE, NO_USE, NO_USE,
      NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE},
     spell_earthelem,
     TAR_IGNORE,
     POS_STANDING,
     NULL,
     SLOT(637),
     500,
     24,
     FALSE,
     "",
     "!EARTH ELEMENTAL!",
     ""},

    {NORM,
     "iron golem",
     {NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, 63,     NO_USE,
      NO_USE, NO_USE, NO_USE, NO_USE, 63,     NO_USE, NO_USE, NO_USE,
      NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE},
     spell_iron_golem,
     TAR_IGNORE,
     POS_STANDING,
     NULL,
     SLOT(638),
     800,
     24,
     FALSE,
     "",
     "!IRON GOLEM!",
     ""},

    {NORM,
     "diamond golem",
     {NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, 77,     NO_USE,
      NO_USE, NO_USE, NO_USE, NO_USE, 77,     NO_USE, NO_USE, NO_USE,
      NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE},
     spell_diamond_golem,
     TAR_IGNORE,
     POS_STANDING,
     NULL,
     SLOT(639),
     1100,
     24,
     FALSE,
     "",
     "!DIAMOND GOLEM!",
     ""},
    {NORM,
     "soul thief",
     {NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE,
      NO_USE, NO_USE, 67,     NO_USE, NO_USE, NO_USE, NO_USE, NO_USE,
      67,     NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE},
     spell_soul_thief,
     TAR_IGNORE,
     POS_STANDING,
     NULL,
     SLOT(640),
     900,
     24,
     FALSE,
     "",
     "!SOUL THIEF!",
     ""},
    {NORM,
     "holy avenger",
     {NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, 76,
      NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, 76,     NO_USE, NO_USE,
      NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE},
     spell_holy_avenger,
     TAR_IGNORE,
     POS_STANDING,
     NULL,
     SLOT(641),
     1200,
     24,
     FALSE,
     "",
     "!HOLY AVENGER!",
     ""},
    {NORM,
     "heat armor",
     {NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, 57,     NO_USE,
      NO_USE, NO_USE, 78,     NO_USE, 57,     NO_USE, NO_USE, NO_USE,
      78,     NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE},
     spell_heat_armor,
     TAR_CHAR_OFFENSIVE,
     POS_FIGHTING,
     NULL,
     SLOT(642),
     350,
     12,
     TRUE,
     "Heat Armor",
     "!Heat Armor!",
     ""},

    {NORM,
     "Retributive Strike",
     {NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, 72,     NO_USE,
      NO_USE, NO_USE, 78,     NO_USE, 72,     NO_USE, NO_USE, NO_USE,
      78,     NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE},
     spell_retri_strike,
     TAR_IGNORE,
     POS_FIGHTING,
     NULL,
     SLOT(643),
     800,
     12,
     TRUE,
     "Retributive strike",
     "!Retributive Strike!",
     ""},

    {NORM,
     "Lava Burst",
     {NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, 40,     NO_USE,
      NO_USE, NO_USE, NO_USE, NO_USE, 40,     NO_USE, NO_USE, NO_USE,
      NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE},
     spell_lava_burst,
     TAR_CHAR_OFFENSIVE,
     POS_FIGHTING,
     NULL,
     SLOT(644),
     350,
     12,
     TRUE,
     "Lava Burst",
     "!Lava Burst!",
     ""},

    {NORM,
     "fireshield",
     {NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, 80,     NO_USE,
      NO_USE, NO_USE, NO_USE, NO_USE, 80,     NO_USE, NO_USE, NO_USE,
      NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE},
     spell_fireshield,
     TAR_CHAR_DEFENSIVE,
     POS_FIGHTING,
     NULL,
     SLOT(645),
     400,
     12,
     FALSE,
     "",
     "",
     ""},

    {NORM,
     "iceshield",
     {NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, 65,     NO_USE,
      NO_USE, NO_USE, NO_USE, NO_USE, 65,     NO_USE, NO_USE, NO_USE,
      NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE},
     spell_iceshield,
     TAR_CHAR_DEFENSIVE,
     POS_FIGHTING,
     NULL,
     SLOT(646),
     350,
     12,
     FALSE,
     "",
     "",
     ""},

    {NORM,
     "shockshield",
     {NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, 55,     NO_USE,
      NO_USE, NO_USE, NO_USE, NO_USE, 55,     NO_USE, NO_USE, NO_USE,
      NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE},
     spell_shockshield,
     TAR_CHAR_DEFENSIVE,
     POS_FIGHTING,
     NULL,
     SLOT(647),
     400,
     12,
     FALSE,
     "",
     "",
     ""},

    {NORM,
     "shadowshield",
     {NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE,
      NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE,
      NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE},
     spell_shadowshield,
     TAR_CHAR_DEFENSIVE,
     POS_FIGHTING,
     NULL,
     SLOT(648),
     400,
     12,
     FALSE,
     "",
     "@@NThe @@rshield@@N shatters!!",
     "@@NThe @@rshield@@N protecting $n shatters!!"},
    {NORM,
     "thoughtshield",
     {NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE,
      NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE,
      NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE},
     spell_thoughtshield,
     TAR_CHAR_DEFENSIVE,
     POS_FIGHTING,
     NULL,
     SLOT(649),
     400,
     12,
     FALSE,
     "",
     "@@NThe @@rshield@@N shatters!!",
     "@@NThe @@rshield@@N protecting $n shatters!!"},

    {NORM,
     "summon pegasus",
     {NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE,
      NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE,
      NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE},
     spell_summon_pegasus,
     TAR_IGNORE,
     POS_STANDING,
     NULL,
     SLOT(659),
     1200,
     24,
     FALSE,
     "",
     "",
     ""},

    {NORM,
     "summon nightmare",
     {NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE,
      NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE,
      NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE},
     spell_summon_nightmare,
     TAR_IGNORE,
     POS_STANDING,
     NULL,
     SLOT(660),
     1200,
     24,
     FALSE,
     "",
     "",
     ""},

    {NORM,
     "summon beast",
     {NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE,
      NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE,
      NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE},
     spell_summon_beast,
     TAR_IGNORE,
     POS_STANDING,
     NULL,
     SLOT(661),
     1200,
     24,
     FALSE,
     "",
     "",
     ""},

    {NORM,
     "summon devourer",
     {NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE,
      NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE,
      NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE},
     spell_summon_devourer,
     TAR_IGNORE,
     POS_STANDING,
     NULL,
     SLOT(662),
     1200,
     24,
     FALSE,
     "",
     "",
     ""},

    {NORM,
     "summon shadow",
     {NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE,
      NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE,
      NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE},
     spell_summon_shadow,
     TAR_IGNORE,
     POS_STANDING,
     NULL,
     SLOT(663),
     1200,
     24,
     FALSE,
     "",
     "",
     ""},

    {NORM,
     "thought devourer",
     {NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE,
      NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE,
      65,     NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE},
     spell_summon_thought_devourer,
     TAR_IGNORE,
     POS_STANDING,
     NULL,
     SLOT(754),
     1200,
     24,
     FALSE,
     "",
     "",
     ""},

    {NORM,
     "creature bond",
     {NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, 77,     NO_USE,
      NO_USE, NO_USE, 55,     NO_USE, 60,     NO_USE, NO_USE, NO_USE,
      NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE},
     spell_creature_bond,
     TAR_CHAR_DEFENSIVE,
     POS_FIGHTING,
     NULL,
     SLOT(664),
     100,
     12,
     FALSE,
     "",
     "",
     ""},

    {NORM,
     "corrupt bond",
     {NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE,
      NO_USE, NO_USE, 33,     NO_USE, NO_USE, NO_USE, NO_USE, NO_USE,
      50,     NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE},
     spell_corrupt_bond,
     TAR_CHAR_DEFENSIVE,
     POS_FIGHTING,
     NULL,
     SLOT(665),
     100,
     12,
     FALSE,
     "",
     "",
     ""},

    {NORM,
     "Fire Blast",
     {NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, 34,     NO_USE,
      NO_USE, NO_USE, 55,     NO_USE, NO_USE, NO_USE, NO_USE, NO_USE,
      NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE},
     spell_fireblast,
     TAR_CHAR_OFFENSIVE,
     POS_FIGHTING,
     NULL,
     SLOT(666),
     80,
     12,
     TRUE,
     "Fire Blast",
     "!Fire Blast!",
     ""},

    {NORM,
     "Shock Storm",
     {NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, 42,     NO_USE,
      NO_USE, NO_USE, 68,     NO_USE, NO_USE, NO_USE, NO_USE, NO_USE,
      68,     NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE},
     spell_shockstorm,
     TAR_CHAR_OFFENSIVE,
     POS_FIGHTING,
     NULL,
     SLOT(667),
     100,
     12,
     TRUE,
     "Shock Storm",
     "!Shock Storm!",
     ""},

    {NORM,
     "Cone of cold",
     {NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, 56,     NO_USE,
      NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE,
      NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE},
     spell_cone_cold,
     TAR_CHAR_OFFENSIVE,
     POS_FIGHTING,
     NULL,
     SLOT(668),
     100,
     12,
     TRUE,
     "Cone of Cold",
     "!Cone of Cold!",
     ""},

    {NORM,
     "Earth Shatter",
     {NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, 60,     NO_USE,
      NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE,
      NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE},
     spell_earth_shatter,
     TAR_CHAR_OFFENSIVE,
     POS_FIGHTING,
     NULL,
     SLOT(690),
     100,
     12,
     TRUE,
     "Earth Shatter",
     "!Earth Shatter!",
     ""},

    {NORM,
     "arc lightning",
     {NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE,
      NO_USE, NO_USE, NO_USE, NO_USE, 30,     NO_USE, NO_USE, NO_USE,
      NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE},
     spell_arc_lightning,
     TAR_CHAR_OFFENSIVE,
     POS_FIGHTING,
     NULL,
     SLOT(682),
     120,
     12,
     TRUE,
     "arc lightning",
     "!arc lightning!",
     ""},

    {NORM,
     "terra rend",
     {NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE,
      NO_USE, NO_USE, NO_USE, NO_USE, 40,     NO_USE, NO_USE, NO_USE,
      NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE},
     spell_terra_rend,
     TAR_CHAR_OFFENSIVE,
     POS_FIGHTING,
     NULL,
     SLOT(683),
     120,
     12,
     TRUE,
     "terra rend",
     "!terra rend!",
     ""},

    {NORM,
     "tidal lash",
     {NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE,
      NO_USE, NO_USE, NO_USE, NO_USE, 50,     NO_USE, NO_USE, NO_USE,
      NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE},
     spell_tidal_lash,
     TAR_CHAR_OFFENSIVE,
     POS_FIGHTING,
     NULL,
     SLOT(684),
     120,
     12,
     TRUE,
     "tidal lash",
     "!tidal lash!",
     ""},

    {NORM,
     "phoenix flare",
     {NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE,
      NO_USE, NO_USE, NO_USE, NO_USE, 60,     NO_USE, NO_USE, NO_USE,
      NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE},
     spell_phoenix_flare,
     TAR_CHAR_OFFENSIVE,
     POS_FIGHTING,
     NULL,
     SLOT(685),
     120,
     12,
     TRUE,
     "phoenix flare",
     "!phoenix flare!",
     ""},

    {NORM,
     "elemental inferno",
     {NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE,
      NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE,
      NO_USE, NO_USE, 1,      NO_USE, NO_USE, NO_USE, NO_USE, NO_USE},
     spell_elemental_inferno,
     TAR_CHAR_OFFENSIVE,
     POS_FIGHTING,
     NULL,
     SLOT(686),
     120,
     12,
     TRUE,
     "elemental inferno",
     "!elemental inferno!",
     ""},

    {NORM,
     "elemental shock",
     {NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE,
      NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE,
      NO_USE, NO_USE, 5,      NO_USE, NO_USE, NO_USE, NO_USE, NO_USE},
     spell_elemental_shock,
     TAR_CHAR_OFFENSIVE,
     POS_FIGHTING,
     NULL,
     SLOT(687),
     120,
     12,
     TRUE,
     "elemental shock",
     "!elemental shock!",
     ""},

    {NORM,
     "elemental deluge",
     {NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE,
      NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE,
      NO_USE, NO_USE, 10,     NO_USE, NO_USE, NO_USE, NO_USE, NO_USE},
     spell_elemental_deluge,
     TAR_CHAR_OFFENSIVE,
     POS_FIGHTING,
     NULL,
     SLOT(688),
     120,
     12,
     TRUE,
     "elemental deluge",
     "!elemental deluge!",
     ""},

    {NORM,
     "elemental rupture",
     {NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE,
      NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE,
      NO_USE, NO_USE, 15,     NO_USE, NO_USE, NO_USE, NO_USE, NO_USE},
     spell_elemental_rupture,
     TAR_CHAR_OFFENSIVE,
     POS_FIGHTING,
     NULL,
     SLOT(689),
     120,
     12,
     TRUE,
     "elemental rupture",
     "!elemental rupture!",
     ""},

    {NORM,
     "Holy Wrath",
     {NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, 80,
      NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, 40,     NO_USE, NO_USE,
      NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE},
     spell_holy_wrath,
     TAR_CHAR_OFFENSIVE,
     POS_FIGHTING,
     NULL,
     SLOT(669),
     140,
     12,
     TRUE,
     "Holy Wrath",
     "!Holy Wrath!",
     ""},

    {NORM,
     "Wraith Touch",
     {NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE,
      NO_USE, NO_USE, 46,     NO_USE, NO_USE, NO_USE, NO_USE, NO_USE,
      NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE},
     spell_wraith_touch,
     TAR_CHAR_OFFENSIVE,
     POS_FIGHTING,
     NULL,
     SLOT(670),
     120,
     12,
     TRUE,
     "Wraith Touch",
     "!Wraith Touch!",
     ""},

    {NORM,
     "Thought Vise",
     {NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE,
      NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE,
      70,     NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE},
     spell_thought_vise,
     TAR_CHAR_OFFENSIVE,
     POS_FIGHTING,
     NULL,
     SLOT(670),
     200,
     12,
     TRUE,
     "Thought Vise",
     "!Thought Vise!",
     ""},

    {NORM,
     "black curse",
     {NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE,
      NO_USE, NO_USE, 65,     NO_USE, NO_USE, NO_USE, NO_USE, NO_USE,
      65,     NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE},
     spell_black_curse,
     TAR_CHAR_OFFENSIVE,
     POS_FIGHTING,
     NULL,
     SLOT(0),
     120,
     12,
     TRUE,
     "Black Curse",
     "!Black Curse!",
     ""},

    {NORM,
     "spirit curse",
     {NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE,
      NO_USE, NO_USE, 77,     NO_USE, NO_USE, NO_USE, NO_USE, NO_USE,
      77,     NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE},
     spell_spirit_curse,
     TAR_CHAR_OFFENSIVE,
     POS_FIGHTING,
     NULL,
     SLOT(0),
     120,
     12,
     TRUE,
     "Spirit Curse",
     "!Spirit Curse!",
     ""},

    {NORM,
     "rictus curse",
     {NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE,
      NO_USE, NO_USE, 100,    NO_USE, NO_USE, NO_USE, NO_USE, NO_USE,
      100,    NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE},
     spell_rictus_curse,
     TAR_CHAR_OFFENSIVE,
     POS_FIGHTING,
     NULL,
     SLOT(0),
     120,
     12,
     TRUE,
     "Rictus Curse",
     "!Rictus Curse!",
     ""},

    {NORM,
     "Kinetic Reversion",
     {NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE,
      NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE,
      NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, 2,      NO_USE},
     spell_kinetic_reversion,
     TAR_CHAR_OFFENSIVE,
     POS_FIGHTING,
     NULL,
     SLOT(0),
     120,
     12,
     TRUE,
     "Kinetic Reversion",
     "!Kinetic Reversion!",
     ""},

    {NORM,
     "cloak:misery",
     {NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE,
      80,     NO_USE, 73,     NO_USE, NO_USE, NO_USE, 80,     NO_USE,
      73,     NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE},
     spell_cloak_misery,
     TAR_CHAR_DEFENSIVE,
     POS_STANDING,
     NULL,
     SLOT(672),
     550,
     12,
     FALSE,
     "",
     "@@NThe @@Rcloak@@N around your body fades.",
     "@@NThe @@Rcloak@@N around $n's body fades."},

    {NORM,
     "cloak:drain",
     {NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE,
      NO_USE, NO_USE, 48,     NO_USE, NO_USE, NO_USE, NO_USE, NO_USE,
      NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE},
     spell_cloak_drain,
     TAR_CHAR_DEFENSIVE,
     POS_STANDING,
     NULL,
     SLOT(677),
     550,
     12,
     FALSE,
     "",
     "@@NThe @@rcloak@@N around your body fades.",
     "@@NThe @@rcloak@@N around $n's body fades."},

    {NORM,
     "cloak:iron",
     {NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE,
      NO_USE, 48,     NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE,
      NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE},
     spell_cloak_iron,
     TAR_CHAR_DEFENSIVE,
     POS_STANDING,
     NULL,
     SLOT(678),
     550,
     12,
     FALSE,
     "",
     "@@NThe @@Wcloak@@N around your body fades.",
     "@@NThe @@Wcloak@@N around $n's body fades."},

    {NORM,
     "cloak:mental",
     {NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE,
      NO_USE, NO_USE, NO_USE, 48,     NO_USE, NO_USE, NO_USE, NO_USE,
      NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE},
     spell_cloak_mental,
     TAR_CHAR_DEFENSIVE,
     POS_STANDING,
     NULL,
     SLOT(679),
     550,
     12,
     FALSE,
     "",
     "@@NThe @@mcloak@@N around your body fades.",
     "@@NThe @@mcloak@@N around $n's body fades."},

    {NORM,
     "cloak:oathbreaker",
     {NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE,
      NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, 48,     NO_USE,
      NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE},
     spell_cloak_oathbreaker,
     TAR_CHAR_DEFENSIVE,
     POS_STANDING,
     NULL,
     SLOT(680),
     550,
     12,
     FALSE,
     "",
     "@@NThe @@dcloak@@N around your body fades.",
     "@@NThe @@dcloak@@N around $n's body fades."},

    {NORM,
     "cloak:transcendence",
     {NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE,
      48,     NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE,
      NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE},
     spell_cloak_transcendence,
     TAR_CHAR_DEFENSIVE,
     POS_STANDING,
     NULL,
     SLOT(681),
     550,
     12,
     FALSE,
     "",
     "@@NThe @@Ccloak@@N around your body fades.",
     "@@NThe @@Ccloak@@N around $n's body fades."},

    {NORM,
     "poison:quinine",
     {NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE,
      56,     NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, 21,     NO_USE,
      NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE},
     spell_null,
     TAR_CHAR_OFFENSIVE,
     POS_FIGHTING,
     &gsn_poison_quinine,
     SLOT(673),
     80,
     12,
     TRUE,
     "Poison Quinine",
     "@@N$n feels much better!",
     ""},

    {NORM,
     "poison:arsenic",
     {NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE,
      66,     NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, 28,     NO_USE,
      NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE},
     spell_null,
     TAR_CHAR_OFFENSIVE,
     POS_FIGHTING,
     &gsn_poison_arsenic,
     SLOT(674),
     80,
     12,
     TRUE,
     "Poison Arsenic",
     "@@N$nFeels much better!",
     ""},

    {NORM,
     "poison:nightshade",
     {NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE,
      NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE,
      NO_USE, NO_USE, NO_USE, NO_USE, 2,      NO_USE, NO_USE, NO_USE},
     spell_null,
     TAR_CHAR_OFFENSIVE,
     POS_FIGHTING,
     &gsn_poison_nightshade,
     SLOT(0),
     80,
     12,
     TRUE,
     "Poison Nightshade",
     "@@N$nFeels much better!",
     ""},

    {NORM,
     "riposte",
     {NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE,
      NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, 30,
      NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE},
     spell_null,
     TAR_CHAR_OFFENSIVE,
     POS_FIGHTING,
     &gsn_riposte,
     SLOT(0),
     80,
     12,
     TRUE,
     "Riposte",
     "You are no longer in a position to riposte!",
     "$n is no longer in a position to riposte."},

    {NORM,
     "cripple",
     {NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE,
      89,     NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, 92,     NO_USE,
      NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE},
     spell_null,
     TAR_CHAR_OFFENSIVE,
     POS_FIGHTING,
     &gsn_cripple,
     SLOT(0),
     80,
     12,
     TRUE,
     "Cripple",
     "You are no longer crippled!",
     "$n is no longer crippled."},

    {NORM,
     "pummel",
     {NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, 66,     NO_USE, NO_USE,
      NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE,
      NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE},
     spell_null,
     TAR_CHAR_OFFENSIVE,
     POS_FIGHTING,
     &gsn_pummel,
     SLOT(0),
     80,
     12,
     TRUE,
     "Pummel",
     "!!Pummel!!",
     "!!$n Pummel!!"},

    {NORM,
     "aurabolt",
     {NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE,
      NO_USE, NO_USE, NO_USE, 34,     NO_USE, NO_USE, NO_USE, NO_USE,
      NO_USE, 41,     NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE},
     spell_null,
     TAR_CHAR_OFFENSIVE,
     POS_FIGHTING,
     &gsn_aurabolt,
     SLOT(0),
     80,
     12,
     TRUE,
     "Aurabolt",
     "!!Aurabolt!!",
     "!!$n Aurabolt!!"},

    {NORM,
     "chiblock",
     {NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE,
      NO_USE, NO_USE, NO_USE, 86,     NO_USE, NO_USE, NO_USE, NO_USE,
      NO_USE, 84,     NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE},
     spell_null,
     TAR_CHAR_OFFENSIVE,
     POS_FIGHTING,
     &gsn_chiblock,
     SLOT(0),
     80,
     12,
     TRUE,
     "Chiblock",
     "You are no longer able to block with your chi!",
     "$n is no longer able to block with their chi."},

    {NORM,
     "spinfist",
     {NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE,
      NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE,
      NO_USE, 66,     NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE},
     spell_null,
     TAR_CHAR_OFFENSIVE,
     POS_FIGHTING,
     &gsn_spinfist,
     SLOT(0),
     80,
     12,
     TRUE,
     "Spinfist",
     "!!SPINFIST!!",
     "!!$n SPINFIST!!"},

    {NORM,
     "phantomfist",
     {NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE,
      NO_USE, NO_USE, NO_USE, 51,     NO_USE, NO_USE, NO_USE, NO_USE,
      NO_USE, 34,     NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE},
     spell_null,
     TAR_CHAR_DEFENSIVE,
     POS_FIGHTING,
     &gsn_phantomfist,
     SLOT(0),
     80,
     12,
     TRUE,
     "Phantomfist (bugged)",
     "You no longer move like a phantom",
     "$n no longer moves like a phantom."},

    {NORM,
     "Mind Over Body",
     {NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, 21,     NO_USE, NO_USE,
      NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE,
      NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE},
     spell_null,
     TAR_CHAR_OFFENSIVE,
     POS_FIGHTING,
     &gsn_mindoverbody,
     SLOT(0),
     80,
     24,
     TRUE,
     "Mind Over Body",
     "You lose your focus on your mind over your body",
     "$n loses focus on mind over body."},

    {NORM,
     "Flurry",
     {NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, 45,     NO_USE, NO_USE,
      NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE,
      NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE},
     spell_null,
     TAR_CHAR_OFFENSIVE,
     POS_FIGHTING,
     &gsn_flurry,
     SLOT(0),
     80,
     24,
     TRUE,
     "Flurry",
     "",
     ""},

    {NORM,
     "chakra",
     {NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE,
      NO_USE, NO_USE, NO_USE, 55,     NO_USE, NO_USE, NO_USE, NO_USE,
      NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE},
     spell_null,
     TAR_CHAR_OFFENSIVE,
     POS_FIGHTING,
     &gsn_chakra,
     SLOT(0),
     80,
     24,
     TRUE,
     "Chakra",
     "",
     ""},

    {NORM,
     "shieldblock",
     {NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, 83,
      NO_USE, 57,     NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE,
      NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE},
     spell_null,
     TAR_CHAR_OFFENSIVE,
     POS_FIGHTING,
     &gsn_riposte,
     SLOT(0),
     80,
     12,
     TRUE,
     "Shieldblock",
     "You are no longer ready to shield block!",
     "$n is no longer ready to shield block."},

    {NORM,
     "fleche",
     {NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE,
      NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, 45,
      NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE},
     spell_null,
     TAR_CHAR_OFFENSIVE,
     POS_FIGHTING,
     &gsn_fleche,
     SLOT(0),
     80,
     12,
     TRUE,
     "Fleche",
     "!Fleche!",
     ""},

    {NORM,
     "holystrike",
     {NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, 44,
      NO_USE, 29,     NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE,
      NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE},
     spell_null,
     TAR_CHAR_OFFENSIVE,
     POS_FIGHTING,
     &gsn_holystrike,
     SLOT(0),
     80,
     12,
     TRUE,
     "Holystrike",
     "!Holystrike!",
     ""},

    {NORM,
     "anti magic shell",
     {NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE,
      NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE,
      NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, 2,      NO_USE, NO_USE},
     spell_null,
     TAR_CHAR_OFFENSIVE,
     POS_FIGHTING,
     &gsn_anti_magic_shell,
     SLOT(0),
     80,
     12,
     TRUE,
     "Anti Magic Shell",
     "You are no longer surrounded by an anti-magic shell!",
     "$n is no longer surrounded by an anti-magic shell."},

    {NORM,
     "sonic blast",
     {NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE,
      NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE,
      67,     NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE},
     spell_sonic_blast,
     TAR_CHAR_OFFENSIVE,
     POS_FIGHTING,
     NULL,
     SLOT(675),
     140,
     12,
     TRUE,
     "Sonic Blast",
     "@@N$nFeels much better!",
     ""},

    {NORM,
     "mystical potency",
     {20,     NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE,
      NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE,
      NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE},
     spell_null,
     TAR_IGNORE,
     POS_STANDING,
     &gsn_potency,
     SLOT(0),
     0,
     0,
     FALSE,
     "",
     "!Enhanced Damage!",
     ""},

    {NORM,
     "mystical focus",
     {NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, 55,     NO_USE,
      NO_USE, NO_USE, 48,     NO_USE, 45,     NO_USE, NO_USE, NO_USE,
      47,     NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE, NO_USE},
     spell_mystical_focus,
     TAR_CHAR_SELF,
     POS_STANDING,
     NULL,
     SLOT(676),
     200,
     10,
     TRUE,
     "",
     "Your lose your mystical focus.",
     "$N shakes his head, and seems less focused."},
